### ISSUE TITLE
test_getMapTile_found failed

### ISSUE THREAD

**Issue by trofimchyk** [osmdroid/osmdroid#106]
Hi. I'm trying to build sources. But on Integration tests stage I've got a problem:
```xml
        <testcase classname="org.osmdroid.views.util.OpenStreetMapTileProviderDirectTest" name="test_getMapTile_found" time="0.0040">
            <failure message="" type="junit.framework.AssertionFailedError">
junit.framework.AssertionFailedError: Expect tile to be not null
at org.osmdroid.views.util.OpenStreetMapTileProviderDirectTest.test_getMapTile_found(OpenStreetMapTileProviderDirectTest.java:66)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:190)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:175)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1661)
            </failure>
        </testcase>
```
Does anyone know where is the problem?

**Comment by trofimchyk** [comment]
I've got this problem after my playing with tile filters.

**Comment by kurtzmarc** [comment]
FYI - I just did a build on the trunk and did not have any tests fail. Maybe something device specific?

**Comment by trofimchyk** [comment]
@kurtzmarc I've tested on different devices & Genymotion emulators. I had build failed 9 of 10 times. Finally I did build too, but why so many test failures?

**Comment by neilboyd** [comment]
It never fails for me.  I'm using the Google x86 emulator.

**Comment by spyhunter99** [comment]
second that, haven't had any random failures.
