### ISSUE TITLE
Crash when initializing a map

### ISSUE THREAD

**Issue by StevenTB** [osmdroid/osmdroid#1079]
## Issue Type

[X] Question
[X] Bug

## Description and/or steps/code to reproduce the problem

I had a crash on a customer's phone on that line :
`Configuration.getInstance().load(getApplicationContext(), PreferenceManager.getDefaultSharedPreferences(getApplicationContext()));`

But it does work fine when I am testing on Galaxy S7, Nexus 5. Here is the Fabric's stacktrace :

` Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{ ... }: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference`

I can see that the NPE happened in the `load()` method in `DefaultConfigurationProvider.java`.

In my project, this is the line where it crashs, located in the onCreate() of my Activity, before I inflate my map: 
`Configuration.getInstance().load(this, PreferenceManager.getDefaultSharedPreferences(this));`

### If it's a bug, version(s) of android this affects:

At least Sony Xperia Z3 (6.0.1) and One Plus 5 (8.1)

### Version of osmdroid the issue relates to:

5.6.5

**Comment by StevenTB** [comment]
I can tell you that happened when a user did an update with an previous project *without* osmdroid

**Comment by cbalster** [comment]
Can you post the full stacktrace? I suspect this is an issue in `StorageUtils`.

**Comment by spyhunter99** [comment]
second that we need the line number

**Comment by StevenTB** [comment]
@spyhunter99 @cbalster Hi, thanks for your help. Here is the Fabric stacktrace : 

```
DefaultConfigurationProvider.java line 401
org.osmdroid.config.DefaultConfigurationProvider.load
```

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.xxx/com.xxx.view.trip.activity.MapActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2911)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2989)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6753)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```


```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
       at org.osmdroid.config.DefaultConfigurationProvider.load(DefaultConfigurationProvider.java:401)
       at org.osmdroid.config.DefaultConfigurationProvider.load(DefaultConfigurationProvider.java:317)
       at com.drivequant.view.trip.activity.TripActivity.onCreate(TripActivity.java:111)
       at android.app.Activity.performCreate(Activity.java:7036)
       at android.app.Activity.performCreate(Activity.java:7027)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1231)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2864)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2989)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6753)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by StevenTB** [comment]
Hi, 

If you need more information please do not hesitate to tell me how can we help each other.

Regards,

**Comment by spyhunter99** [comment]
Soonest I can look at it is Sunday, should be an easy fix

**Comment by StevenTB** [comment]
@spyhunter99 Thank you so much for your help. Did you plan to make a snapshot with that fix (and others) or do you have any release date for the v6.0.2 ? 

Regards

**Comment by spyhunter99** [comment]
It was cut Monday
