### ISSUE TITLE
is there a listener for create the cache file "cache.db" 

### ISSUE THREAD

**Issue by pavel-korolenkov** [osmdroid/osmdroid#1092]
Hello!
i use com.github.MKergall:osmbonuspack:6.5.1 and org.osmdroid:osmdroid-android:6.0.1

when i use map, cache files "cache.db" is created, but not at once
 
sometimes user delete this file and error occurs

07-12 12:38:24.789 18315-19435/xx.xxx.xxx E/SQLiteLog: (1032) statement aborts at 15: [INSERT INTO tiles(tile,expires,provider,key) VALUES (?,?,?,?)] attempt to write a readonly database
07-12 12:38:24.790 18315-19435/xx.xxx.xxx E/SQLiteDatabase: Error inserting tile=[B@2a2d5f7 expires=1531647505000 provider=2gisTile key=2517149
    android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:783)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1548)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1417)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.saveFile(SqlTileWriter.java:182)
        at org.osmdroid.tileprovider.modules.MapTileDownloader$TileLoader.loadTile(MapTileDownloader.java:250)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:315)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

i have two questions
1) is there a listener for create the cache file "cache.db"?
2) is there a listener for delete the cache file "cache.db"?

**Comment by spyhunter99** [comment]
unfortunately not. It's created with the initialization of the SqlTileWriter class. If you want, you can provide your own tile provider configuration along with a custom version of SqlTileWriter so that you can better control the creation and wire in your own listener. If you feel this should be brought mainstream, feel free to open a pr
