### ISSUE TITLE
NegativeArraySizeException on MapView.setTileSource

### ISSUE THREAD

**Issue by conej730** [osmdroid/osmdroid#1093]
## Issue Type

[X] Question
[X] Bug

## Description and/or steps/code to reproduce the problem

I'm seeing stacktraces from Crashlytics where the setTileSource on our MapView is resulting in this NegativeArraySizeException.  So far this has only affected users with v8 or v9 of Android.  Have you seen this happen anywhere else?  I haven't been able to reproduce the issue locally or work out how the maptilecache could have a negative size.  Here's the stack trace I'm seeing:

Fatal Exception: java.lang.NegativeArraySizeException: -1
       at org.osmdroid.util.MapTileList.<init>(MapTileList.java:25)
       at org.osmdroid.tileprovider.MapTileCache.clear(MapTileCache.java:149)
       at org.osmdroid.tileprovider.MapTileProviderBase.clearTileCache(MapTileProviderBase.java:269)
       at org.osmdroid.tileprovider.MapTileProviderArray.setTileSource(MapTileProviderArray.java:256)
       at org.osmdroid.views.MapView.setTileSource(MapView.java:438)
       at com.flightaware.android.liveFlightTracker.fragments.BaseMapFragment.setMapType(BaseMapFragment.java:251)
       at com.flightaware.android.liveFlightTracker.fragments.BaseMapFragment.onOptionsItemSelected(BaseMapFragment.java:605)
       at com.flightaware.android.liveFlightTracker.fragments.FlightMapFragment.onOptionsItemSelected(FlightMapFragment.java:44)
       at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2394)
       at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:3326)
       at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:344)
       at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:386)
       at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
       at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
       at android.support.v7.app.AppCompatDelegateImplV9.onMenuItemSelected(AppCompatDelegateImplV9.java:674)
       at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
       at android.support.v7.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:89)
       at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
       at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
       at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
       at android.widget.AdapterView.performItemClick(AdapterView.java:350)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1683)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:4094)
       at android.widget.AbsListView$10.run(AbsListView.java:6583)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

### If it's a bug, version(s) of android this affects:

Android v8 & v9

### Version of osmdroid the issue relates to:

6.0.1

**Comment by monsieurtanuki** [comment]
@conej730 Duplicate with #1012 I guess.
Could you please check with the latest version of osmdroid?

**Comment by spyhunter99** [comment]
i.e. use the most recent SNAPSHOT version. Just change your gradle file to use 6.0.2-SNAPSHOT and retest. Probably going to cut the new version very soon
