### ISSUE TITLE
#547 Error loading bitmapGOOGLE_IMAGE_ROAD

### ISSUE THREAD

**Issue by xiaozuozi** [osmdroid/osmdroid#1133]
java.lang.IllegalArgumentException: Problem decoding into existing bitmap
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:707)
        at org.osmdroid.tileprovider.tilesource.BitmapTileSourceBase.getDrawable(BitmapTileSourceBase.java:172)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.loadTile(SqlTileWriter.java:625)
        at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:163)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:182)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:148)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:130)
        at org.osmdroid.tileprovider.modules.MapTileApproximater$TileLoader.loadTile(MapTileApproximater.java:111)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)
08-08 16:14:45.099 16801-18177/com.jiyiuav.android.k3a W/BitmapFactory: bitmap marked for reuse (262144 bytes) can't fit new bitmap (1048576 bytes)
08-08 16:14:45.099 16801-18177/com.jiyiuav.android.k3a D/skia: --- Got null SkPixelRef
08-08 16:14:45.099 16801-18177/com.jiyiuav.android.k3a W/OsmDroid: #547 Error loading bitmapGOOGLE_IMAGE_ROAD
    java.lang.IllegalArgumentException: Problem decoding into existing bitmap
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:707)
        at org.osmdroid.tileprovider.tilesource.BitmapTileSourceBase.getDrawable(BitmapTileSourceBase.java:172)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.loadTile(SqlTileWriter.java:625)
        at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:163)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:182)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:148)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:130)
        at org.osmdroid.tileprovider.modules.MapTileApproximater$TileLoader.loadTile(MapTileApproximater.java:111)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)
08-08 16:14:45.100 16801-18215/com.jiyiuav.android.k3a W/BitmapFactory: bitmap marked for reuse (262144 bytes) can't fit new bitmap (1048576 bytes)
08-08 16:14:45.100 16801-18215/com.jiyiuav.android.k3a D/skia: --- Got null SkPixelRef
08-08 16:14:45.101 16801-18215/com.jiyiuav.android.k3a W/OsmDroid: #547 Error loading bitmapGOOGLE_IMAGE_ROAD
    java.lang.IllegalArgumentException: Problem decoding into existing bitmap
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:707)
        at org.osmdroid.tileprovider.tilesource.BitmapTileSourceBase.getDrawable(BitmapTileSourceBase.java:172)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.loadTile(SqlTileWriter.java:625)
        at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:163)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:182)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:148)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:130)
        at org.osmdroid.tileprovider.modules.MapTileApproximater$TileLoader.loadTile(MapTileApproximater.java:111)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)
08-08 16:14:45.202 16801-16812/com.jiyiuav.android.k3a I/art: Background sticky concurrent mark sweep GC freed 4979(273KB) AllocSpace objects, 26(6MB) LOS objects, 0% free, 91MB/91MB, paused 6.769ms total 54.285ms
08-08 16:14:45.266 16801-18247/com.jiyiuav.android.k3a W/BitmapFactory: bitmap marked for reuse (262144 bytes) can't fit new bitmap (1048576 bytes)
08-08 16:14:45.266 16801-18247/com.jiyiuav.android.k3a D/skia: --- Got null SkPixelRef
08-08 16:14:45.266 16801-18247/com.jiyiuav.android.k3a W/OsmDroid: #547 Error loading bitmapGOOGLE_IMAGE_ROAD
    java.lang.IllegalArgumentException: Problem decoding into existing bitmap
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:707)
        at org.osmdroid.tileprovider.tilesource.BitmapTileSourceBase.getDrawable(BitmapTileSourceBase.java:172)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.loadTile(SqlTileWriter.java:625)
        at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:163)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:182)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:148)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:130)
        at org.osmdroid.tileprovider.modules.MapTileApproximater$TileLoader.loadTile(MapTileApproximater.java:111)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)

**Comment by spyhunter99** [comment]
hmm try turning on tile provider debugging via the `Configuration` class. You're looking for an actual tile url. Then try loading it in the browser. It's more than probable that google turned off the tile service
