### ISSUE TITLE
hello,when i use setTileSource,sometime i can load the map,but the network can not load the new tile

### ISSUE THREAD

**Issue by xiaozuozi** [osmdroid/osmdroid#1134]
hello,when i use setTileSource,sometime i can load the map,but the network can not load the new tile,it shows that gcc problem ,how can i solve the problem?

**Comment by spyhunter99** [comment]
You probably have a memory leak

**Comment by xiaozuozi** [comment]
how can i solve the problem,the network is good,but the map can not load

**Comment by xiaozuozi** [comment]
public static OnlineTileSourceBase GOOGLE_IMAGE_NORMAL = new OnlineTileSourceBase("GoogleNormal", MIN_LEVEL, MAX_LEVEL, 256, ".png", new String[]{""}) {
        public String getTileURLString(final long pMapTileIndex) {
            int i = MapTileIndex.getX(pMapTileIndex);
            int j = MapTileIndex.getY(pMapTileIndex);
            int k = MapTileIndex.getZoom(pMapTileIndex);
//            LogUtils.e("eee","http://mt" + i % 4 + ".google.cn/vt/lyrs=y&hl=zh-CN&gl=cn&scale=2&x=" + i + "&y=" + j + "&z=" + k + "");
            return "http://mt" + i % 4 + ".google.cn/vt/lyrs=m&hl=zh-CN&gl=cn&scale=2&x=" + i + "&y=" + j + "&z=" + k + "";
        }
    };
this is what i use

**Comment by xiaozuozi** [comment]
08-08 20:04:09.532 18037-18048/com.jiyiuav.android.k3a I/art: Background sticky concurrent mark sweep GC freed 26000(1673KB) AllocSpace objects, 74(2MB) LOS objects, 0% free, 124MB/124MB, paused 5.272ms total 65.824ms
08-08 20:04:16.129 18037-18048/com.jiyiuav.android.k3a I/art: Background partial concurrent mark sweep GC freed 4322(189KB) AllocSpace objects, 29(12MB) LOS objects, 6% free, 218MB/234MB, paused 3.765ms total 119.788ms
08-08 20:04:20.713 18037-18042/com.jiyiuav.android.k3a I/art: Do full code cache collection, code=125KB, data=124KB
08-08 20:04:20.753 18037-18042/com.jiyiuav.android.k3a I/art: After code cache collection, code=96KB, data=89KB
this is the log,when the cache is incresing,final the map will not show

**Comment by xiaozuozi** [comment]
Error loading bitmapGOOGLE_IMAGE_ROAD
    java.lang.IllegalArgumentException: Problem decoding into existing bitmap
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:707)
        at org.osmdroid.tileprovider.tilesource.BitmapTileSourceBase.getDrawable(BitmapTileSourceBase.java:172)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.loadTile(SqlTileWriter.java:625)
        at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:163)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:182)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:148)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:130)
        at org.osmdroid.tileprovider.modules.MapTileApproximater$TileLoader.loadTile(MapTileApproximater.java:111)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)
08-08 20:06:04.057 18037-24776/com.jiyiuav.android.k3a W/BitmapFactory: bitmap marked for reuse (262144 bytes) can't fit new bitmap (1048576 bytes)
08-08 20:06:04.057 18037-24776/com.jiyiuav.android.k3a D/skia: --- Got null SkPixelRef
08-08 20:06:04.057 18037-24776/com.jiyiuav.android.k3a W/OsmDroid: #547 Error loading bitmapGOOGLE_IMAGE_ROAD
    java.lang.IllegalArgumentException: Problem decoding into existing bitmap
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:707)
        at org.osmdroid.tileprovider.tilesource.BitmapTileSourceBase.getDrawable(BitmapTileSourceBase.java:172)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.loadTile(SqlTileWriter.java:625)
        at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:163)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:182)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:148)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:130)
        at org.osmdroid.tileprovider.modules.MapTileApproximater$TileLoader.loadTile(MapTileApproximater.java:111)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)
08-08 20:06:04.063 18037-24680/com.jiyiuav.android.k3a W/BitmapFactory: bitmap marked for reuse (262144 bytes) can't fit new bitmap (1048576 bytes)
08-08 20:06:04.063 18037-24680/com.jiyiuav.android.k3a D/skia: --- Got null SkPixelRef
08-08 20:06:04.064 18037-24680/com.jiyiuav.android.k3a W/OsmDroid: #547 Error loading bitmapGOOGLE_IMAGE_ROAD
    java.lang.IllegalArgumentException: Problem decoding into existing bitmap
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:707)
        at org.osmdroid.tileprovider.tilesource.BitmapTileSourceBase.getDrawable(BitmapTileSourceBase.java:172)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.loadTile(SqlTileWriter.java:625)
        at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:163)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:182)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:148)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:130)
        at org.osmdroid.tileprovider.modules.MapTileApproximater$TileLoader.loadTile(MapTileApproximater.java:111)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)
08-08 20:06:04.342 18037-24683/com.jiyiuav.android.k3a W/BitmapFactory: bitmap marked for reuse (262144 bytes) can't fit new bitmap (1048576 bytes)
08-08 20:06:04.342 18037-24683/com.jiyiuav.android.k3a D/skia: --- Got null SkPixelRef
08-08 20:06:04.342 18037-24683/com.jiyiuav.android.k3a W/OsmDroid: #547 Error loading bitmapGOOGLE_IMAGE_ROAD
    java.lang.IllegalArgumentException: Problem decoding into existing bitmap
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:707)
        at org.osmdroid.tileprovider.tilesource.BitmapTileSourceBase.getDrawable(BitmapTileSourceBase.java:172)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.loadTile(SqlTileWriter.java:625)
        at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:163)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:182)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:148)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:130)
        at org.osmdroid.tileprovider.modules.MapTileApproximater$TileLoader.loadTile(MapTileApproximater.java:111)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)

**Comment by cbalster** [comment]
What version of osmdroid are you using?

**Comment by spyhunter99** [comment]
are you changing map tile providers by chance? Are you implementing the start/stop/destroy activity methods to also call the corresponding methods with osmdroid?

**Comment by xiaozuozi** [comment]
yes,i have use onResume/onPause/onDetach,the version is 6.0.2

**Comment by xiaozuozi** [comment]
public abstract class BaseMapView extends MapView {

    public BaseMapView(Context context) {
        super(context);
        init();
    }

    public BaseMapView(Context context, AttributeSet attributeSet) {
        super(context, attributeSet);
        init();
    }

    private void init() {
        setGoogleTile(getZoomLevelDouble());
    }

    private void setGoogleTile(double paramInt) {
        if (paramInt > 19) {
            setTileSource(GoogleTileSourceFactory.GOOGLE_IMAGE_NORMAL);
//            setTileSource(GoogleTileSourceFactory2.GoogleHybrid);
            return;
        }
        setTileSource(GoogleTileSourceFactory.GOOGLE_IMAGE_ROAD);
//        setTileSource(GoogleTileSourceFactory2.GoogleHybrid);
    }
}
this is the code

**Comment by xiaozuozi** [comment]
java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 0 free bytes and 3GB until,when i load wordmap,it crash

**Comment by xiaozuozi** [comment]
public class GoogleTileSourceFactory extends TileSourceFactory {

    private static String str;
    public static final int MIN_LEVEL=0;
    public static final int MAX_LEVEL=19;

    public static OnlineTileSourceBase GOOGLE_IMAGE = new OnlineTileSourceBase("GOOGLE_IMAGE", MIN_LEVEL, MAX_LEVEL, 256, ".png", new String[]{""}) {
        public String getTileURLString(final long pMapTileIndex) {
            int i = MapTileIndex.getX(pMapTileIndex);
            int j = MapTileIndex.getY(pMapTileIndex);
            int k = MapTileIndex.getZoom(pMapTileIndex);
            str = "Galileo".substring(0, (i * 3 + j) % 8);
//            LogUtils.e("eee","http://mt" + i % 4 + ".google.cn/vt/lyrs=s&hl=zh-CN&gl=cn&" + "x=" + i + "&" + "y=" + j + "&" + "z=" + k + "&" + "s=" + str);
            return "http://mt" + i % 4 + ".google.cn/vt/lyrs=s&hl=zh-CN&gl=cn&" + "x=" + i + "&" + "y=" + j + "&" + "z=" + k + "&" + "s=" + str;
        }
    };
    public static OnlineTileSourceBase GOOGLE_IMAGE_ROAD = new OnlineTileSourceBase("GOOGLE_IMAGE_ROAD", MIN_LEVEL, MAX_LEVEL, 256, ".png", new String[]{""}) {
        public String getTileURLString(final long pMapTileIndex) {
            int i = MapTileIndex.getX(pMapTileIndex);
            int j = MapTileIndex.getY(pMapTileIndex);
            int k = MapTileIndex.getZoom(pMapTileIndex);
//            LogUtils.e("eee","http://mt" + i % 4 + ".google.cn/vt/lyrs=y&hl=zh-CN&gl=cn&scale=2&x=" + i + "&y=" + j + "&z=" + k + "");
            return "http://mt" + i % 4 + ".google.cn/vt/lyrs=y&hl=zh-CN&gl=cn&scale=2&x=" + i + "&y=" + j + "&z=" + k + "";
        }
    };
    public static OnlineTileSourceBase GOOGLE_IMAGE_NORMAL = new OnlineTileSourceBase("GoogleNormal", MIN_LEVEL, MAX_LEVEL, 256, ".png", new String[]{""}) {
        public String getTileURLString(final long pMapTileIndex) {
            int i = MapTileIndex.getX(pMapTileIndex);
            int j = MapTileIndex.getY(pMapTileIndex);
            int k = MapTileIndex.getZoom(pMapTileIndex);
//            LogUtils.e("eee","http://mt" + i % 4 + ".google.cn/vt/lyrs=y&hl=zh-CN&gl=cn&scale=2&x=" + i + "&y=" + j + "&z=" + k + "");
            return "http://mt" + i % 4 + ".google.cn/vt/lyrs=m&hl=zh-CN&gl=cn&scale=2&x=" + i + "&y=" + j + "&z=" + k + "";
        }
    };
    public static OnlineTileSourceBase GOOGLE_NET_ROAD = new OnlineTileSourceBase("GOOGLE_NET_ROAD", MIN_LEVEL, MAX_LEVEL, 256, ".png", new String[]{""}) {
        public String getTileURLString(final long pMapTileIndex) {
            int i = MapTileIndex.getX(pMapTileIndex);
            int j = MapTileIndex.getY(pMapTileIndex);
            int k = MapTileIndex.getZoom(pMapTileIndex);
            str = "Galileo".substring(0, (i * 3 + j) % 8);
            return "http://mt" + i % 4 + ".google.cn/vt/imgtp=png32&lyrs=h@169000000&hl=zh-CN&gl=cn&" + "x=" + i + "&" + "y=" + j + "&" + "z=" + k + "&" + "s=" + str;
        }
    };
}

**Comment by xiaozuozi** [comment]
public class CaoBugsMapView extends BaseMapView {
    public CaoBugsMapView(Context context)
    {
        super(context);
    }

    public CaoBugsMapView(Context paramContext, AttributeSet attributeSet)
    {
        super(paramContext, attributeSet);
        initMapSetting();
    }

    private void initMapSetting()
    {
        setTilesScaledToDpi(true);
    }
}

**Comment by xiaozuozi** [comment]
08-14 07:31:58.892 16041-16058/com.jiyiuav.android.k3a I/art: Background sticky concurrent mark sweep GC freed 39100(1659KB) AllocSpace objects, 40(11MB) LOS objects, 11% free, 90MB/103MB, paused 5.574ms total 51.947ms
08-14 07:32:00.605 16041-16058/com.jiyiuav.android.k3a I/art: Background partial concurrent mark sweep GC freed 20436(936KB) AllocSpace objects, 48(17MB) LOS objects, 13% free, 100MB/116MB, paused 2.559ms total 143.986ms
08-14 07:32:01.634 16041-16058/com.jiyiuav.android.k3a I/art: Background partial concurrent mark sweep GC freed 58056(2MB) AllocSpace objects, 70(25MB) LOS objects, 14% free, 94MB/110MB, paused 1.865ms total 122.980ms
08-14 07:32:01.662 16041-17013/com.jiyiuav.android.k3a W/BitmapFactory: bitmap marked for reuse (262144 bytes) can't fit new bitmap (1048576 bytes)
08-14 07:32:01.662 16041-17013/com.jiyiuav.android.k3a D/skia: --- Got null SkPixelRef
08-14 07:32:01.662 16041-17013/com.jiyiuav.android.k3a W/OsmDroid: #547 Error loading bitmapGOOGLE_IMAGE_ROAD
    java.lang.IllegalArgumentException: Problem decoding into existing bitmap
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:707)
        at org.osmdroid.tileprovider.tilesource.BitmapTileSourceBase.getDrawable(BitmapTileSourceBase.java:172)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.loadTile(SqlTileWriter.java:625)
        at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:163)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:182)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:148)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:130)
        at org.osmdroid.tileprovider.modules.MapTileApproximater$TileLoader.loadTile(MapTileApproximater.java:111)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)
08-14 07:32:01.715 16041-17001/com.jiyiuav.android.k3a W/BitmapFactory: bitmap marked for reuse (262144 bytes) can't fit new bitmap (1048576 bytes)
08-14 07:32:01.716 16041-17001/com.jiyiuav.android.k3a D/skia: --- Got null SkPixelRef
08-14 07:32:01.719 16041-17001/com.jiyiuav.android.k3a W/OsmDroid: #547 Error loading bitmapGOOGLE_IMAGE_ROAD
    java.lang.IllegalArgumentException: Problem decoding into existing bitmap
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:707)
        at org.osmdroid.tileprovider.tilesource.BitmapTileSourceBase.getDrawable(BitmapTileSourceBase.java:172)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.loadTile(SqlTileWriter.java:625)
        at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:163)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:182)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:148)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:130)
        at org.osmdroid.tileprovider.modules.MapTileApproximater$TileLoader.loadTile(MapTileApproximater.java:111)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)
08-14 07:32:02.260 16041-16046/com.jiyiuav.android.k3a I/art: Do partial code cache collection, code=126KB, data=124KB
08-14 07:32:02.260 16041-16046/com.jiyiuav.android.k3a I/art: After code cache collection, code=125KB, data=123KB
    Increasing code cache capacity to 512KB
08-14 07:32:07.940 16041-17001/com.jiyiuav.android.k3a W/BitmapFactory: bitmap marked for reuse (262144 bytes) can't fit new bitmap (1048576 bytes)
08-14 07:32:07.940 16041-17001/com.jiyiuav.android.k3a D/skia: --- Got null SkPixelRef
08-14 07:32:07.940 16041-17001/com.jiyiuav.android.k3a W/OsmDroid: #547 Error loading bitmapGOOGLE_IMAGE_ROAD
    java.lang.IllegalArgumentException: Problem decoding into existing bitmap
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:707)
        at org.osmdroid.tileprovider.tilesource.BitmapTileSourceBase.getDrawable(BitmapTileSourceBase.java:172)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.loadTile(SqlTileWriter.java:625)
        at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:163)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:182)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:148)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:130)
        at org.osmdroid.tileprovider.modules.MapTileApproximater$TileLoader.loadTile(MapTileApproximater.java:111)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)
08-14 07:32:08.160 16041-16060/com.jiyiuav.android.k3a D/HwCust: Create obj success use class android.telephony.HwCustSignalStrengthImpl
08-14 07:32:14.350 16041-17017/com.jiyiuav.android.k3a W/BitmapFactory: bitmap marked for reuse (262144 bytes) can't fit new bitmap (1048576 bytes)
08-14 07:32:14.350 16041-17017/com.jiyiuav.android.k3a D/skia: --- Got null SkPixelRef
08-14 07:32:14.351 16041-17017/com.jiyiuav.android.k3a W/OsmDroid: #547 Error loading bitmapGOOGLE_IMAGE_ROAD
    java.lang.IllegalArgumentException: Problem decoding into existing bitmap
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:707)
        at org.osmdroid.tileprovider.tilesource.BitmapTileSourceBase.getDrawable(BitmapTileSourceBase.java:172)
        at org.osmdroid.tileprovider.modules.TileDownloader.downloadTile(TileDownloader.java:155)
        at org.osmdroid.tileprovider.modules.MapTileDownloader$TileLoader.downloadTile(MapTileDownloader.java:210)
        at org.osmdroid.tileprovider.modules.MapTileDownloader$TileLoader.loadTile(MapTileDownloader.java:239)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)
this is logcat shows

**Comment by xiaozuozi** [comment]
OsmDroid: OutOfMemoryError loading bitmap

**Comment by xiaozuozi** [comment]
08-14 10:04:04.843 17779-20007/com.jiyiuav.android.k3a E/OsmDroid: OutOfMemoryError loading bitmap
08-14 10:04:06.257 17779-20007/com.jiyiuav.android.k3a E/OsmDroid: OutOfMemoryError loading bitmap
08-14 10:04:06.739 17779-19648/com.jiyiuav.android.k3a E/OsmDroid: OutOfMemoryError loading bitmap
08-14 10:04:07.046 17779-19652/com.jiyiuav.android.k3a E/OsmDroid: OutOfMemoryError loading bitmap
08-14 10:04:07.135 17779-19653/com.jiyiuav.android.k3a E/OsmDroid: Error loading tile
    android.database.sqlite.SQLiteException: unknown error (Sqlite code 0): Native could not create new byte[], (OS error - 0:Success)
        at android.database.CursorWindow.nativeGetBlob(Native Method)
        at android.database.CursorWindow.getBlob(CursorWindow.java:403)
        at android.database.AbstractWindowedCursor.getBlob(AbstractWindowedCursor.java:45)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.loadTile(SqlTileWriter.java:614)
        at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:163)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)
08-14 10:04:07.248 17779-19651/com.jiyiuav.android.k3a E/OsmDroid: OutOfMemoryError loading bitmap
08-14 10:04:07.339 17779-17779/com.jiyiuav.android.k3a E/OsmDroid: OutOfMemoryError rescaling cache
08-14 10:04:07.553 17779-19650/com.jiyiuav.android.k3a E/OsmDroid: OutOfMemoryError loading bitmap
08-14 10:04:07.665 17779-19647/com.jiyiuav.android.k3a E/OsmDroid: OutOfMemoryError loading bitmap
08-14 10:04:07.997 17779-19649/com.jiyiuav.android.k3a E/OsmDroid: OutOfMemoryError loading bitmap
08-14 10:04:08.522 17779-17779/com.jiyiuav.android.k3a E/OsmDroid: OutOfMemoryError rescaling cache
08-14 10:04:11.065 17779-19645/com.jiyiuav.android.k3a E/OsmDroid: OutOfMemoryError loading bitmap
08-14 10:04:11.207 17779-19684/com.jiyiuav.android.k3a E/OsmDroid: OutOfMemoryError loading bitmap
08-14 10:04:11.534 17779-17792/com.jiyiuav.android.k3a E/Binder: Caught an OutOfMemoryError from the binder stub implementation.
    java.lang.OutOfMemoryError: Failed to allocate a 104 byte allocation with 376 free bytes and 376B until OOM
        at android.os.Parcel.nativeReadString(Native Method)
        at android.os.Parcel.readString(Parcel.java:1719)
        at android.location.IGnssStatusListener$Stub.onTransact(IGnssStatusListener.java:90)
        at android.os.Binder.execTransact(Binder.java:565)
08-14 10:04:11.840 17779-17788/com.jiyiuav.android.k3a E/System: Uncaught exception thrown by finalizer
08-14 10:04:11.892 17779-19666/com.jiyiuav.android.k3a E/OsmDroid: OutOfMemoryError loading bitmap
08-14 10:04:11.904 17779-17792/com.jiyiuav.android.k3a E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
    java.lang.RuntimeException: Out of memory
        at android.os.Binder.execTransact(Binder.java:584)
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 104 byte allocation with 376 free bytes and 376B until OOM
        at android.os.Parcel.nativeReadString(Native Method)
        at android.os.Parcel.readString(Parcel.java:1719)
        at android.location.IGnssStatusListener$Stub.onTransact(IGnssStatusListener.java:90)
        at android.os.Binder.execTransact(Binder.java:565)
08-14 10:04:15.254 17779-19681/com.jiyiuav.android.k3a E/OsmDroid: OutOfMemoryError loading bitmap
08-14 10:04:16.239 17779-19679/com.jiyiuav.android.k3a E/OsmDroid: OutOfMemoryError loading bitmap
08-14 10:04:17.468 17779-17788/com.jiyiuav.android.k3a E/System: java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 376 free bytes and 376B until OOM
08-14 10:04:17.468 17779-19684/com.jiyiuav.android.k3a E/OsmDroid: Error loading tile
    java.lang.OutOfMemoryError: Failed to allocate a 34 byte allocation with 0 free bytes and 3GB until OOM
        at java.lang.Long.toString(Long.java:268)
        at java.lang.String.valueOf(String.java:2801)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.getPrimaryKeyParameters(SqlTileWriter.java:577)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.getPrimaryKeyParameters(SqlTileWriter.java:566)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.loadTile(SqlTileWriter.java:609)
        at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:163)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:182)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:148)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:130)
        at org.osmdroid.tileprovider.modules.MapTileApproximater$TileLoader.loadTile(MapTileApproximater.java:111)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)
08-14 10:04:17.481 17779-19681/com.jiyiuav.android.k3a E/OsmDroid: Error loading tile
    java.lang.OutOfMemoryError: Failed to allocate a 28 byte allocation with 3776 free bytes and 3KB until OOM
        at org.osmdroid.tileprovider.tilesource.BitmapTileSourceBase.getDrawable(BitmapTileSourceBase.java:179)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.loadTile(SqlTileWriter.java:625)
        at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:163)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:182)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:148)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:130)
        at org.osmdroid.tileprovider.modules.MapTileApproximater$TileLoader.loadTile(MapTileApproximater.java:111)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)
08-14 10:04:17.518 17779-17791/com.jiyiuav.android.k3a E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
    java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 3776 free bytes and 3KB until OOM
        at android.os.Parcel.obtain(Parcel.java:2631)
        at android.os.Binder.execTransact(Binder.java:556)
