### ISSUE TITLE
IllegalStateException in ZipFileArchive

### ISSUE THREAD

**Issue by JonasDaWi** [osmdroid/osmdroid#1162]
I have an Offline Map App with a map in osmdroid zip format. I display the map in a fragment. When i close the Fragment I sometimes get following crash (happens after .onStop() is called)

## Issue Type
[x] Bug

## Description and/or steps/code to reproduce the problem
When i close my Mapfragment, I sometimes (rarely) get a crash in Line 51 of ZipFileArchive:
`final ZipEntry entry = mZipFile.getEntry(path);`

> E/OsmDroid: Error loading tile
>     java.lang.IllegalStateException: zip file closed
>         at java.util.zip.ZipFile.ensureOpen(ZipFile.java:654)
>         at java.util.zip.ZipFile.getEntry(ZipFile.java:315)
>         at org.osmdroid.tileprovider.modules.ZipFileArchive.getInputStream(ZipFileArchive.java:51)
>         at org.osmdroid.tileprovider.modules.MapTileFileArchiveProvider.getInputStream(MapTileFileArchiveProvider.java:195)
>         at org.osmdroid.tileprovider.modules.MapTileFileArchiveProvider.access$100(MapTileFileArchiveProvider.java:29)
>         at org.osmdroid.tileprovider.modules.MapTileFileArchiveProvider$TileLoader.loadTile(MapTileFileArchiveProvider.java:229)
>         at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:312)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
>         at java.lang.Thread.run(Thread.java:762)

## Environment
Samsung S6, Android 7

### If it's a bug, version(s) of android this affects:
7

### Version of osmdroid the issue relates to:

6.0.2

**Comment by spyhunter99** [comment]
hmm this is probably related to the strict mode fixes that was put in a few versions ago. Are you reusing instances of the mapview or have a static reference to it?

**Comment by JonasDaWi** [comment]
I have a non-static reference of the mapview in a fragment, but it crashes even when it is not reused

**Comment by spyhunter99** [comment]
try setting strict mode for your app. I'm willing to bet you have a
resource leak somewhere

**Comment by JonasDaWi** [comment]
update: the crash is happening on 6.0.3, too. I checked with StrictMode, and no leak was detected.
Before the crash, some of these messages occur:
TileLoader failed to load tile due to mWriter being null (map shutdown?)
TileLoader failed to load tile due to mWriter being null (map shutdown?)
TileLoader failed to load tile due to mWriter being null (map shutdown?)
TileLoader failed to load tile due to mWriter being null (map shutdown?)
TileLoader failed to load tile due to mWriter being null (map shutdown?)

**Comment by JonasDaWi** [comment]
And maybe this has something to do with it, too:
 D/skia: ---- read threw an exception
 D/skia: ------ png error Read Error!
 D/skia: --- SkAndroidCodec::NewFromStream returned null

**Comment by spyhunter99** [comment]
is this still reproducible?
