### ISSUE TITLE
Custom Tile Source

### ISSUE THREAD

**Issue by stefanhuber** [osmdroid/osmdroid#1188]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[x ] Question
[x ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[x ] Documentation

## Description and/or steps/code to reproduce the problem

```java
public class MainActivity extends AppCompatActivity {

    MapView map = null;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        map = (MapView) findViewById(R.id.map);
        map.setTileSource(new OnlineTileSourceBase("basemap", 7, 16, 256, "png",
                new String[] { "https://maps2.wien.gv.at/basemap/geolandbasemap/normal/google3857/" }) {

            @Override
            public String getTileURLString(long pMapTileIndex) {
                String url = getBaseUrl()
                        + MapTileIndex.getZoom(pMapTileIndex)
                        + "/" + MapTileIndex.getY(pMapTileIndex)
                        + "/" + MapTileIndex.getX(pMapTileIndex)
                        + "." + mImageFilenameEnding;

                Log.i("MAP_EXAMPLE", url);

                return url;
            }
        });
        map.setBuiltInZoomControls(true);
        map.setMultiTouchControls(true);

        IMapController mapController = map.getController();
        mapController.setZoom(14);
        GeoPoint startPoint = new GeoPoint(47.584072, 12.173591);
        mapController.setCenter(startPoint);
    }
}
```

I have created a custom online TileSource. I try to start the project on an emulator Version 8.1 and also a Device with Android Version 6.

Unfortunately the mapview is empty. I only get errors:
```
11-05 16:29:56.792 11742-11945/com.example.mymap E/SQLiteDatabase: Failed to open database '/storage/emulated/0/osmdroid/tiles/cache.db'.
    android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 1294): Could not open database
    #################################################################
    Error Code : 1294 (SQLITE_CANTOPEN_ENOENT)
    Caused By : Specified directory or database file does not exist.
    	(unknown error (code 1294): Could not open database)
    #################################################################
        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:283)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:210)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:512)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:178)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:908)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:878)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:699)
        at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:714)
        at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:707)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.getDb(SqlTileWriter.java:727)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.getTileCursor(SqlTileWriter.java:588)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.loadTile(SqlTileWriter.java:609)
        at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:163)
        at org.osmdroid.tileprovider.MapTilePreCache.search(MapTilePreCache.java:100)
        at org.osmdroid.tileprovider.MapTilePreCache.access$100(MapTilePreCache.java:27)
        at org.osmdroid.tileprovider.MapTilePreCache$1.run(MapTilePreCache.java:38)
        at org.osmdroid.util.GarbageCollector$1.run(GarbageCollector.java:31)
        at java.lang.Thread.run(Thread.java:818)
```

```
11-05 16:29:56.792 11742-11945/com.example.mymap E/OsmDroid: Error loading tile
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.Cursor android.database.sqlite.SQLiteDatabase.query(java.lang.String, java.lang.String[], java.lang.String, java.lang.String[], java.lang.String, java.lang.String, java.lang.String)' on a null object reference
        at org.osmdroid.tileprovider.modules.SqlTileWriter.getTileCursor(SqlTileWriter.java:589)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.loadTile(SqlTileWriter.java:609)
        at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:163)
        at org.osmdroid.tileprovider.MapTilePreCache.search(MapTilePreCache.java:100)
        at org.osmdroid.tileprovider.MapTilePreCache.access$100(MapTilePreCache.java:27)
        at org.osmdroid.tileprovider.MapTilePreCache$1.run(MapTilePreCache.java:38)
        at org.osmdroid.util.GarbageCollector$1.run(GarbageCollector.java:31)
        at java.lang.Thread.run(Thread.java:818)
```

**The example from the documentation with the default `MAPNIK` provider doesn't work either!**

### If it's a bug, version(s) of android this affects:

Testet on: Emulator 8.1, Device 6.0.1

### Version of osmdroid the issue relates to:

6.0.2

**Comment by stefanhuber** [comment]
```
2018-11-05 16:42:39.242 20036-20070/com.example.mymap E/SQLiteLog: (14) cannot open file at line 35803 of [605907e73a]
2018-11-05 16:42:39.242 20036-20070/com.example.mymap E/SQLiteLog: (14) os_unix.c:35803: (2) open(/storage/emulated/0/osmdroid/tiles/cache.db) - 
2018-11-05 16:42:39.242 20036-20070/com.example.mymap E/SQLiteDatabase: Failed to open database '/storage/emulated/0/osmdroid/tiles/cache.db'.
    android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:210)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:194)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:493)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:200)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:192)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:864)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:849)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:750)
        at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:767)
        at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:759)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.getDb(SqlTileWriter.java:727)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.getTileCursor(SqlTileWriter.java:588)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.loadTile(SqlTileWriter.java:609)
        at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:163)
        at org.osmdroid.tileprovider.MapTilePreCache.search(MapTilePreCache.java:100)
        at org.osmdroid.tileprovider.MapTilePreCache.access$100(MapTilePreCache.java:27)
        at org.osmdroid.tileprovider.MapTilePreCache$1.run(MapTilePreCache.java:38)
        at org.osmdroid.util.GarbageCollector$1.run(GarbageCollector.java:31)
        at java.lang.Thread.run(Thread.java:764)
2018-11-05 16:42:39.242 20036-20070/com.example.mymap E/OsmDroid: Unable to start the sqlite tile writer. Check external storage availability.
    android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:210)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:194)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:493)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:200)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:192)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:864)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:849)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:750)
        at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:767)
        at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:759)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.getDb(SqlTileWriter.java:727)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.getTileCursor(SqlTileWriter.java:588)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.loadTile(SqlTileWriter.java:609)
        at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:163)
        at org.osmdroid.tileprovider.MapTilePreCache.search(MapTilePreCache.java:100)
        at org.osmdroid.tileprovider.MapTilePreCache.access$100(MapTilePreCache.java:27)
        at org.osmdroid.tileprovider.MapTilePreCache$1.run(MapTilePreCache.java:38)
        at org.osmdroid.util.GarbageCollector$1.run(GarbageCollector.java:31)
        at java.lang.Thread.run(Thread.java:764)
2018-11-05 16:42:39.242 20036-20070/com.example.mymap E/OsmDroid: Error loading tile
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.Cursor android.database.sqlite.SQLiteDatabase.query(java.lang.String, java.lang.String[], java.lang.String, java.lang.String[], java.lang.String, java.lang.String, java.lang.String)' on a null object reference
        at org.osmdroid.tileprovider.modules.SqlTileWriter.getTileCursor(SqlTileWriter.java:589)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.loadTile(SqlTileWriter.java:609)
        at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:163)
        at org.osmdroid.tileprovider.MapTilePreCache.search(MapTilePreCache.java:100)
        at org.osmdroid.tileprovider.MapTilePreCache.access$100(MapTilePreCache.java:27)
        at org.osmdroid.tileprovider.MapTilePreCache$1.run(MapTilePreCache.java:38)
        at org.osmdroid.util.GarbageCollector$1.run(GarbageCollector.java:31)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by stefanhuber** [comment]
ok, sry I forgot those lines in the `onCreate` Method:

```java
Context ctx = getApplicationContext();
Configuration.getInstance().load(ctx, PreferenceManager.getDefaultSharedPreferences(ctx));
```
