### ISSUE TITLE
error zoom or rotate

### ISSUE THREAD

**Issue by nicolae1992** [osmdroid/osmdroid#1222]
Error rotate and zoom
```
2018-12-03 16:52:00.733 4356-4577/md.point.map W/art: "approximater" prio=5 tid=58 Runnable
2018-12-03 16:52:00.733 4356-4577/md.point.map W/art:   | group="main" sCount=0 dsCount=0 obj=0x12c220d0 self=0xcbedfb00
2018-12-03 16:52:00.733 4356-4577/md.point.map W/art:   | sysTid=4577 nice=0 cgrp=default sched=0/0 handle=0xc7e5c920
2018-12-03 16:52:00.733 4356-4577/md.point.map W/art:   | state=R schedstat=( 0 0 0 ) utm=222 stm=6 core=7 HZ=100
2018-12-03 16:52:00.733 4356-4577/md.point.map W/art:   | stack=0xc7d5a000-0xc7d5c000 stackSize=1038KB
2018-12-03 16:52:00.733 4356-4577/md.point.map W/art:   | held mutexes= "mutator lock"(shared held)
2018-12-03 16:52:00.733 4356-4577/md.point.map W/art:     at java.util.HashMap.inflateTable(HashMap.java:287)
2018-12-03 16:52:00.733 4356-4577/md.point.map W/art:     at java.util.HashMap.put(HashMap.java:419)
2018-12-03 16:52:00.733 4356-4577/md.point.map W/art:     at android.database.sqlite.SQLiteCursor.getColumnIndex(SQLiteCursor.java:171)
2018-12-03 16:52:00.733 4356-4577/md.point.map W/art:     at org.osmdroid.tileprovider.modules.SqlTileWriter.loadTile(SqlTileWriter.java:615)
2018-12-03 16:52:00.733 4356-4577/md.point.map W/art:     at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:163)
2018-12-03 16:52:00.733 4356-4577/md.point.map W/art:     at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:183)
2018-12-03 16:52:00.733 4356-4577/md.point.map W/art:     at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:149)
2018-12-03 16:52:00.733 4356-4577/md.point.map W/art:     at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:131)
2018-12-03 16:52:00.733 4356-4577/md.point.map W/art:     at org.osmdroid.tileprovider.modules.MapTileApproximater$TileLoader.loadTile(MapTileApproximater.java:112)
2018-12-03 16:52:00.733 4356-4577/md.point.map W/art:     at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:312)
2018-12-03 16:52:00.733 4356-4577/md.point.map W/art:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2018-12-03 16:52:00.733 4356-4577/md.point.map W/art:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2018-12-03 16:52:00.733 4356-4577/md.point.map W/art:     at java.lang.Thread.run(Thread.java:762)

```
## Issue Type

[ ] Question
[x] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.3

**Comment by nicolae1992** [comment]
zoom 19 and fast zoom 20... rotate left right.. but add this line:
`map.getTileProvider().getTileCache().setAutoEnsureCapacity(false);` 
and work

**Comment by monsieurtanuki** [comment]
Still cannot reproduce the bug, but if you say that `map.getTileProvider().getTileCache().setAutoEnsureCapacity(false);` has a positive impact, I'd say it's a (very strange) memory side effect.
As it was also the source of #1217, I guess it's safer to `setAutoEnsureCapacity` to `false` by default.

Just PR'ed #1225. Feel free to test it and to close the issue if solved.

**Comment by spyhunter99** [comment]
this doesn't look like a crash stack trace unless it was truncated. What is the exact exception that's thrown? or is it a native thing?

**Comment by monsieurtanuki** [comment]
@nicolae1992 May we close this issue?

**Comment by nicolae1992** [comment]
@monsieurtanuki yes
