### ISSUE TITLE
Crash when opening map. NullPointerException

### ISSUE THREAD

**Issue by panovvitalik** [osmdroid/osmdroid#1223]
Caused by: java.lang.NullPointerException: 
  at org.osmdroid.views.MapViewRepository.getDefaultMarkerIcon (MapViewRepository.java:71)
  at org.osmdroid.views.overlay.Marker.setDefaultIcon (Marker.java:139)
  at org.osmdroid.views.overlay.Marker.<init> (Marker.java:114)
  at org.osmdroid.views.overlay.Marker.<init> (Marker.java:92)
  at vitalypanov.phototracker.utils.MapOpenStreetUtils$BaseMarker.<init> (MapOpenStreetUtils.java:64)

## Issue Type

[ ] Question
[ x] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
Sometimes occure when showing map

### If it's a bug, version(s) of android this affects:
All

### Version of osmdroid the issue relates to:
6.0.3

**Comment by panovvitalik** [comment]
Crash occure on this variable:
private MapViewRepository mMapViewRepository;
Unfortuntely it's declared as private and I cant acces it and check for null value in super class :(

**Comment by panovvitalik** [comment]
The only way I see now, to fix this crash is extends Marker class
and ovveride method:
        ```
@Override
        public void setDefaultIcon() {
            // mIcon = mMapViewRepository.getDefaultMarkerIcon();
            setAnchor(ANCHOR_CENTER, ANCHOR_BOTTOM);
        }
```

**Comment by panovvitalik** [comment]
Ohhh :( as a result for fixing this bug, I get full code of Marker class to my project and rewrite constructor and setDefaultIcon method and some other short changes to point on my class, not on Marker.
Very terrible solution but I have no other idea to fix it. Main code for fixing the bug below

public class BaseMarker extends OverlayWithIW {
...
public BaseMarker(MapView mapView, final Context resourceProxy) {
        super();
        if (!Utils.isNull(mapView)) {
            mMapViewRepository = mapView.getRepository();
        }
        if (!Utils.isNull(mapView.getContext())) {
            mResources = mapView.getContext().getResources();
        }
        mBearing = 0.0f;
        mAlpha = 1.0f; //opaque
        mPosition = new GeoPoint(0.0, 0.0);
        mAnchorU = ANCHOR_CENTER;
        mAnchorV = ANCHOR_CENTER;
        mIWAnchorU = ANCHOR_CENTER;
        mIWAnchorV = ANCHOR_TOP;
        mDraggable = false;
        mIsDragged = false;
        mPositionPixels = new Point();
        mPanToView = true;
        mDragOffsetY = 0.0f;
        mFlat = false; //billboard
        mOnMarkerClickListener = null;
        mOnMarkerDragListener = null;
        setDefaultIcon();
        if (!Utils.isNull(mMapViewRepository)) {
            setInfoWindow(mMapViewRepository.getDefaultMarkerInfoWindow());
        }
    }
...
 public void setDefaultIcon() {
        if (!Utils.isNull(mMapViewRepository)) {
            mIcon = mMapViewRepository.getDefaultMarkerIcon();
        }
        setAnchor(ANCHOR_CENTER, ANCHOR_BOTTOM);
    }
....
}

**Comment by monsieurtanuki** [comment]
I don't know the context of this issue, and I can tell you that I can see Marker default icons in my tests.
How do you get this bug?

`mRepository` cannot be `null`, cf. `MapView`:
````java
private final MapViewRepository mRepository = new MapViewRepository(this);
````

"at org.osmdroid.views.MapViewRepository.getDefaultMarkerIcon (MapViewRepository.java:71)" is
````java
mDefaultMarkerIcon = mMapView.getContext().getResources().getDrawable(R.drawable.marker_default);
````

`mMapView` cannot be `null`, unless you call `mMapView.onDetach()`. Do you call this `onDetach` method and expect the map view to work afterwards?

**Comment by panovvitalik** [comment]
> I don't know the context of this issue, and I can tell you that I can see Marker default icons in my tests.
> How do you get this bug?
I get it from end users. I can't reproduce it directly, it occure from time to time in production app.

> ```
> 
> `mMapView` cannot be `null`, unless you call `mMapView.onDetach()`. Do you call this `onDetach` method and expect the map view to work afterwards?
Of course I'm not creating Marker objects in onDetach method.

**Comment by monsieurtanuki** [comment]
Are you creating Markers _after_ onDetach has been called?

**Comment by panovvitalik** [comment]
> Are you creating Markers _after_ onDetach has been called?

No

**Comment by panovvitalik** [comment]
It looks like release 6.0.3 is unstable  :(
(at least in my app)
I rolled back to 6.0.2

**Comment by panovvitalik** [comment]
> @panovvitalik If you want the bug to be fixed, I suggest that you create a mini app where you reproduce the bug.
I can't reproduce this bug on developer machine as I mentioned above. 
It occure in production env. from time to time.
I can provide full crash stack only if it helps to find out the solution.
For example:

Today, 1:59 PM on app version 136
Xiaomi Redmi Note 5A (ugg), Android 7.1
Report 1 of 1
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2755)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2816)
  at android.app.ActivityThread.handleRelaunchActivity (ActivityThread.java:4651)
  at android.app.ActivityThread.-wrap19 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1563)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:163)
  at android.app.ActivityThread.main (ActivityThread.java:6383)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:904)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:794)
Caused by: java.lang.NullPointerException: 
  at org.osmdroid.views.MapViewRepository.getDefaultMarkerIcon (MapViewRepository.java:71)
  at org.osmdroid.views.overlay.Marker.setDefaultIcon (Marker.java:139)
  at org.osmdroid.views.overlay.Marker.<init> (Marker.java:114)
  at org.osmdroid.views.overlay.Marker.<init> (Marker.java:92)
  at vitalypanov.phototracker.utils.MapOpenStreetUtils$BaseMarker.<init> (MapOpenStreetUtils.java:64)
  at vitalypanov.phototracker.utils.MapOpenStreetUtils$UserMarker.<init> (MapOpenStreetUtils.java:87)
  at vitalypanov.phototracker.utils.MapOpenStreetUtils$DistanceMarker.<init> (MapOpenStreetUtils.java:94)
  at vitalypanov.phototracker.utils.MapOpenStreetUtils.getDistanceMarkers (MapOpenStreetUtils.java:265)
  at vitalypanov.phototracker.utils.MapOpenStreetUtils.addTrackData (MapOpenStreetUtils.java:318)
  at vitalypanov.phototracker.fragment.MapOpenStreetSupportFragment.reloadTrackData (MapOpenStreetSupportFragment.java:522)
  at vitalypanov.phototracker.fragment.MapOpenStreetSupportFragment.access$1500 (MapOpenStreetSupportFragment.java:97)
  at vitalypanov.phototracker.fragment.MapOpenStreetSupportFragment$21$1.run (MapOpenStreetSupportFragment.java:947)
  at android.app.Activity.runOnUiThread (Activity.java:6040)
  at vitalypanov.phototracker.fragment.MapOpenStreetSupportFragment$21.onActivityEnabled (MapOpenStreetSupportFragment.java:944)
  at vitalypanov.phototracker.fragment.BaseFragment.onAttach (BaseFragment.java:29)
  at android.support.v4.app.Fragment.onAttach (Fragment.java:1422)
  at vitalypanov.phototracker.fragment.BaseFragment.onAttach (BaseFragment.java:36)
  at android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1404)
  at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState (FragmentManager.java:1784)
  at android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1852)
  at android.support.v4.app.FragmentManagerImpl.dispatchStateChange (FragmentManager.java:3269)
  at android.support.v4.app.FragmentManagerImpl.dispatchCreate (FragmentManager.java:3223)
  at android.support.v4.app.FragmentController.dispatchCreate (FragmentController.java:190)
  at android.support.v4.app.FragmentActivity.onCreate (FragmentActivity.java:369)
  at android.support.v7.app.AppCompatActivity.onCreate (AppCompatActivity.java:85)
  at vitalypanov.phototracker.activity.RunningTrackPagerActivity.onCreate (RunningTrackPagerActivity.java:58)
  at android.app.Activity.performCreate (Activity.java:6861)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1119)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2708)

**Comment by spyhunter99** [comment]
on detach is also called when the activity is recycled, such as changing activities, device rotation, etc. could that be a factor?

**Comment by mueller-ma** [comment]
Same here:

````
06-01 21:33:04.044 org.openhab.habdroid.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.openhab.habdroid.beta, PID: 9943
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.osmdroid.views.MapView.getContext()' on a null object reference
        at org.osmdroid.views.MapViewRepository.getDefaultMarkerIcon(MapViewRepository.java:74)
        at org.osmdroid.views.overlay.Marker.setDefaultIcon(Marker.java:139)
        at org.osmdroid.views.overlay.Marker.<init>(Marker.java:114)
        at org.osmdroid.views.overlay.Marker.<init>(Marker.java:92)
        at org.openhab.habdroid.ui.MapViewHelper$OsmViewHolder.setMarker(MapViewHelper.java:230)
````

**Comment by spyhunter99** [comment]
i just added some NPE checks and updated the javadocs. Snapshots have been updated too. Can you try and reproduce the issue? I fear this commit will only reveal other issue.

**Comment by imcosta** [comment]
Same with 6.1.0. 

> Fatal Exception: java.lang.NullPointerException
> Attempt to invoke virtual method 'android.content.Context org.osmdroid.views.MapView.getContext()' on a null object reference
> org.osmdroid.views.MapViewRepository.getDefaultMarkerIcon (MapViewRepository.java:74)
> org.osmdroid.views.overlay.Marker.setDefaultIcon (Marker.java:139)
> org.osmdroid.views.overlay.Marker.<init> (Marker.java:114)
> org.osmdroid.views.overlay.Marker.<init> (Marker.java:92)

**Comment by spyhunter99** [comment]
MapViewRepository.java:74 is a javadoc line so i bet your snapshot is out of date @imcosta

**Comment by spyhunter99** [comment]
v6.1.1 is out, test when you can

**Comment by DaniilPavlenko** [comment]
Are you using MOXY or NavigationDrawer in your project?
@panovvitalik @imcosta

**Comment by panovvitalik** [comment]
@DaniilPavlenko no

**Comment by DaniilPavlenko** [comment]
@panovvitalik Try to open your app where you use map, switch to Multi-window mode and then resize your window. Was the application crashing?

**Comment by DaniilPavlenko** [comment]
@spyhunter99 In my case it happens when I use DrawerBuilder....build() (it removes all views in root view), after that Repository detached. But when it attached again view doesn't recreate and repository doesn't initialize. In my opinion repository and all other need to be recreated on `onAttachedToWindow`, but you just call super method.
Sorry for my English.
