### ISSUE TITLE
Crash when closing activity on which is osmdroid.MapView

### ISSUE THREAD

**Issue by panovvitalik** [osmdroid/osmdroid#1224]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: vitalypanov.phototracker, PID: 30739
    java.lang.RuntimeException: Unable to destroy activity {vitalypanov.phototracker/vitalypanov.phototracker.activity.StartScreenActivity}: java.util.ConcurrentModificationException
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4383)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4401)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6501)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
        at org.osmdroid.views.MapViewRepository.onDetach(MapViewRepository.java:37)
        at org.osmdroid.views.MapView.onDetach(MapView.java:1026)
        at org.osmdroid.views.MapView.onDetachedFromWindow(MapView.java:1212)
        at android.view.View.dispatchDetachedFromWindow(View.java:17502)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3701)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3693)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3693)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3693)
        at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5245)
        at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5216)
        at android.view.ViewGroup.removeView(ViewGroup.java:5147)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1550)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3260)
        at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:274)
        at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:419)
        at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:210)
        at android.app.Activity.performDestroy(Activity.java:7218)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1250)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4370)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4401) 
        at android.app.ActivityThread.-wrap5(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6501) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 

## Issue Type

[ ] Question
[ x] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
Occurred when closing activity (exiting from application) with MapView object

## Environment
Android 8.1

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.3

**Comment by monsieurtanuki** [comment]
> Caused by: java.util.ConcurrentModificationException
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
at org.osmdroid.views.MapViewRepository.onDetach(MapViewRepository.java:37)
at org.osmdroid.views.MapView.onDetach(MapView.java:1026)

Looks similar to #1223. It looks like `mapView.onDetach()` is called at an inappropriate time, in that case something like twice at the same time. Do you have several `MapView`s?

**Comment by panovvitalik** [comment]
> > Caused by: java.util.ConcurrentModificationException
> > at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
> > at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
> > at org.osmdroid.views.MapViewRepository.onDetach(MapViewRepository.java:37)
> > at org.osmdroid.views.MapView.onDetach(MapView.java:1026)
> 
> Looks similar to #1223. It looks like `mapView.onDetach()` is called at an inappropriate time, in that case something like twice at the same time. Do you have several `MapView`s?

- Are you serius? You see "detach" name function in stack trace and think it similar to other bug? I think it's other problem. In this stack trace no my app calling at all! Only osmdroid and system calls.
This bug reproduced on developer machine. It cause when I closing activity which contains MapView objects. 
Yes, I have several map views on several different activities in app.

**Comment by spyhunter99** [comment]
try using 6.1.0-SNAPSHOT
