### ISSUE TITLE
NPE: Attempt to invoke virtual method 'org.osmdroid.util.GeoPoint org.osmdroid.views.overlay.LinearRing.getCloseTo

### ISSUE THREAD

**Issue by pasniak** [osmdroid/osmdroid#1247]
I got the below stack while playing with my app and clicking furiously around the map.... nothing urgent.

## Issue Type

[ ] Question
[x] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

6.1.0-SNAPSHOT:debug@aar
c956fe1d923916d1c362994918e31b74c7d45174

java.lang.NullPointerException: Attempt to invoke virtual method 'org.osmdroid.util.GeoPoint org.osmdroid.views.overlay.LinearRing.getCloseTo(org.osmdroid.util.GeoPoint, double, org.osmdroid.views.Projection, boolean)' on a null object reference
at org.osmdroid.views.overlay.Polyline.getCloseTo(Polyline.java:195)
at org.osmdroid.views.overlay.Polyline.onSingleTapConfirmed(Polyline.java:227)
at org.osmdroid.views.overlay.DefaultOverlayManager.onSingleTapConfirmed(DefaultOverlayManager.java:265)
at org.osmdroid.views.overlay.FolderOverlay.onSingleTapConfirmed(FolderOverlay.java:85)
at org.osmdroid.views.overlay.DefaultOverlayManager.onSingleTapConfirmed(DefaultOverlayManager.java:265)
at org.osmdroid.views.MapView$MapViewDoubleClickListener.onSingleTapConfirmed(MapView.java:1564)
at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6694)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)

**Comment by spyhunter99** [comment]
unless there's more to the stack trace, (like a line number in linear ring) i think the only way this could happen is if one of the input parameters to getCloseTo was null. So a `Boolean` null was passed and cast to `boolean`.

**Comment by spyhunter99** [comment]
or perhaps mapview or projection or something else was null, strange

**Comment by monsieurtanuki** [comment]
@pasniak Couldn't it be that the `getCloseTo` method is called after an `onDetach`? (in that case, `private LinearRing mOutline = null;`)

If so:
1. I don't know how you managed to do this ;)
1. We could implement a safe "don't do anything after `onDetach`" fix

**Comment by pasniak** [comment]
Yes, I saw cases when my Activity was restarted (I think it started when I added Day/Night theme support and have not updated android:configChanges) then I got called from the system into osmdroid code: `
    public void onDetach(MapView mapView) {
        mOutline = null;
`
![capture](https://user-images.githubusercontent.com/19778666/51648049-111a0d00-1f77-11e9-9a97-ba334c34482d.PNG)

I added uiMode to android:configChanges and I think the "problem" is gone. It only reappears when I "Apply Changes" and Android Studio force-restarts my Activity... My GUI is not too complicated so I do not really want to deal with lifecycle "complications"...

**Comment by monsieurtanuki** [comment]
@pasniak What's the status then? Are you able to bypass this issue in your app?

Or do you think we'll be better off with a more decent attach/detach management?
For the moment, in `MapView` we override `ViewGroup.onDetachedToWindow`, without implementing `ViewGroup.onAttachedToWindow`. I assume the initial idea was to override a non-existing `View.onDestroy` method, without expecting the same `View` to be reattached later.
I don't think it would make sense to implement `ViewGroup.onAttachedToWindow`, as we don't really care about this event.

Perhaps the solution would be to let 99% of the osmdroid users work without any change, but for the 1% like you:
* add something like `MapView.setDestroyMode(int mode)`, with a default value (for the 99%) of "on detach", and a possible value of "explicit on destroy"
* create method `MapView.onDestroy` and move there the "destroy" code currently in `onDetachedToWindow`
* automatically call the new `MapView.onDestroy` method only when the `MapView` is on "on detach" mode, in `MapView.onDetachedToWindow` (99%)
* explicitly add a call to `MapView.onDestroy` when overriding your `Activity.onDestroy` (1%)

@pasniak Looks like a quick fix: do you think it will work in your case? Could you test that?

**Comment by monsieurtanuki** [comment]
@pasniak My point was that:
* it would be a pain in the neck to re-think and re-code all `MapView`, all `Overlay`s and maybe more with that `onAttachedToWindow` system, especially considering the legacy aspect
* the way I use osmdroid, it's an issue I never had
* an elegant way of fixing that is to say: "OK folks, you can keep your dev as is, no problem, but if you want a more robust version you only have to add `MapView.setDestroyMode(MapView.EXPLICIT_ON_DESTROY)` in `Fragment.onCreateView` and `MapView.onDestroy` in `Fragment.onDestroy`

That is, if my hypothesis is correct; what do the sages say? @spyhunter99 Is it fair to assume that the current implementation of `MapView.onDetachedFromWindow` is just an approximation of the nonexistent `View.onDestroy`, and that this approximation presumably causes the current issue?

**Comment by monsieurtanuki** [comment]
@pasniak I've just PR'ed #1274. Tell me if it works in your case.

**Comment by Saursinet** [comment]
Hey @monsieurtanuki, 
I was using osmdroid version 6.1.6 previously and didn't have the problem mentioned above.
I then upgraded the library a month and a half ago to version 6.1.10.
But ever since I did I received more than a thousand crashes with this stacktrace :

`Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'org.osmdroid.util.GeoPoint org.osmdroid.views.overlay.LinearRing.getCloseTo(org.osmdroid.util.GeoPoint, double, org.osmdroid.views.Projection, boolean)' on a null object reference
org.osmdroid.views.overlay.PolyOverlayWithIW.getCloseTo (PolyOverlayWithIW.java:596)
org.osmdroid.views.overlay.PolyOverlayWithIW.onSingleTapConfirmed (PolyOverlayWithIW.java:619)
org.osmdroid.views.overlay.DefaultOverlayManager.onSingleTapConfirmed (DefaultOverlayManager.java:306)
org.osmdroid.views.MapView$MapViewDoubleClickListener.onSingleTapConfirmed (MapView.java:1605)
android.view.GestureDetector$GestureHandler.handleMessage (GestureDetector.java:345)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1075)` 

I did apply the suggested 

> add MapView.setDestroyMode(false) in Fragment.onCreateView and MapView.onDestroy in Fragment.onDestroy

But this doesn't seem to fix this crash.
By testing manually, I cannot seem to reproduce it while the app being in foreground. But I still do see on Crashlytics that my phone is registered as having received the crash. So I believe it has to be when the app is in the background.

Did anything change in the latests releases that could have affected the fix provided? Or would you have any idea on why I could have it?
Also if you have any lead to investigate it further they would be welcome!

Thanks

**Comment by monsieurtanuki** [comment]
Hi @Saursinet!
Perhaps in background but still a bit active: `MapView$MapViewDoubleClickListener.onSingleTapConfirmed`.
I don't know if you can remove the click listener when the app is in background.
The ideal case would be for you to be able to reproduce the bug, anyway...

**Comment by Saursinet** [comment]
Alright I'll investigate a bit more then and will test further to try to reproduce it.
Thanks for the answer!
