### ISSUE TITLE
More Samples > Cache > Cache Manager crashes

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#1297]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Bug

## Description and/or steps/code to reproduce the problem
```  Process: org.osmdroid, PID: 13403
    org.osmdroid.tileprovider.tilesource.TileSourcePolicyException: This online tile source doesn't support bulk download
        at org.osmdroid.tileprovider.cachemanager.CacheManager.<init>(CacheManager.java:107)
        at org.osmdroid.tileprovider.cachemanager.CacheManager.<init>(CacheManager.java:91)
        at org.osmdroid.tileprovider.cachemanager.CacheManager.<init>(CacheManager.java:80)
        at org.osmdroid.tileprovider.cachemanager.CacheManager.<init>(CacheManager.java:76)
        at org.osmdroid.samplefragments.cache.SampleCacheDownloader.onCreateView(SampleCacheDownloader.java:60)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2354)
```
looks like this is related to the latest changes for prevent tool many concurrent tile downloads

### Version of osmdroid the issue relates to:

head

**Comment by monsieurtanuki** [comment]
Actually that's how it's meant to work: from #1289 the bulk download of "MAPNIK" is forbidden, as requested by OSM admins.

Back to the current issue:
* definitely we should select another tile source for this CacheManager demo
* perhaps we could implement a "lazy bulk" download mode, something like waiting a second between each tile download, in order to smoothen the accesses to the tile servers, which would make the load more acceptable for them
* perhaps I overreacted from what OSM admins said - forbid bulk downloads on "MAPNIK" _just_ for the default "osmdroid" agent

**Comment by spyhunter99** [comment]
default is now usgs sat for those demos

**Comment by spyhunter99** [comment]
default is now usgs sat for those demos
