### ISSUE TITLE
Keep getting NPE while instantiating MapsForgeTileProver while trying to rendering a simple map-File

### ISSUE THREAD

**Issue by FalcoSuessgott** [osmdroid/osmdroid#1330]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[X ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
I downloaded a map-file from mapsforge-Server (v4) (http://ftp-stud.hs-esslingen.de/pub/Mirrors/download.mapsforge.org/maps/v4/).
I also had to copy the assets/renderthemes folder into my src-dir, since I got a FileNotFoundException while declaring `XmlRenderTheme theme`.

I want to render this file, with mapsforge with the following code:

```
map = (MapView) findViewById(R.id.map);
        Set<File> mapfiles = findMapFiles();
        File[] maps = new File[mapfiles.size()];
        maps = mapfiles.toArray(maps);

        for (File f : maps){
            Log.i(TAG, "File: " + f.getPath().toString());
        }
        if (maps.length == 0) Log.d(TAG, "No Mapsforge files found");
        else {
            Toast.makeText(this, "Loaded " + maps.length + " map files",
            Toast.LENGTH_LONG).show();
        }

        XmlRenderTheme theme = null;

        try {
            theme = new AssetsRenderTheme(getApplicationContext(),"renderthemes/", "rendertheme-v4.xml");
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        MapsForgeTileProvider forge = new MapsForgeTileProvider(
                new SimpleRegisterReceiver(this),
                MapsForgeTileSource.createFromFiles(maps, theme, "rendertheme-v4"),
                null);

        map.setTileProvider(forge);
        map.setUseDataConnection(false);
        map.setMultiTouchControls(true);
        map.setBuiltInZoomControls(true);
```

Im receiving the following error message:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.htwBerlin.ois/de.htwBerlin.ois.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.osmdroid.views.MapView.setTileProvider(org.osmdroid.tileprovider.MapTileProviderBase)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.osmdroid.views.MapView.setTileProvider(org.osmdroid.tileprovider.MapTileProviderBase)' on a null object reference
        at de.htwBerlin.ois.MainActivity.onCreate(MainActivity.java:119)
        at android.app.Activity.performCreate(Activity.java:6679)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

## Environment
```
    // OSM Mapsforge
    implementation 'org.osmdroid:osmdroid-android:6.1.0'
    implementation 'org.osmdroid:osmdroid-mapsforge:6.0.1@aar'

    // Mapsforge
    implementation 'org.mapsforge:mapsforge-core:0.11.0'
    implementation 'org.mapsforge:mapsforge-map:0.11.0'
    implementation 'org.mapsforge:mapsforge-map-reader:0.11.0'
    implementation 'org.mapsforge:mapsforge-themes:0.11.0'
    implementation 'net.sf.kxml:kxml2:2.3.0'
    implementation 'org.mapsforge:mapsforge-map-android:0.11.0'
    implementation 'com.caverock:androidsvg:1.3'
```

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.1

**Comment by spyhunter99** [comment]
use the older version of mapsforge. There are several open issues with the forge adapter

**Comment by FalcoSuessgott** [comment]
Okay, found the problem.
`map = (MapView) findViewById(R.id.map);`
was never actually initialized by this, because it is a Mapview in a LinearLayout. As I specfied a simple MapView in a Constraint layout, map is initialized by 

`map = (MapView) findViewById(R.id.map);`
