### ISSUE TITLE
n must be positive\ Out of memory

### ISSUE THREAD

**Issue by WhiskyCat** [osmdroid/osmdroid#1331]
## Issue Type

[x ] Question
[x ] Bug

## Description and/or steps/code to reproduce the problem
When scrolling outside the offline tiles and Internet is turned on I receive the "java.lang.IllegalArgumentException: n must be positive" exception and the app crashes.

 If I don't scroll to the edge of the offline tiles, just scrolling and zooming a bit, I receive the "E/art: Out of memory: Heap Size=192MB, Allocated=191MB, Capacity=192MB" problem after about 10 Seconds.
The offline tiles are displayed correctly until the out of memory problem occurs, then the tiles aren't displayed any more.
The tiles are inside the assets Folder. assets/MAPNIK/ZoomLevel/Number/number.png and have a resolution of 256x256.

As help for the implementation I used: https://github.com/osmdroid/osmdroid/wiki/Offline-Map-Tiles

Did I miss anything essential inside my implementation in order to use offline tiles?

**MapClass:**
The permissions are obtained inside a previous activity
`
MapView map = null;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        setContentView(R.layout.maplayout);
        //load/initialize the osmdroid configuration, this can be done
        Context ctx = getApplicationContext();
        Configuration.getInstance().load(ctx, PreferenceManager.getDefaultSharedPreferences(ctx));

        map = findViewById(R.id.map);
        map.setUseDataConnection(false);
        map.setTileSource(new XYTileSource(
                "MAPNIK",
                17,
                19,
                265,
                ".png", new String[]{}
        ));

        map.setBuiltInZoomControls(true);
        map.setMultiTouchControls(true);
        final IMapController mapController = map.getController();
        mapController.setZoom(18);
        GeoPoint startPoint = new GeoPoint(startPointsLa, startPointLo);
        mapController.setCenter(startPoint);
        // Method where markes are created and placed. More markers evoke
        //the out of memmory problem faster.
        makeMarker();
        map.setScrollableAreaLimitDouble(new BoundingBox(boundingNorth, boundingEast, boundingSouth, boundingWest));
        map.setMinZoomLevel(17.0);
        map.setMaxZoomLevel(19.0);

        map.getTileProvider().getTileCache().setAutoEnsureCapacity(false);
        map.getTileProvider().getTileCache().setStressedMemory(true);
        map.getTileProvider().clearTileCache();
        map.invalidate();
    }`

**Dependencies:**
`implementation 'org.osmdroid:osmdroid-android:6.1.0'
    implementation 'org.osmdroid:osmdroid-wms:6.1.0'
    implementation 'org.osmdroid:osmdroid-mapsforge:6.1.0'
    implementation 'org.osmdroid:osmdroid-geopackage:6.1.0'
    implementation group: 'org.osmdroid', name: 'osmdroid-packager', version: '4.2'`

**Exceptions:**
`java.lang.IllegalArgumentException: n must be positive
        at java.util.Random.nextInt(Random.java:391)
        at org.osmdroid.tileprovider.tilesource.OnlineTileSourceBase.getBaseUrl(OnlineTileSourceBase.java:67)
        at org.osmdroid.tileprovider.tilesource.XYTileSource.getTileURLString(XYTileSource.java:42)
        at org.osmdroid.tileprovider.modules.MapTileDownloader$TileLoader.loadTile(MapTileDownloader.java:223)
        at org.osmdroid.tileprovider.MapTilePreCache.search(MapTilePreCache.java:125)
        at org.osmdroid.tileprovider.MapTilePreCache.access$100(MapTilePreCache.java:30)
        at org.osmdroid.tileprovider.MapTilePreCache$1.run(MapTilePreCache.java:41)
        at org.osmdroid.util.GarbageCollector$1.run(GarbageCollector.java:31)
        at java.lang.Thread.run(Thread.java:761)
Application terminated.`

`E/art: Out of memory: Heap Size=192MB, Allocated=191MB, Capacity=192MB
W/art: Throwing OutOfMemoryError "Failed to allocate a 262156 byte allocation with 141288 free bytes and 137KB until OOM"
I/art: WaitForGcToComplete blocked for 728.452ms for cause Alloc
    Starting a blocking GC Alloc
E/OsmDroid: OutOfMemoryError loading bitmap
I/art: WaitForGcToComplete blocked for 69.592ms for cause Alloc
    Starting a blocking GC Alloc
I/art: Waiting for a blocking GC Alloc
I/art: Clamp target GC heap from 207MB to 192MB
    Alloc concurrent mark sweep GC freed 71(5KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 799us total 32.826ms`

### If it's a bug, version(s) of android this affects:

Android 7.0

### Version of osmdroid the issue relates to:

6.1.0

**Comment by spyhunter99** [comment]
the root cause is the oom issue. i think there was a related issue now too long ago.
https://github.com/osmdroid/osmdroid/issues/1328 and https://github.com/osmdroid/osmdroid/issues/1325
