### ISSUE TITLE
Bing Maps fatal error

### ISSUE THREAD

**Issue by ryanbehr** [osmdroid/osmdroid#1373]
## Issue Type

[ ] Question
[X] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
Use Bing Maps Hybrid as a tile source. (with the same environment below)

The Issue is an NPE at https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/bing/BingMapTileSource.java#L124

I believe the mUrl is null which is throwing the exception. This ends up crashing the app with this stack trace:

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
       at java.util.Formatter.parse + 2545(Formatter.java:2545)
       at java.util.Formatter.format + 2504(Formatter.java:2504)
       at java.util.Formatter.format + 2458(Formatter.java:2458)
       at java.lang.String.format + 2770(String.java:2770)
       at org.osmdroid.tileprovider.tilesource.bing.BingMapTileSource.getTileURLString + 124(BingMapTileSource.java:124)
       at org.osmdroid.tileprovider.modules.MapTileDownloader$TileLoader.loadTile + 223(MapTileDownloader.java:223)
       at org.osmdroid.tileprovider.MapTilePreCache.search + 125(MapTilePreCache.java:125)
       at org.osmdroid.tileprovider.MapTilePreCache.access$000 + 30(MapTilePreCache.java:30)
       at org.osmdroid.tileprovider.MapTilePreCache$1.run + 41(MapTilePreCache.java:41)
       at org.osmdroid.util.GarbageCollector$1.run + 31(GarbageCollector.java:31)
       at java.lang.Thread.run + 784(Thread.java:784)

## Environment
Work in an area with bad internet or no internet

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.0

**Comment by spyhunter99** [comment]
i can add additional checks...i bet microsoft changed the api

**Comment by spyhunter99** [comment]
did you see any other related logs?

**Comment by spyhunter99** [comment]
actually i am able to reproduce... the org.json.JSONObject is returning null when parsing the result. not sure why

**Comment by mat8854** [comment]
Hello, on which Android API level are you running (Pie or higher?). This exception is related to Android itself.

Check your LogCat also for this:
... `E/OsmDroid: Error getting imagery meta data java.io.IOException: Cleartext HTTP traffic to dev.virtualearth.net not permitted` ...

Under Android Pie and above cleartext HTTP traffic is not permitted by default:
https://developer.android.com/training/articles/security-config

Add a network_security_config.xml with this content:
`<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">dev.virtualearth.net</domain>
        <domain includeSubdomains="true">ecn.t0.tiles.virtualearth.net</domain>
    </domain-config>
</network-security-config>`

Not sure if these are already all domains.

**Comment by mat8854** [comment]
There is a runtime check available for testing certain domains: https://developer.android.com/reference/android/security/NetworkSecurityPolicy.html#isCleartextTrafficPermitted()

**Comment by ryanbehr** [comment]
Hey, sorry for the late reply here - for some odd reason I didn't get any notifications until this morning.

No other logs there, and this isn't related to cleartext HTTP traffic - it works if we are online, just an issue if we are offline. This affects all versions of android. (we test from android 4 to android 9).

I guess the easy fix is just a null pointer check - but I think if the user actually goes online it won't pull in the map because mUrl isn't set due to the mImageryData.m_imageUrl being null on line 304. Maybe there should be a check to see if we resolved the ImageryMetaData yet or not?

**Comment by mat8854** [comment]
I see: yours is a different error.

By the way: Google suggests 3rd party libs should honor this network flag / policy.

**Comment by spyhunter99** [comment]
even with the json response as a hard coded string literal, anroids json parser is barfing on it. its like the org.json.parser suddenly no longer work at all....

**Comment by spyhunter99** [comment]
what if we changed that one line to this...

```
if(mUrl!=null)
            return String.format(mUrl, quadTree(pMapTileIndex));
        return String.format("https://localhost/", quadTree(pMapTileIndex));
```

**Comment by amoizard** [comment]
Thanks / I would like to try this, but I'm just using osmdroid in gradle and have no experience in making a modification to a third party dependency.

NOTE: I'm using 6.1.13 now and still see the error in reports.

**Comment by WangHan2014** [comment]
The same issue.Using BingMap when connect to the wifi whit out internet connection.
I dev a app which control the uav.when connect to the uav's wifi,there is no network can get  the map,and it will cause this issue.

Hope to  fix it in next version.

Here is the logcat:

FATAL EXCEPTION: GarbageCollector
                                                                                                    Process: cn.ef.uav.mp, PID: 15215
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                                                                    	at java.util.Formatter.parse(Formatter.java:2546)
                                                                                                    	at java.util.Formatter.format(Formatter.java:2505)
                                                                                                    	at java.util.Formatter.format(Formatter.java:2459)
                                                                                                    	at java.lang.String.format(String.java:2870)
                                                                                                    	at org.osmdroid.tileprovider.tilesource.bing.BingMapTileSource.getTileURLString(BingMapTileSource.java:124)
                                                                                                    	at org.osmdroid.tileprovider.modules.MapTileDownloader$TileLoader.loadTile(MapTileDownloader.java:188)
                                                                                                    	at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.loadTileIfReachable(MapTileModuleProviderBase.java:213)
                                                                                                    	at org.osmdroid.tileprovider.MapTilePreCache.search(MapTilePreCache.java:127)
                                                                                                    	at org.osmdroid.tileprovider.MapTilePreCache.access$100(MapTilePreCache.java:31)
                                                                                                    	at org.osmdroid.tileprovider.MapTilePreCache$1.run(MapTilePreCache.java:42)
                                                                                                    	at org.osmdroid.util.GarbageCollector$1.run(GarbageCollector.java:32)
                                                                                                    	at java.lang.Thread.run(Thread.java:929)
2023-09-05 09:33:52.953 15215-15372 OsmDroid                cn.ef.uav.mp                         E  Error getting imagery meta data
