### ISSUE TITLE
app crashes with OnlineTileSourceBase.getBaseUrl causing a IllegalArgumentException: bound must be positive

### ISSUE THREAD

**Issue by deltacharlie1** [osmdroid/osmdroid#1379]
## Issue Type

[x ] Question
[x ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
I'm using offline maps (from 4uMaps) of an area encompassing the UK at zoom levels 3 - 13.

            map.setTileSource(new XYTileSource("4uMaps", 0, 18, 256, ".jpg", new String[]{}));

  When I move outside of an area covered by an existing tile I get the following logcat errors:-

`    java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:388)
        at org.osmdroid.tileprovider.tilesource.OnlineTileSourceBase.getBaseUrl(OnlineTileSourceBase.java:67)
        at org.osmdroid.tileprovider.tilesource.XYTileSource.getTileURLString(XYTileSource.java:42)
        at org.osmdroid.tileprovider.modules.MapTileDownloader$TileLoader.loadTile(MapTileDownloader.java:223)
        at org.osmdroid.tileprovider.MapTilePreCache.search(MapTilePreCache.java:125)
        at org.osmdroid.tileprovider.MapTilePreCache.access$100(MapTilePreCache.java:30)
        at org.osmdroid.tileprovider.MapTilePreCache$1.run(MapTilePreCache.java:41)
        at org.osmdroid.util.GarbageCollector$1.run(GarbageCollector.java:31)
        at java.lang.Thread.run(Thread.java:764)
`
How can I resolve this (other than by not going beyond existing tile coverage.  Or is that they only way)?

### If it's a bug, version(s) of android this affects:

Android 8 - sdk 28

### Version of osmdroid the issue relates to:

6.1.0

**Comment by spyhunter99** [comment]
change `new String[]{}` to `new String[]{""}`

**Comment by deltacharlie1** [comment]
Amazingly quick response!! - Many thanks, that has done the trick.  Can I suggest that you change the relevant code in https://github.com/osmdroid/osmdroid/wiki/Offline-Map-Tiles to show this.

**Comment by spyhunter99** [comment]
no problem. right place right time. wiki updated
