### ISSUE TITLE
mbtiles map crash TransactionTooLarge

### ISSUE THREAD

**Issue by TFreudi1** [osmdroid/osmdroid#1381]
I have a app with osmdroid completly based on offline mbtiles. Especially on tablets (different android versions) but als on mobiles I got often crash's. I will build a sample project based on your simple map project, but sometime it is hard to track, sometimes it happens with the first tap on zoom-out (-). Until I finish sample maybe somebody have a hint for that problem. I tried osmdroid 6.1.0 and 6.1.1-SNAPSHOT, it happens on both. Here is the log, it looks like "animateTo" is called very often but I did'nt do it in my source, I simple tap on the internal zoom controls :

08-13 09:49:42.971 3728-3728/com.pg.poliksgraf E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pg.poliksgraf, PID: 3728
    java.lang.StackOverflowError: stack size 8MB
        at org.osmdroid.views.Projection.<init>(Projection.java:45)
        at org.osmdroid.views.Projection.<init>(Projection.java:65)
        at org.osmdroid.views.MapView.getProjection(MapView.java:358)
        at org.osmdroid.views.MapView.setExpectedCenter(MapView.java:1809)
        at org.osmdroid.views.MapView.setExpectedCenter(MapView.java:1823)
        at org.osmdroid.views.MapView.setZoomLevel(MapView.java:480)
        at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
        at android.animation.ValueAnimator.end(ValueAnimator.java:1155)
        at org.osmdroid.views.MapController.animateTo(MapController.java:167)
        at org.osmdroid.views.MapController.animateTo(MapController.java:137)
        at org.osmdroid.views.MapController.animateTo(MapController.java:183)
        at org.osmdroid.views.MapController.animateTo(MapController.java:129)
        at org.osmdroid.views.MapView.setZoomLevel(MapView.java:492)
        at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
        at android.animation.ValueAnimator.end(ValueAnimator.java:1155)
        at org.osmdroid.views.MapController.animateTo(MapController.java:167)
        at org.osmdroid.views.MapController.animateTo(MapController.java:137)
        at org.osmdroid.views.MapController.animateTo(MapController.java:183)
        at org.osmdroid.views.MapController.animateTo(MapController.java:129)
        at org.osmdroid.views.MapView.setZoomLevel(MapView.java:492)
        at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
        at android.animation.ValueAnimator.end(ValueAnimator.java:1155)
        at org.osmdroid.views.MapController.animateTo(MapController.java:167)
        at org.osmdroid.views.MapController.animateTo(MapController.java:137)
        at org.osmdroid.views.MapController.animateTo(MapController.java:183)
        at org.osmdroid.views.MapController.animateTo(MapController.java:129)
        at org.osmdroid.views.MapView.setZoomLevel(MapView.java:492)
        at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
        at android.animation.ValueAnimator.end(ValueAnimator.java:1155)
        at org.osmdroid.views.MapController.animateTo(MapController.java:167)
        at org.osmdroid.views.MapController.animateTo(MapController.java:137)
        at org.osmdroid.views.MapController.animateTo(MapController.java:183)
        at org.osmdroid.views.MapController.animateTo(MapController.java:129)
        at org.osmdroid.views.MapView.setZoomLevel(MapView.java:492)
        at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
        at android.animation.ValueAnimator.end(ValueAnimator.java:1155)
        at org.osmdroid.views.MapController.animateTo(MapController.java:167)
        at org.osmdroid.views.MapController.animateTo(MapController.java:137)
        at org.osmdroid.views.MapController.animateTo(MapController.java:183)
        at org.osmdroid.views.MapController.animateTo(MapController.java:129)
        at org.osmdroid.views.MapView.setZoomLevel(MapView.java:492)
        at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
        at android.animation.ValueAnimator.end(ValueAnimator.java:1155)
        at org.osmdroid.views.MapController.animateTo(MapController.java:167)
        at org.osmdroid.views.MapController.animateTo(MapController.java:137)
        at org.osmdroid.views.MapController.animateTo(MapController.java:183)
        at org.osmdroid.views.MapController.animateTo(MapController.java:129)
        at org.osmdroid.views.MapView.setZoomLevel(MapView.java:492)
    	at org.osmdroid.views.MapController$MapAnimatorListener.onAnimatio
08-13 09:49:43.174 3728-3728/com.pg.poliksgraf I/art: Waiting for a blocking GC Alloc
08-13 09:49:43.210 3728-3737/com.pg.poliksgraf I/art: Background partial concurrent mark sweep GC freed 256637(31MB) AllocSpace objects, 9(83MB) LOS objects, 6% free, 58MB/62MB, paused 401us total 180.863ms
08-13 09:49:43.210 3728-3728/com.pg.poliksgraf I/art: WaitForGcToComplete blocked for 35.847ms for cause Alloc
08-13 09:49:43.210 3728-3728/com.pg.poliksgraf I/art: Starting a blocking GC Alloc
08-13 09:49:43.245 3728-3728/com.pg.poliksgraf D/Error: ERR: exClass=java.lang.StackOverflowError
08-13 09:49:43.246 3728-3728/com.pg.poliksgraf D/Error: ERR: exMsg=stack size 8MB
08-13 09:49:43.246 3728-3728/com.pg.poliksgraf D/Error: ERR: file=Projection.java
08-13 09:49:43.246 3728-3728/com.pg.poliksgraf D/Error: ERR: class=org.osmdroid.views.Projection
08-13 09:49:43.246 3728-3728/com.pg.poliksgraf D/Error: ERR: method=<init> line=45
08-13 09:49:43.281 3728-3728/? D/Error: ERR: stack=java.lang.StackOverflowError: stack size 8MB
        at org.osmdroid.views.Projection.<init>(Projection.java:45)
        at org.osmdroid.views.Projection.<init>(Projection.java:65)
        at org.osmdroid.views.MapView.getProjection(MapView.java:358)
        at org.osmdroid.views.MapView.setExpectedCenter(MapView.java:1809)
        at org.osmdroid.views.MapView.setExpectedCenter(MapView.java:1823)
        at org.osmdroid.views.MapView.setZoomLevel(MapView.java:480)
        at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
        at android.animation.ValueAnimator.end(ValueAnimator.java:1155)
        at org.osmdroid.views.MapController.animateTo(MapController.java:167)
        at org.osmdroid.views.MapController.animateTo(MapController.java:137)
        at org.osmdroid.views.MapController.animateTo(MapController.java:183)
        at org.osmdroid.views.MapController.animateTo(MapController.java:129)
        at org.osmdroid.views.MapView.setZoomLevel(MapView.java:492)
        at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
        at android.animation.ValueAnimator.end(ValueAnimator.java:1155)
        at org.osmdroid.views.MapController.animateTo(MapController.java:167)
        at org.osmdroid.views.MapController.animateTo(MapController.java:137)
        at org.osmdroid.views.MapController.animateTo(MapController.java:183)
        at org.osmdroid.views.MapController.animateTo(MapController.java:129)
        at org.osmdroid.views.MapView.setZoomLevel(MapView.java:492)
        at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
        at android.animation.ValueAnimator.end(ValueAnimator.java:1155)
        at org.osmdroid.views.MapController.animateTo(MapController.java:167)
        at org.osmdroid.views.MapController.animateTo(MapController.java:137)
        at org.osmdroid.views.MapController.animateTo(MapController.java:183)
        at org.osmdroid.views.MapController.animateTo(MapController.java:129)
        at org.osmdroid.views.MapView.setZoomLevel(MapView.java:492)
        at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
        at android.animation.ValueAnimator.end(ValueAnimator.java:1155)
        at org.osmdroid.views.MapController.animateTo(MapController.java:167)
        at org.osmdroid.views.MapController.animateTo(MapController.java:137)
        at org.osmdroid.views.MapController.animateTo(MapController.java:183)
        at org.osmdroid.views.MapController.animateTo(MapController.java:129)
        at org.osmdroid.views.MapView.setZoomLevel(MapView.java:492)
        at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
        at android.animation.ValueAnimator.end(ValueAnimator.java:1155)
        at org.osmdroid.views.MapController.animateTo(MapController.java:167)
        at org.osmdroid.views.MapController.animateTo(MapController.java:137)
        at org.osmdroid.views.MapController.animateTo(MapController.java:183)
        at org.osmdroid.views.MapController.animateTo(MapController.java:129)
        at org.osmdroid.views.MapView.setZoomLevel(MapView.java:492)
        at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
        at android.animation.ValueAnimator.end(ValueAnimator.java:1155)
        at org.osmdroid.views.MapController.animateTo(MapController.java:167)
        at org.osmdroid.views.MapController.animateTo(MapController.java:137)
        at org.osmdroid.views.MapController.animateTo(MapController.java:183)
        at org.osmdroid.views.MapController.animateTo(MapController.java:129)
        at org.osmdroid.views.MapView.setZoomLevel(MapView.java:492)
        at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
    	at android.animation.Valu
08-13 09:49:43.281 3728-3728/? D/Error: ERR: TOTAL BYTES WRITTEN: 16510424
08-13 09:49:43.284 3728-3728/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 16510508)
08-13 09:49:43.284 3728-3728/? E/AndroidRuntime: Error reporting crash
    android.os.TransactionTooLargeException: data parcel size 16510508 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:503)
        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4425)
        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
08-13 09:49:43.284 3728-3728/? I/Process: Sending signal. PID: 3728 SIG: 9

**Comment by monsieurtanuki** [comment]
Nice bug! I'll have a look at it.

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by TFreudi1** [comment]
Well ok, I wil have a test project for you and an video, nothing with mbtiles, my current guess is that it has something to do with myLocation... As I say it happens much more on tablets as on mobiles. I took the actual androidstudio 3.4.2 and build a tablet emulator with a 10,1" Tablet and Android 23.

**Comment by TFreudi1** [comment]
The Projekt :
[OsmdroidCrash.zip](https://github.com/osmdroid/osmdroid/files/3496633/OsmdroidCrash.zip)

**Comment by TFreudi1** [comment]
The video:
[https://1drv.ms/v/s!At-t2qCm4ADnuDT9pzz9lvxcwI6y?e=ZLBNxb](url)

**Comment by TFreudi1** [comment]
After the first run you must give the app the permission for GPS/storage manually, to make it simpler I did'nt inlcude code for that.

**Comment by TFreudi1** [comment]
This is the code left out after some trys, with that you just have to tap minus zoomcontrol shortly after the app starts and it crash:
`public class MainActivity extends AppCompatActivity {

    MapView mapView=null;

    // Extensions to simple map version
    MyLocationNewOverlay mLocationOverlay = null;
    static Handler UIhandler = new Handler(); // Handler fuer Update in UI Thread

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Configuration.getInstance().load(getApplicationContext(), PreferenceManager.getDefaultSharedPreferences(getApplicationContext()));
        setContentView(R.layout.activity_main);
        mapView = (MapView) findViewById(R.id.mapView);
      
        mLocationOverlay = new MyLocationNewOverlay(mapView);
        mapView.getOverlays().add(mLocationOverlay);

        mLocationOverlay.runOnFirstFix(new Runnable() {
            public void run() {
                UIhandler.post(new Runnable() {
                    @Override
                    public void run() {
                        mapView.getController().animateTo(mLocationOverlay.getMyLocation(), 15.0, 100L);
                    }
                });
            }
        });

    }
    @Override
    public void onResume(){
        super.onResume();
        Configuration.getInstance().load(getApplicationContext(), PreferenceManager.getDefaultSharedPreferences(getApplicationContext()));
        if (mapView!=null)
            mapView.onResume();
    }

    @Override
    public void onPause(){
        super.onPause();
        Configuration.getInstance().save(getApplicationContext(), PreferenceManager.getDefaultSharedPreferences(getApplicationContext()));
        if (mapView!=null)
            mapView.onPause();
    }
}
`

**Comment by monsieurtanuki** [comment]
Sounds familiar. I have currently a very limited access to internet, but I'm almost certain this bug has been solved in a recent (but probably not merged yet) PR.

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by TFreudi1** [comment]
Some more results ... it don't happen with 6.0.1/2/3
It is much easier to reproduce with the runOnFirstFix - code, with that the first tap on '-' crash. But I have the same crash without runOnFirstFix but it is muuuuch harder to reproduce.

**Comment by monsieurtanuki** [comment]
@TFreudi1 Could you try again with the latest release (something like 6.1.2)?

**Comment by TFreudi1** [comment]
I'm just on holiday but will try it upcoming weekend. Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: monsieurtanuki <notifications@github.com> Datum: 09.10.19  14:10  (GMT+00:00) An: osmdroid/osmdroid <osmdroid@noreply.github.com> Cc: TFreudi1 <TFreudi1@gmx.de>, Mention <mention@noreply.github.com> Betreff: Re: [osmdroid/osmdroid] mbtiles map crash TransactionTooLarge (#1381) @TFreudi1 Could you try again with the latest release (something like 6.1.2)?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/osmdroid/osmdroid/issues/1381?email_source=notifications\u0026email_token=ABEFA2N6QTKLJVA35CH77MLQNXJ4FA5CNFSM4ILIDOZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAX2MQY#issuecomment-539993667",
"url": "https://github.com/osmdroid/osmdroid/issues/1381?email_source=notifications\u0026email_token=ABEFA2N6QTKLJVA35CH77MLQNXJ4FA5CNFSM4ILIDOZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAX2MQY#issuecomment-539993667",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by TFreudi1** [comment]
Back from Holiday, let me test this next week with some different devices before finally close it, but it looks like it is gone, on the problematic tablet I cant reproduce it anymore.

**Comment by TFreudi1** [comment]
I can't reproduce it anymore, Looks good thanks
