### ISSUE TITLE
Unable to add back overlays after screen rotation

### ISSUE THREAD

**Issue by deltacharlie1** [osmdroid/osmdroid#1392]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[x ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
I can construct a route and add markers (one of which is a `MarkerWithLabel`) without any problem.  However, when I rotate the screen everything is lost as it seems `onCreate()` is being called which instantiates a new map object.  I therefore save the map centre, zoom level and existing overlays in the `onPause()` method and attempt to add them back in the `onResume()` method.  The map at the correct zoom level and centre is displayed but not the overlays.  If I add just the `MarkerWithLabel `marker then the (painted) text is displayed correctly but the marker icon is not.

My `onPause()/onResume()` code is:-

```
    public void onResume(){
        super.onResume();
        Log.e("OSMCH","--  onResume");
        if (paused) {
            mapController.setCenter(saveCentre);
            mapController.setZoom(saveZoom);
            map.getOverlays().addAll(mapOverlays);
            map.invalidate();

        }
        paused = false;
        map.onResume(); //needed for compass, my location overlays, v6.0.0 and up
    }
    public void onPause(){
        super.onPause();
        paused = true;
        Log.e("OSMCH","--  onPause ");
        saveCentre = (GeoPoint)map.getMapCenter();
        saveZoom = map.getZoomLevelDouble();
        mapOverlays.addAll(map.getOverlays());
        map.onPause();  //needed for compass, my location overlays, v6.0.0 and up
    }

```
The logcat messages generated  at some point, I think at the conclusion of the `onResume()` call is (although this does not generate an app error message):-

```
2019-09-01 15:57:36.600 16194-16194/com.corunna.osm E/OsmDroid: error dispatchDraw, probably in edit mode
    java.lang.NullPointerException: Attempt to invoke virtual method 'void org.osmdroid.views.overlay.LinearRing.setClipArea(org.osmdroid.views.Projection)' on a null object reference
        at org.osmdroid.views.overlay.Polyline.draw(Polyline.java:150)
        at org.osmdroid.views.overlay.Overlay.draw(Overlay.java:141)
        at org.osmdroid.views.overlay.DefaultOverlayManager.onDrawHelper(DefaultOverlayManager.java:178)
        at org.osmdroid.views.overlay.DefaultOverlayManager.onDraw(DefaultOverlayManager.java:138)
        at org.osmdroid.views.MapView.onDraw(MapView.java:1223)
        at android.view.View.draw(View.java:20373)
        at android.view.View.updateDisplayListIfDirty(View.java:19318)
        at android.view.View.draw(View.java:20096)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
        at android.view.View.updateDisplayListIfDirty(View.java:19309)
        at android.view.View.draw(View.java:20096)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
        at android.view.View.draw(View.java:20376)
        at android.view.View.updateDisplayListIfDirty(View.java:19318)
        at android.view.View.draw(View.java:20096)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
        at android.view.View.updateDisplayListIfDirty(View.java:19309)
        at android.view.View.draw(View.java:20096)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
        at android.view.View.updateDisplayListIfDirty(View.java:19309)
        at android.view.View.draw(View.java:20096)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
        at android.view.View.updateDisplayListIfDirty(View.java:19309)
        at android.view.View.draw(View.java:20096)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
        at android.view.View.draw(View.java:20376)
        at com.android.internal.policy.DecorView.draw(DecorView.java:980)
        at android.view.View.updateDisplayListIfDirty(View.java:19318)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:800)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3496)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3283)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2818)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1780)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7827)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
2019-09-01 15:57:36.700 16194-16194/com.corunna.osm E/OsmDroid: error dispatchDraw, probably in edit mode
    java.lang.NullPointerException: Attempt to invoke virtual method 'void org.osmdroid.views.overlay.LinearRing.setClipArea(org.osmdroid.views.Projection)' on a null object reference
        at org.osmdroid.views.overlay.Polyline.draw(Polyline.java:150)
        at org.osmdroid.views.overlay.Overlay.draw(Overlay.java:141)
        at org.osmdroid.views.overlay.DefaultOverlayManager.onDrawHelper(DefaultOverlayManager.java:178)
        at org.osmdroid.views.overlay.DefaultOverlayManager.onDraw(DefaultOverlayManager.java:138)
        at org.osmdroid.views.MapView.onDraw(MapView.java:1223)
        at android.view.View.draw(View.java:20373)
        at android.view.View.updateDisplayListIfDirty(View.java:19318)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
        at android.view.View.updateDisplayListIfDirty(View.java:19277)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
        at android.view.View.updateDisplayListIfDirty(View.java:19277)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
        at android.view.View.updateDisplayListIfDirty(View.java:19277)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
        at android.view.View.updateDisplayListIfDirty(View.java:19277)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
        at android.view.View.updateDisplayListIfDirty(View.java:19277)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
        at android.view.View.updateDisplayListIfDirty(View.java:19277)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:800)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3496)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3283)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2818)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1780)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7827)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
I'm not sure whether this is a bug or not so my question is - how should I be recreating map overlays when the screen is rotated?

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.0

**Comment by deltacharlie1** [comment]
Hi,  Thank you for your reply and suggestion.  I now store all relevant route data (polylines and markers) in preferences as a single string (currentRoute) which is then used to reconstruct the route (which is how the routes are initially constructed).  This all now works fine except for one bit which is the `boundingBox` where I get an error saying North is out of bounds when it is manifestly not.  I have tried the same code in both `onResume()` and `onCreate(0` with exactly the same error.

My (relevant) code is:-

```
    public void onResume(){
        super.onResume();
        Log.e("OSMCH","--  onResume");
        if (paused) {
            currentRoute = preferences.getString("currentRoute","");
            source = preferences.getBoolean("source",false);
            clearRouteVariables(7);
            buildRoute(currentRoute,source);
            displayRoutes();
            if (markers.size() > 0) {
                BoundingBox b = getBoundingBox(markers.get(0).getPosition(), markers.get(markers.size() - 1).getPosition());
                Log.e("OSMCH","North Lat = "+b.getLatNorth());
                Log.e("OSMCH","East Lon = "+b.getLonEast());
                Log.e("OSMCH","South Lat = "+b.getLatSouth());
                Log.e("OSMCH","West Lon = "+b.getLonWest());
                map.zoomToBoundingBox(b, false, 100);  //  <=== line 977
                map.invalidate();
            } else {
                Toast.makeText(ctx, "something wrong with waypoints", Toast.LENGTH_SHORT).show();
            }
//            mapController.setCenter(saveCentre);
//            mapController.setZoom(saveZoom);
        }
        paused = false;
        map.onResume(); //needed for compass, my location overlays, v6.0.0 and up
    }
```
and the logcat error I'm getting is:-

```
2019-09-02 17:39:04.227 12911-12911/com.corunna.osm E/OSMCH: --  onResume
2019-09-02 17:39:04.255 12911-12911/com.corunna.osm E/OSMCH: North Lat = 52.31231
2019-09-02 17:39:04.255 12911-12911/com.corunna.osm E/OSMCH: East Lon = 0.71795
2019-09-02 17:39:04.255 12911-12911/com.corunna.osm E/OSMCH: South Lat = 52.24896
2019-09-02 17:39:04.255 12911-12911/com.corunna.osm E/OSMCH: West Lon = 0.6377
2019-09-02 17:39:04.258 12911-12911/com.corunna.osm E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.corunna.osm, PID: 12911
    java.lang.RuntimeException: Unable to resume activity {com.corunna.osm/com.corunna.osm.MainActivity}: java.lang.IllegalArgumentException: north must be in [-85.05112877980658,85.05112877980658]
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3790)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3830)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3038)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4921)
        at android.app.ActivityThread.-wrap19(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1702)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.IllegalArgumentException: north must be in [-85.05112877980658,85.05112877980658]
        at org.osmdroid.util.BoundingBox.set(BoundingBox.java:67)
        at org.osmdroid.views.Projection.refresh(Projection.java:666)
        at org.osmdroid.views.Projection.<init>(Projection.java:99)
        at org.osmdroid.views.Projection.<init>(Projection.java:110)
        at org.osmdroid.views.MapView.zoomToBoundingBox(MapView.java:545)
        at org.osmdroid.views.MapView.zoomToBoundingBox(MapView.java:571)
        at com.corunna.osm.MainActivity.onResume(MainActivity.java:977)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1361)
        at android.app.Activity.performResume(Activity.java:7361)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3765)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3830) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3038) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4921) 
        at android.app.ActivityThread.-wrap19(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1702) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
``` 

As far as I can see the error is caused by a validation check in `BoungingBox.java` the `Tilesystem` is not getting initialised but I don't understand why that should be as if I uncomment the 2 `mapController` lines the map is shown properly albeit not quite within the new bounds.

**Comment by deltacharlie1** [comment]
I don't know why the last bit of text is marked as code, it shouldn't be.  It should, in fact, read:0

As far as I can see the error is caused by a validation check in `BoungingBox.java` the `Tilesystem` is not getting initialised but I don't understand why that should be as if I uncomment the 2 `mapController` lines the map is shown properly albeit not quite within the new bounds.

**Comment by monsieurtanuki** [comment]
I guess the `zoomToBoundingBox` part must be inside a `post` statement, because we need the `MapView` (as a `View`) to be initialized, in order to know its width and height and then being able to compute the correct zoom.
Something like
````java
map.post(new Runnable(){
    public void run() {
        map.zoomToBoundingBox(...);
    }
});
````

Regarding the formatting of your post, just try to start with "4 backquotes + java" and end with "4 bacquotes" (it looks like sometimes you end with only 3 of them).

**Comment by deltacharlie1** [comment]
Yes!  That worked perfectly - thank you very much for your advice (including the formatting).
