### ISSUE TITLE
Exception when loading tiles from zip archive -  java.io.IOException: mark/reset not supported

### ISSUE THREAD

**Issue by Ruediger34** [osmdroid/osmdroid#1406]
## Issue Type

[x ] Question
[x] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

I´m trying to load tiles from a zip archive with the following code:

	final File[] allZipFiles = fileHelper.listAllFilesInFolderWithExtension(pathToMapFileDirectory, ".zip");
	final OfflineTileProvider tileProvider = new OfflineTileProvider(new SimpleRegisterReceiver(this), allZipFiles);
	final ITileSource tileSource = new FileBasedTileSource(osmTileName, 0, 19, 512, ".png", null);
	map.setTileProvider(tileProvider);
	map.setTileSource(tileSource);

This works flawless with versions of osmdroid < 6.1.1. 

But beginning with 6.1.1 the following exception is thrown:

	W/OsmDroid: #547 Error loading bitmaposm
    java.io.IOException: mark/reset not supported
        at java.util.zip.InflaterInputStream.reset(InflaterInputStream.java:298)
        at org.osmdroid.tileprovider.tilesource.BitmapTileSourceBase.getDrawable(BitmapTileSourceBase.java:185)
        at org.osmdroid.tileprovider.modules.MapTileFileArchiveProvider$TileLoader.loadTile(MapTileFileArchiveProvider.java:234)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:183)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:149)
        at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:131)
        at org.osmdroid.tileprovider.modules.MapTileApproximater$TileLoader.loadTile(MapTileApproximater.java:112)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

I think it's related with #1310 

Do you have any hint for me?

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.1

**Comment by spyhunter99** [comment]
well thats not good....

**Comment by spyhunter99** [comment]
i should have a snapshot update momentarily with a fix, stand by

**Comment by spyhunter99** [comment]
snapshots updated, can you give it a shot? if it fixes the issue, i'll cut another version today

**Comment by Ruediger34** [comment]
Ok, I have tested 6.1.2 snapshot. Now all tiles are loaded from the archive as before. 
No exception anymore.

Thank you.

**Comment by spyhunter99** [comment]
ok i'll get to work on the release. unfortunately sonatype is having all
kinds of issues at the moment, may have to wait until monday
