### ISSUE TITLE
speech bubble causes crash after back button during animation

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#1407]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

ion ? true
    Handing Exception on to default ExceptionHandler
09-28 19:11:15.878 19544-21941/org.osmdroid E/AndroidRuntime: FATAL EXCEPTION: Timer-19
    Process: org.osmdroid, PID: 19544
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.osmdroid.views.MapView.getContext()' on a null object reference
        at org.osmdroid.views.overlay.Marker.<init>(Marker.java:92)
        at org.osmdroid.samplefragments.data.SampleSpeechBalloon.addToDisplay(SampleSpeechBalloon.java:136)
        at org.osmdroid.samplefragments.data.SampleSpeechBalloon.displayNext(SampleSpeechBalloon.java:107)
        at org.osmdroid.samplefragments.data.SampleSpeechBalloon.access$100(SampleSpeechBalloon.java:25)
        at org.osmdroid.samplefragments.data.SampleSpeechBalloon$3.run(SampleSpeechBalloon.java:118)
        at java.util.Timer$TimerImpl.run(Timer.java:284)

**Comment by monsieurtanuki** [comment]
@spyhunter99 Oh, it's just related to the animation process of the sample, it has nothing to do with the speech balloon feature itself.
I will fix it.

**Comment by monsieurtanuki** [comment]
I mean, I will fix it as soon as Android Studio starts compiling what I've just written instead of what I wrote 2 months ago...
