### ISSUE TITLE
app crash, sample follow me

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#1411]
## Issue Type

[ ] Bug

## Description and/or steps/code to reproduce the problem

sample follow me, then use the zoom buttons. looks like its creating an infinite loop

### Version of osmdroid the issue relates to:

6.1.2

````

10-05 08:27:39.955  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:137)
10-05 08:27:39.955  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:183)
10-05 08:27:39.955  2253  2253 W System.err: 	at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
10-05 08:27:39.955  2253  2253 W System.err: 	at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
10-05 08:27:39.955  2253  2253 W System.err: 	at android.animation.ValueAnimator.end(ValueAnimator.java:1133)
10-05 08:27:39.955  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:167)
10-05 08:27:39.955  2253  2253 W System.err: 	at org.osmdroid.views.MapView.setZoomLevel(MapView.java:502)
10-05 08:27:39.955  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:167)
10-05 08:27:39.955  2253  2253 W System.err: 	at org.osmdroid.views.MapView.setZoomLevel(MapView.java:502)
10-05 08:27:39.955  2253  2253 W System.err: 	at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
10-05 08:27:39.955  2253  2253 W System.err: 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1547)
10-05 08:27:39.955  2253  2253 W System.err: 	at android.animation.ValueAnimator.end(ValueAnimator.java:1133)
10-05 08:27:39.955  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:167)
10-05 08:27:39.955  2253  2253 W System.err: 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1547)
10-05 08:27:39.956  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:129)
10-05 08:27:39.956  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:129)
10-05 08:27:39.956  2253  2253 W System.err: 	at org.osmdroid.views.MapView.setZoomLevel(MapView.java:502)
10-05 08:27:39.956  2253  2253 W System.err: 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1547)
10-05 08:27:39.956  2253  2253 W System.err: 	at android.animation.ValueAnimator.end(ValueAnimator.java:1133)
10-05 08:27:39.956  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:137)
10-05 08:27:39.956  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:129)
10-05 08:27:39.956  2253  2253 W System.err: 	at org.osmdroid.views.MapView.setZoomLevel(MapView.java:502)
10-05 08:27:39.956  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:167)
10-05 08:27:39.956  2253  2253 W System.err: 	at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
10-05 08:27:39.956  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:183)
10-05 08:27:39.956  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:129)
10-05 08:27:39.956  2253  2253 W System.err: 	at org.osmdroid.views.MapView.setZoomLevel(MapView.java:502)
10-05 08:27:39.956  2253  2253 W System.err: 	at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
10-05 08:27:39.956  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:183)
10-05 08:27:39.956  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:129)
10-05 08:27:39.956  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:137)
10-05 08:27:39.956  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:167)
10-05 08:27:39.956  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:137)
10-05 08:27:39.957  2253  2253 W System.err: 	at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
10-05 08:27:39.957  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:167)
10-05 08:27:39.957  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:183)
10-05 08:27:39.957  2253  2253 W System.err: 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1547)
10-05 08:27:39.957  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:137)
10-05 08:27:39.957  2253  2253 W System.err: 	at org.osmdroid.views.MapView.setZoomLevel(MapView.java:502)
10-05 08:27:39.957  2253  2253 W System.err: 	at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
10-05 08:27:39.957  2253  2253 W System.err: 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1547)
10-05 08:27:39.957  2253  2253 W System.err: 	at android.animation.ValueAnimator.end(ValueAnimator.java:1133)
10-05 08:27:39.957  2253  2253 W System.err: 	at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
10-05 08:27:39.957  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:183)
10-05 08:27:39.957  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:167)
10-05 08:27:39.958  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:129)
10-05 08:27:39.958  2253  2253 W System.err: 	at org.osmdroid.views.MapView.setZoomLevel(MapView.java:502)
10-05 08:27:39.958  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:183)
10-05 08:27:39.958  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:129)
10-05 08:27:39.958  2253  2253 W System.err: 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1547)
10-05 08:27:39.958  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:137)
10-05 08:27:39.958  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:183)
10-05 08:27:39.958  2253  2253 W System.err: 	at android.animation.ValueAnimator.end(ValueAnimator.java:1133)
10-05 08:27:39.958  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:167)
10-05 08:27:39.958  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:137)
10-05 08:27:39.958  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:183)
10-05 08:27:39.958  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:129)
10-05 08:27:39.958  2253  2253 W System.err: 	at org.osmdroid.views.MapView.setZoomLevel(MapView.java:502)
10-05 08:27:39.958  2253  2253 W System.err: 	at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
10-05 08:27:39.958  2253  2253 W System.err: 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1547)
10-05 08:27:39.958  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:137)
10-05 08:27:39.958  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:183)
10-05 08:27:39.958  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:129)
10-05 08:27:39.958  2253  2253 W System.err: 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1547)
10-05 08:27:39.958  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:129)
10-05 08:27:39.958  2253  2253 W System.err: 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1547)
10-05 08:27:39.958  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:167)
10-05 08:27:39.958  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:137)
10-05 08:27:39.958  2253  2253 W System.err: 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1547)
10-05 08:27:39.958  2253  2253 W System.err: 	at android.animation.ValueAnimator.end(ValueAnimator.java:1133)
10-05 08:27:39.958  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:167)
10-05 08:27:39.959  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:167)
10-05 08:27:39.959  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:137)
10-05 08:27:39.959  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:183)
10-05 08:27:39.959  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:129)
10-05 08:27:39.959  2253  2253 W System.err: 	at org.osmdroid.views.MapView.setZoomLevel(MapView.java:502)
10-05 08:27:39.959  2253  2253 W System.err: 	at android.animation.ValueAnimator.end(ValueAnimator.java:1133)
10-05 08:27:39.959  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:167)
10-05 08:27:39.960  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:137)
10-05 08:27:39.960  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:183)
10-05 08:27:39.960  2253  2253 W System.err: 	at android.animation.ValueAnimator.end(ValueAnimator.java:1133)
10-05 08:27:39.960  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:167)
10-05 08:27:39.960  2253  2253 W System.err: 	at org.osmdroid.views.MapView.setZoomLevel(MapView.java:502)
10-05 08:27:39.960  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:137)
10-05 08:27:39.960  2253  2253 W System.err: 	at android.animation.ValueAnimator.end(ValueAnimator.java:1133)
10-05 08:27:39.960  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:167)
10-05 08:27:39.960  2253  2253 W System.err: 	at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
10-05 08:27:39.960  2253  2253 W System.err: 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1547)
10-05 08:27:39.960  2253  2253 W System.err: 	at android.animation.ValueAnimator.end(ValueAnimator.java:1133)
10-05 08:27:39.960  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:167)
10-05 08:27:39.960  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:129)
10-05 08:27:39.960  2253  2253 W System.err: 	at android.animation.ValueAnimator.end(ValueAnimator.java:1133)
10-05 08:27:39.960  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:129)
10-05 08:27:39.961  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:183)
10-05 08:27:39.961  2253  2253 W System.err: 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1547)
10-05 08:27:39.961  2253  2253 W System.err: 	at android.animation.ValueAnimator.end(ValueAnimator.java:1133)
10-05 08:27:39.961  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:167)
10-05 08:27:39.961  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:137)
10-05 08:27:39.961  2253  2253 W System.err: 	at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
10-05 08:27:39.961  2253  2253 W System.err: 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1547)
10-05 08:27:39.961  2253  2253 W System.err: 	at android.animation.ValueAnimator.end(ValueAnimator.java:1133)
10-05 08:27:39.961  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:129)
10-05 08:27:39.961  2253  2253 W System.err: 	at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
10-05 08:27:39.961  2253  2253 W System.err: 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1547)
10-05 08:27:39.961  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:137)
10-05 08:27:39.961  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:183)
10-05 08:27:39.961  2253  2253 W System.err: 	at android.animation.ValueAnimator.end(ValueAnimator.java:1133)
10-05 08:27:39.961  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:167)
10-05 08:27:39.962  2253  2253 I chatty  : uid=10271(org.osmdroid) identical 1 line
10-05 08:27:39.962  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:167)
10-05 08:27:39.962  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:137)
10-05 08:27:39.962  2253  2253 W System.err: 	at org.osmdroid.views.MapView.setZoomLevel(MapView.java:502)
10-05 08:27:39.962  2253  2253 W System.err: 	at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
10-05 08:27:39.962  2253  2253 W System.err: 	at android.animation.ValueAnimator.end(ValueAnimator.java:1133)
10-05 08:27:39.962  2253  2253 W System.err: 	at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
10-05 08:27:39.962  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:183)
10-05 08:27:39.962  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:129)
10-05 08:27:39.962  2253  2253 W System.err: 	at android.animation.ValueAnimator.end(ValueAnimator.java:1133)
10-05 08:27:39.962  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:167)
10-05 08:27:39.962  2253  2253 W System.err: 	at org.osmdroid.views.MapView.setZoomLevel(MapView.java:502)
10-05 08:27:39.962  2253  2253 W System.err: 	at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
10-05 08:27:39.963  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:167)
10-05 08:27:39.963  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:183)
10-05 08:27:39.963  2253  2253 W System.err: 	at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
10-05 08:27:39.963  2253  2253 W System.err: 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1547)
10-05 08:27:39.963  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:183)
10-05 08:27:39.963  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:129)
10-05 08:27:39.963  2253  2253 W System.err: 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1547)
10-05 08:27:39.963  2253  2253 W System.err: 	at android.animation.ValueAnimator.end(ValueAnimator.java:1133)
10-05 08:27:39.963  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:183)
10-05 08:27:39.963  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:167)
10-05 08:27:39.963  2253  2253 W System.err: 	at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
10-05 08:27:39.963  2253  2253 W System.err: 	at android.animation.ValueAnimator.end(ValueAnimator.java:1133)
10-05 08:27:39.963  2253  2253 W System.err: 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1547)
10-05 08:27:39.963  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:137)
10-05 08:27:39.963  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:183)
10-05 08:27:39.963  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:129)
10-05 08:27:39.963  2253  2253 W System.err: 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1547)
10-05 08:27:39.963  2253  2253 W System.err: 	at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
10-05 08:27:39.963  2253  2253 W System.err: 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1547)
10-05 08:27:39.963  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:129)
10-05 08:27:39.964  2253  2253 W System.err: 	at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
10-05 08:27:39.964  2253  2253 W System.err: 	at android.animation.ValueAnimator.end(ValueAnimator.java:1133)
10-05 08:27:39.964  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:167)
10-05 08:27:39.964  2253  2253 W System.err: 	at org.osmdroid.views.MapView.setZoomLevel(MapView.java:502)
10-05 08:27:39.964  2253  2253 W System.err: 	at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
10-05 08:27:39.964  2253  2253 W System.err: 	at org.osmdroid.views.MapController.animateTo(MapController.java:137)
````

**Comment by spyhunter99** [comment]
my bad, this was on a snapshot 6.1.1 version. current version is not affected
