### ISSUE TITLE
NullPointerException: TilesOverlay.java line 328

### ISSUE THREAD

**Issue by ziem** [osmdroid/osmdroid#157]
Can't reproduce.

Device:
Sony Xperia J (ST26i)
Android 4.1.2

https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/TilesOverlay.java#L328

> java.lang.NullPointerException
       at android.graphics.Canvas.<init>(Canvas.java:126)
       at org.osmdroid.views.overlay.TilesOverlay.getLoadingTile(TilesOverlay.java:328)
       at org.osmdroid.views.overlay.TilesOverlay.access$100(TilesOverlay.java:38)
       at org.osmdroid.views.overlay.TilesOverlay$1.handleTile(TilesOverlay.java:175)
       at org.osmdroid.util.TileLooper.loop(TileLooper.java:34)
       at org.osmdroid.views.overlay.TilesOverlay.drawTiles(TilesOverlay.java:149)
       at org.osmdroid.views.overlay.TilesOverlay.draw(TilesOverlay.java:136)
       at org.osmdroid.views.overlay.OverlayManager.onDraw(OverlayManager.java:109)
       at org.osmdroid.views.MapView.dispatchDraw(MapView.java:988)
       at android.view.View.getDisplayList(View.java:12522)
       at android.view.View.getDisplayList(View.java:12568)
       at android.view.View.draw(View.java:13297)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2907)
       at android.view.View.getDisplayList(View.java:12522)
       at android.view.View.getDisplayList(View.java:12568)
       at android.view.View.draw(View.java:13297)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2907)
       at android.view.View.getDisplayList(View.java:12522)
       at android.view.View.getDisplayList(View.java:12568)
       at android.view.View.draw(View.java:13297)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2907)
       at android.view.View.getDisplayList(View.java:12522)
       at android.view.View.getDisplayList(View.java:12568)
       at android.view.View.draw(View.java:13297)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2907)
       at android.view.View.getDisplayList(View.java:12522)
       at android.view.View.getDisplayList(View.java:12568)
       at android.view.View.draw(View.java:13297)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2907)
       at android.view.View.getDisplayList(View.java:12522)
       at android.view.View.getDisplayList(View.java:12568)
       at android.view.View.draw(View.java:13297)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2907)
       at android.view.View.getDisplayList(View.java:12522)
       at android.view.View.getDisplayList(View.java:12568)
       at android.view.View.draw(View.java:13297)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2907)
       at android.view.View.getDisplayList(View.java:12522)
       at android.view.View.getDisplayList(View.java:12568)
       at android.view.View.draw(View.java:13297)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2907)
       at android.view.View.draw(View.java:13576)
       at android.widget.FrameLayout.draw(FrameLayout.java:480)
       at android.view.View.getDisplayList(View.java:12524)
       at android.view.View.getDisplayList(View.java:12568)
       at android.view.View.draw(View.java:13297)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2907)
       at android.view.View.getDisplayList(View.java:12522)
       at android.view.View.getDisplayList(View.java:12568)
       at android.view.View.draw(View.java:13297)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2907)
       at android.view.View.getDisplayList(View.java:12522)
       at android.view.View.getDisplayList(View.java:12568)
       at android.view.View.draw(View.java:13297)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2907)
       at android.view.View.getDisplayList(View.java:12522)
       at android.view.View.getDisplayList(View.java:12568)
       at android.view.View.draw(View.java:13297)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2907)
       at android.view.View.draw(View.java:13576)
       at android.widget.FrameLayout.draw(FrameLayout.java:480)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2187)
       at android.view.View.getDisplayList(View.java:12524)
       at android.view.View.getDisplayList(View.java:12568)
       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1179)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2150)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2022)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1833)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:999)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4217)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
       at android.view.Choreographer.doCallbacks(Choreographer.java:555)
       at android.view.Choreographer.doFrame(Choreographer.java:525)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4802)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:813)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:580)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by spyhunter99** [comment]
could be an OOM situation

**Comment by spyhunter99** [comment]
I added an extra catch in the block. if you run into it again, please reopen
