### ISSUE TITLE
NullPointerException when adding Markers after mapView is detached

### ISSUE THREAD

**Issue by farmazon3000** [osmdroid/osmdroid#1570]
My markers are being added asyncronously - if it happens that adding markers function is so long (many markers) that it's being executed while map gets detached, then NPE happens.
```
java.lang.NullPointerException: Attempt to invoke virtual method 'org.osmdroid.views.MapViewRepository org.osmdroid.views.MapView.getRepository()' on a null object reference
at org.osmdroid.views.overlay.infowindow.InfoWindow.<init>(InfoWindow.java:53)
at org.osmdroid.views.overlay.infowindow.BasicInfoWindow.<init>(BasicInfoWindow.java:54)
at org.osmdroid.views.overlay.infowindow.MarkerInfoWindow.<init>(MarkerInfoWindow.java:42)
at org.osmdroid.views.MapViewRepository.getDefaultMarkerInfoWindow(MapViewRepository.java:54)
at org.osmdroid.views.overlay.Marker.<init>(Marker.java:116)
at org.osmdroid.views.overlay.Marker.<init>(Marker.java:93)
```

This is caused because ```map``` passed when Marker is constructed:
```
val nextMarker = Marker(map)
```
is not the same ```map``` which is used here:
```
public InfoWindow(int layoutResId, MapView mapView) {
        mMapView = mapView;
        mMapView.getRepository().add(this); // <--- NPE here
        mIsVisible = false;
        ViewGroup parent = (ViewGroup) mapView.getParent();
        Context context = mapView.getContext();
        LayoutInflater inflater = (LayoutInflater) context.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        mView = inflater.inflate(layoutResId, parent, false);
        mView.setTag(this);
    }
```

**Comment by farmazon3000** [comment]
OMG! I found a work around with [Activity.isDestroyed()](https://developer.android.com/reference/android/app/Activity#isDestroyed()) thing:
```
if(isDestroyed){
    return
}
val nextMarker = Marker(map)
```

**Comment by monsieurtanuki** [comment]
@farmazon3000 I'm not sure I see the point of a `Marker` if the `MapView` it's been created on is detached.
I believe that everytime you create a new `MapView`, you have to recreate all your `Marker`s.

**Comment by farmazon3000** [comment]
Yes, this is what I'm doing. But if I enter screen and start creating Markers in background thread and then immediately go back, thread with markers is still creating while the Activity with mapView is long time ago destroyed.

I posted a workaround which works for me at least.

**Comment by monsieurtanuki** [comment]
I guess it would be cleaner to cancel the async task in those cases.
That doesn't look like an osmdroid issue, where you're not supposed to add Markers to detached MapViews.
Feel free to close the issue if that makes sense.

**Comment by cbalster** [comment]
@monsieurtanuki is right. It's your responsibility to check if a view still exists when you're referencing it from another thread - as with all other views. Your solution is perfectly fine and not a workaround. Cancelling the thread as soon as the activity is destroyed is also a good idea if your task is taking a really long time, since it holds on to the MapView reference and thereby leaks the whole view hierarchy for as long as it runs.

**Comment by farmazon3000** [comment]
You are right. However if I'm adding Marker to a map, I don't see the reason why internally it creates some additional InfoWindow which in turn uses some other (wrong I think) reference to map.

There should be possibility to create marker with no InfoWindow and InfoWindow should use the map reference passed to Marker. What do you think?

**Comment by monsieurtanuki** [comment]
@farmazon3000 https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/Marker.java#L286:
```java
/* If you don't want any InfoWindow to open, you can set it to null. */
public void setInfoWindow(MarkerInfoWindow infoWindow){
    mInfoWindow = infoWindow;
}
```

**Comment by AlexSuvorov2k** [comment]
I had this problem when I used lazy initialization of view:
`private val mapView: MapView by lazy {
        binding.mapView
}`

The problem went away when I removed lazy initialization.
