### ISSUE TITLE
StackOverflowException

### ISSUE THREAD

**Issue by jimmyw** [osmdroid/osmdroid#1579]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[ X ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

Upgrade to osmdroid 6.1.0 to 6.1.6 starters generating StackOverflow in my app.

Fatal Exception: java.lang.StackOverflowError: stack size 8MB
       at java.lang.ref.FinalizerReference.add(FinalizerReference.java:54)
       at org.osmdroid.views.Projection.<init>(Projection.java:45)
       at org.osmdroid.views.Projection.<init>(Projection.java:65)
       at org.osmdroid.views.MapView.getProjection(MapView.java:358)
       at org.osmdroid.views.MapView.setExpectedCenter(MapView.java:1809)
       at org.osmdroid.views.MapView.setExpectedCenter(MapView.java:1823)
       at org.osmdroid.views.MapController.setCenter(MapController.java:227)
       at org.osmdroid.views.MapView.setZoomLevel(MapView.java:484)
       at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
       at android.animation.ValueAnimator.end(ValueAnimator.java:1155)
       at org.osmdroid.views.MapController.animateTo(MapController.java:167)
       at org.osmdroid.views.MapController.animateTo(MapController.java:137)
       at org.osmdroid.views.MapController.animateTo(MapController.java:183)
       at org.osmdroid.views.MapController.animateTo(MapController.java:129)
       at org.osmdroid.views.MapView.setZoomLevel(MapView.java:492)
       at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
       at android.animation.ValueAnimator.end(ValueAnimator.java:1155)
       at org.osmdroid.views.MapController.animateTo(MapController.java:167)
       at org.osmdroid.views.MapController.animateTo(MapController.java:137)
       at org.osmdroid.views.MapController.animateTo(MapController.java:183)
       at org.osmdroid.views.MapController.animateTo(MapController.java:129)
       at org.osmdroid.views.MapView.setZoomLevel(MapView.java:492)
       at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
       at android.animation.ValueAnimator.end(ValueAnimator.java:1155)
       at org.osmdroid.views.MapController.animateTo(MapController.java:167)
       at org.osmdroid.views.MapController.animateTo(MapController.java:137)
       at org.osmdroid.views.MapController.animateTo(MapController.java:183)
       at org.osmdroid.views.MapController.animateTo(MapController.java:129)
       at org.osmdroid.views.MapView.setZoomLevel(MapView.java:492)
       at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
       at android.animation.ValueAnimator.end(ValueAnimator.java:1155)
       at org.osmdroid.views.MapController.animateTo(MapController.java:167)
       at org.osmdroid.views.MapController.animateTo(MapController.java:137)
       at org.osmdroid.views.MapController.animateTo(MapController.java:183)
       at org.osmdroid.views.MapController.animateTo(MapController.java:129)
       at org.osmdroid.views.MapView.setZoomLevel(MapView.java:492)
       at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
       at android.animation.ValueAnimator.end(ValueAnimator.java:1155)
       at org.osmdroid.views.MapController.animateTo(MapController.java:167)
       at org.osmdroid.views.MapController.animateTo(MapController.java:137)
       at org.osmdroid.views.MapController.animateTo(MapController.java:183)
       at org.osmdroid.views.MapController.animateTo(MapController.java:129)
       at org.osmdroid.views.MapView.setZoomLevel(MapView.java:492)
       at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
       at android.animation.ValueAnimator.end(ValueAnimator.java:1155)
       at org.osmdroid.views.MapController.animateTo(MapController.java:167)
       at org.osmdroid.views.MapController.animateTo(MapController.java:137)
       at org.osmdroid.views.MapController.animateTo(MapController.java:183)
       at org.osmdroid.views.MapController.animateTo(MapController.java:129)
       at org.osmdroid.views.MapView.setZoomLevel(MapView.java:492)
       at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
       at android.animation.ValueAnimator.end(ValueAnimator.java:1155)
       at org.osmdroid.views.MapController.animateTo(MapController.java:167)
       at org.osmdroid.views.MapController.animateTo(MapController.java:137)
       at org.osmdroid.views.MapController.animateTo(MapController.java:183)
       at org.osmdroid.views.MapController.animateTo(MapController.java:129)
       at org.osmdroid.views.MapView.setZoomLevel(MapView.java:492)
       at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
       at android.animation.ValueAnimator.end(ValueAnimator.java:1155)
       at org.osmdroid.views.MapController.animateTo(MapController.java:167)
       at org.osmdroid.views.MapController.animateTo(MapController.java:137)
       at org.osmdroid.views.MapController.animateTo(MapController.java:183)
       at org.osmdroid.views.MapController.animateTo(MapController.java:129)
       at org.osmdroid.views.MapView.setZoomLevel(MapView.java:492)
       at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
       at android.animation.ValueAnimator.end(ValueAnimator.java:1155)
       at org.osmdroid.views.MapController.animateTo(MapController.java:167)
       at org.osmdroid.views.MapController.animateTo(MapController.java:137)
       at org.osmdroid.views.MapController.animateTo(MapController.java:183)
       at org.osmdroid.views.MapController.animateTo(MapController.java:129)
       at org.osmdroid.views.MapView.setZoomLevel(MapView.java:492)
       at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
       at android.animation.ValueAnimator.end(ValueAnimator.java:1155)
       at org.osmdroid.views.MapController.animateTo(MapController.java:167)
       at org.osmdroid.views.MapController.animateTo(MapController.java:137)
       at org.osmdroid.views.MapController.animateTo(MapController.java:183)
       at org.osmdroid.views.MapController.animateTo(MapController.java:129)
       at org.osmdroid.views.MapView.setZoomLevel(MapView.java:492)
       at org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate(MapController.java:520)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
       at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1384)
       at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1427)
       at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:759)
       at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
       at android.view.Choreographer.doCallbacks(Choreographer.java:696)
       at android.view.Choreographer.doFrame(Choreographer.java:628)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5765)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

### If it's a bug, version(s) of android this affects:

6.1.6 and not 6.1.0

### Version of osmdroid the issue relates to:

6.1.6

**Comment by monsieurtanuki** [comment]
@jimmyw Similar to #1299? 
Maybe related to the behavior of one `Overlay` - could you please test by removing your `Overlay`s one by one, in order to find the guilty one?

**Comment by jimmyw** [comment]
I can only see it from reports in production. I have another go trying to trigger the bug my self. I'm not sure how it ends up here. Hoped this stacktrace would help.

**Comment by monsieurtanuki** [comment]
@jimmyw The stacktrace helps: it makes me think of #1299. Found anything in its comments that looks familiar?
