### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'org.osmdroid.views.MapViewRepository org.osmdroid.views.MapView.getRepository()' on a null object reference adding Marker

### ISSUE THREAD

**Issue by gionixiot** [osmdroid/osmdroid#1581]
The application crash adding Marker with:
    java.lang.NullPointerException: Attempt to invoke virtual method 'org.osmdroid.views.MapViewRepository org.osmdroid.views.MapView.getRepository()' on a null object reference
        at org.osmdroid.views.overlay.infowindow.InfoWindow.<init>(InfoWindow.java:53)
        at org.osmdroid.views.overlay.infowindow.BasicInfoWindow.<init>(BasicInfoWindow.java:54)
        at org.osmdroid.views.overlay.infowindow.MarkerInfoWindow.<init>(MarkerInfoWindow.java:42)
        at org.osmdroid.views.MapViewRepository.getDefaultMarkerInfoWindow(MapViewRepository.java:54)
        at org.osmdroid.views.overlay.Marker.<init>(Marker.java:116)
        at org.osmdroid.views.overlay.Marker.<init>(Marker.java:93)
        at com.gionix.iot.GlobalMapActivity.addMarkerLocation(GlobalMapActivity.java:701)
        at com.gionix.iot.GlobalMapActivity$1.onLocationResult(GlobalMapActivity.java:200)
        at com.google.android.gms.internal.zzchc.zzu(Unknown Source)
        at com.google.android.gms.common.api.internal.zzci.zzb(Unknown Source)
        at com.google.android.gms.common.api.internal.zzcj.handleMessage(Unknown Source)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5569)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)

### If it's a bug, version(s) of android this affects:

android 22

### Version of osmdroid the issue relates to:

6.1.6/ 6.1.5

**Comment by monsieurtanuki** [comment]
@gionixiot Probably same as #1570, isn't it?

**Comment by gionixiot** [comment]
@monsieurtanuki 
No, it happens when I try to add a marker in an AsyncTask and not when I go back and the MapView is detached or destroyed

**Comment by monsieurtanuki** [comment]
I still looks like you're creating a Marker with a null MapView and that a portion of the code about InfoWindow triggers the crash.

**Comment by gionixiot** [comment]
This is in onCreate :

        Context ctx = getApplicationContext();
        Configuration.getInstance().setUserAgentValue(ctx.getPackageName());
        map = (MapView) findViewById(R.id.map);
        map.setTileSource(TileSourceFactory.MAPNIK);
        map.setBuiltInZoomControls(true);
        map.setMultiTouchControls(true);

        mapController = map.getController();
        mapController.setZoom(18.0);
        globalMapOverlay = new GlobalMapOverlay(this);
        globalMapOverlay.setSelectText(getApplicationContext().getResources().getString(R.string.popup_station));
        map.getOverlays().add(globalMapOverlay);

        locationManager = (LocationManager) getSystemService(LOCATION_SERVICE);

        fusedLocationClient = LocationServices.getFusedLocationProviderClient(this);

        locationrequest = LocationRequest.create();
        locationrequest.setPriority(LocationRequest.PRIORITY_HIGH_ACCURACY);
        locationrequest.setInterval(UPDATE_INTERVAL);
        locationrequest.setFastestInterval(FASTEST_INTERVAL);
        locationCallback = new LocationCallback() {
            @Override
            public void onLocationResult(LocationResult locationResult) {
                if (locationResult == null) {
                    return;
                }
                for (Location location : locationResult.getLocations()) {
                    if (!locationUpdate) {
                        Log.e("LAT-LONG", location.getLatitude() + " - " + location.getLongitude());
                        startPoint = new GeoPoint(location.getLatitude(), location.getLongitude());
                        mapController.setCenter(startPoint);
                        mapController.animateTo(startPoint);
                        mapController.zoomIn();
                        //addMarkerLocation(map,startPoint);

                        Marker startMarker = new Marker(map);

                        Log.e("STARTPOINT",location.getLatitude()+" - "+ location.getLongitude());
                        //startMarker.setSnippet("You are here");
                        //startMarker.setSubDescription("Latitude: "+location.getLatitude()+" Longitude: "+location.getLongitude());
                        Drawable icon = getResources().getDrawable(R.drawable.bubble_bike);
                        startMarker.setImage(icon);
                        startMarker.setPosition(startPoint);
                        startMarker.setIcon(getResources().getDrawable(R.drawable.marker));
                        startMarker.setAnchor(Marker.ANCHOR_CENTER, Marker.ANCHOR_BOTTOM);
                        //MarkerInfoWindow info = new MarkerInfoWindow(R.layout.bubble_info_window,map);
                        CustomInfoWindow info = new CustomInfoWindow(map);
                        startMarker.setInfoWindow(info);
                        Button btn = (Button) (info.getView().findViewById(R.id.bubble_button));
                        btn.setOnClickListener(new View.OnClickListener() {
                            public void onClick(View view) {
                                Toast.makeText(view.getContext(), "Global map Button clicked", Toast.LENGTH_LONG).show();
                            }
                        });

                        map.getOverlays().add(startMarker);
                        startMarker.setTitle("Start");
                        startMarker.setSnippet("You are here");
                        startMarker.setSubDescription("Latitude: "+location.getLatitude()+" Longitude: "+location.getLongitude());


                        locationUpdate = true;
                    }
                }
            };
        };

The MapView is created before,and if remove Marker startMarker = new Marker(map); is displayed correctly

**Comment by farmazon3000** [comment]
This is exactly the same as #1570, try my workaround published there.

**Comment by AlexSuvorov2k** [comment]
I had this problem when I used lazy initialization of view:
`private val mapView: MapView by lazy {
        binding.mapView
}`

The problem went away when I removed lazy initialization.
