### ISSUE TITLE
Tests gail when building osmdroid with gradle

### ISSUE THREAD

**Issue by KatharinaSick** [osmdroid/osmdroid#1604]
## Issue Type

- [x] Build system related

## Description and/or steps/code to reproduce the problem
I followed the steps that are described in the "Building with Gradle" section on this page: https://github.com/osmdroid/osmdroid/wiki/How-to-build-OsmDroid-from-source to build the osmdroid project on my local. `./gradlew clean install` shows some warnings but succeeds. When running the tests with `./gradlew cC` the following ones fail:

`org.osmdroid.test.ExtraSamplesTest > testBugsDriversActivity[SM-G975F - 10] FAILED 
        junit.framework.AssertionFailedError: Error popping fragment Issue 512 Cache download using waypointsorg.osmdroid.bugtestfragments.Bug512CacheManagerWpjava.lang.RuntimeException: Failure occurred during the test, there were 16
        at junit.framework.Assert.fail(Assert.java:50)`

`org.osmdroid.tileprovider.modules.MapTileProviderTest > test_jump_queue[SM-G975F - 10] FAILED 
        junit.framework.AssertionFailedError: Three tiles in the list expected:<3> but was:<0>
        at junit.framework.Assert.fail(Assert.java:50)`

`org.osmdroid.tileprovider.modules.MapTileProviderTest > test_order[SM-G975F - 10] FAILED 
        junit.framework.AssertionFailedError: Three tiles in the list expected:<3> but was:<0>
        at junit.framework.Assert.fail(Assert.java:50)
:OpenStreetMapViewer:connectedDebugAndroidTest FAILED`

I also tried to use `publishToMavenLocal` instead of `install` but had the same results.

## Environment
I tried running the test on emulators with Android 8.0, 9.0 and 10.0, as well as on my mobile (Samsung Galaxy S10+ running with Android 10).

I don't know if it matters, but my machine is running on Manjaro Linux (Release 20.0.3 - Lysia)

### Version of osmdroid the issue relates to:

6.1.2

**Comment by monsieurtanuki** [comment]
@KatharinaSick We're currently in the middle of a build system maelstrom (cf. #1594). As a consequence I cannot investigate what goes wrong on this issue. My hunch is that the problem is with the min and max zoom levels in `MapTileProviderTest` (both 0).
I don't believe there's something inherently wrong with your configuration - if possible, just ignore this issue for the moment.

**Comment by KatharinaSick** [comment]
Ok thank you! Then I will wait with issue #1603 until that is done.

**Comment by hannesa2** [comment]
Just for your info, when you run [all tests](https://github.com/osmdroid/osmdroid/pull/1600/checks?check_run_id=810104783) based on most recent Android Studio #1594 then you see what's going wrong currently

**Comment by KatharinaSick** [comment]
thank you!

**Comment by y2020x** [comment]
As for the current version that you downloaded from this site, the routines, test_jump_queue & test_order, need to catch the Exception (using try and catch). Or you could fix them by adding the map names to the list - currently, this list is empty - if you look at the codes, then you know what I meant. But, the best thing is to try to catch the exceptions - I think that is the intent of the test.
