### ISSUE TITLE
MapTileModuleProviderBase.java synchronize locking issue

### ISSUE THREAD

**Issue by ryanbehr** [osmdroid/osmdroid#161]
There appears to be a UI lock issue in MapTileModuleProviderBase.java.

ANR Stack Trace (Please note, line numbers may be slightly off on MapTileModuleProviderBase.java due to my attempts to fix the lockup to provide a solution when submitting this issue): 

```
DALVIK THREADS (41):
"main" prio=5 tid=1 Blocked
  | group="main" sCount=1 dsCount=0 obj=0x87bbaef0 self=0xb4e07800
  | sysTid=9447 nice=0 cgrp=apps sched=0/0 handle=0xb6f84ec8
  | state=S schedstat=( 32509306439 11216208308 55533 ) utm=2710 stm=540 core=2 HZ=100
  | stack=0xbe056000-0xbe058000 stackSize=8MB
  | held mutexes=
  at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase.clearQueue(SourceFile:158)
  - waiting to lock <0x03c80b32> (a java.lang.Object) held by thread 37
  at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase.detach(SourceFile:169)
  at org.osmdroid.tileprovider.modules.MapTileFileStorageProviderBase.detach(SourceFile:55)
  at org.osmdroid.tileprovider.MapTileProviderArray.detach(SourceFile:73)
  - locked <0x2a423083> (a java.util.ArrayList)
  at org.osmdroid.views.overlay.TilesOverlay.onDetach(SourceFile:86)
  at org.osmdroid.views.overlay.OverlayManager.onDetach(SourceFile:132)
  at org.osmdroid.views.MapView.onDetach(SourceFile:751)
  at org.osmdroid.views.MapView.onDetachedFromWindow(SourceFile:1005)
```

Relevant thread 37: 

```
"assets" prio=5 tid=37 Blocked
  | group="main" sCount=1 dsCount=0 obj=0x13795220 self=0xa133d800
  | sysTid=11004 nice=0 cgrp=apps sched=0/0 handle=0x9850b480
  | state=S schedstat=( 4830836 11261406 32 ) utm=0 stm=0 core=1 HZ=100
  | stack=0x9e4e0000-0x9e4e2000 stackSize=1036KB
  | held mutexes=
  at org.osmdroid.tileprovider.MapTileProviderArray.boolean getProviderExists(org.osmdroid.tileprovider.modules.MapTileModuleProviderBase)(SourceFile:194)
  - waiting to lock <0x2a423083> (a java.util.ArrayList) held by thread 1
  at org.osmdroid.tileprovider.MapTileProviderArray.org.osmdroid.tileprovider.modules.MapTileModuleProviderBase findNextAppropriateProvider(org.osmdroid.tileprovider.MapTileRequestState)(SourceFile:181)
  at org.osmdroid.tileprovider.MapTileProviderArray.void mapTileRequestFailed(org.osmdroid.tileprovider.MapTileRequestState)(SourceFile:138)
  at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$1.boolean removeEldestEntry(java.util.Map$Entry)(SourceFile:123)
  at java.util.LinkedHashMap.addNewEntry(LinkedHashMap.java:189)
  at java.util.HashMap.put(HashMap.java:403)
  at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase.boolean getUsesDataConnection()(SourceFile:148)
                                                                 void setTileSource(org.osmdroid.tileprovider.tilesource.ITileSource)
                                                                 void loadMapTileAsync(org.osmdroid.tileprovider.MapTileRequestState)
  - locked <0x03c80b32> (a java.lang.Object)
  at org.osmdroid.tileprovider.MapTileProviderArray.void mapTileRequestFailed(org.osmdroid.tileprovider.MapTileRequestState)(SourceFile:140)
  at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.void tileLoadedFailed(org.osmdroid.tileprovider.MapTileRequestState)(SourceFile:275)
  at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.void run()(SourceFile:303)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
  at java.lang.Thread.run(Thread.java:818)
```

This is duplicated when being in a disconnected environment for a few hours on just about any basemap where the tiles load from online sources. It looks like the synchronized lock object is being held by the main thread or the adding tile to queue thread. Both think the other has the lock. The ondestroy is called when I rotate the device (calls onconfigurationchanged), destroy the MapView and reload it from scratch.

I'll keep working on it but if someone sees something that would help let me know. Thanks.

**Comment by spyhunter99** [comment]
this could be related to #131

**Comment by ryanbehr** [comment]
Now that looks like a promising lead. The only difference I see is these tiles exist but unable to reach the servers to get the tiles. There needs to be some sort of expiration on the requests.. Maybe dump if the tile is no longer in the view?

**Comment by spyhunter99** [comment]
My experience was requesting a tile that doesn't exist. Osmdroid appears to continue to ask for it forever until the UI locks up or performance degrades until it's useless.

**Comment by neilboyd** [comment]
I don't think this has got anything to do with #131.  It's a typical deadlock situation caused by a logic error in the syncing.

**Comment by spyhunter99** [comment]
@ryanbehr did you figure out what the root cause is?

**Comment by spyhunter99** [comment]
ping

**Comment by spyhunter99** [comment]
operation timeout. please reopen or comment back if you have further questions
