### ISSUE TITLE
 Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference

### ISSUE THREAD

**Issue by UrbanSide** [osmdroid/osmdroid#1636]
[X] Question
[X] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
Error on this line
```
        Context ctx = getApplicationContext();
  --> Configuration.getInstance().load(ctx, PreferenceManager.getDefaultSharedPreferences(ctx));
```
When i re-open activity
```
2020-08-31 19:15:00.663 29859-29859/? E/com.urban.map: Unknown bits set in runtime_flags: 0x8000
2020-08-31 19:15:12.831 29859-29859/com.urban.map E/RecyclerView: No adapter attached; skipping layout
2020-08-31 19:15:14.418 29859-29859/com.urban.map E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.urban.map, PID: 29859
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.urban.map/com.urban.map.activites.MapsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
        at org.osmdroid.config.DefaultConfigurationProvider.load(DefaultConfigurationProvider.java:337)
        at com.urban.map.activites.MapsActivity.onCreate(MapsActivity.java:34)
        at android.app.Activity.performCreate(Activity.java:7824)
        at android.app.Activity.performCreate(Activity.java:7813)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

## Environment
```
    compileSdkVersion 29
    buildToolsVersion "29.0.2"
```

### Version of osmdroid the issue relates to:

6.1.2

**Comment by spyhunter99** [comment]
Perhaps try a newer version? There were some changes recently regarding this

**Comment by beigirad** [comment]
I saw this bug on version 6.1.5 when I upgrade osmDroid to 6.1.8
Our old users that upgraded their app saw this crash but new users don't crash.

I think this issue refers to remained shared-preferences from the previous version.

**Comment by coletz** [comment]
Got this issue too with 6.1.8, tried on android 10 and simply followed the how-to guide (https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library). Any known workaround other than forking and fixing on our own?

**Comment by monsieurtanuki** [comment]
@coletz The problem seems to occur on the **default** configuration provider. If you provide your own configuration provider (which can be rather easy), the impact will be limited, fork-wise.

That being said, it looks like the problems comes from either [`StorageInfo StorageUtils.getBestWritableStorage(Context)`](https://github.com/osmdroid/osmdroid/blob/8dda31efbd0cbb5778b824d005ff468d254a8106/osmdroid-android/src/main/java/org/osmdroid/tileprovider/util/StorageUtils.java#L258) returning `null` or [`List<StorageInfo> StorageUtils.getStorageList(Context)`](https://github.com/osmdroid/osmdroid/blob/8dda31efbd0cbb5778b824d005ff468d254a8106/osmdroid-android/src/main/java/org/osmdroid/tileprovider/util/StorageUtils.java#L121) being empty.

@coletz @beigirad @UrbanSide If you guys could play with those methods and find what's wrong with them, that would help.

@coletz @beigirad I've just read your latest edits on your comments, which point to the same direction.
The crash happens in the `Exception` block of [`File DefaultConfigurationProvider.getOsmdroidBasePath(Context)`](https://github.com/osmdroid/osmdroid/blob/8dda31efbd0cbb5778b824d005ff468d254a8106/osmdroid-android/src/main/java/org/osmdroid/config/DefaultConfigurationProvider.java#L250).

**Comment by coletz** [comment]
I'm trying to build the project but having some issue which seems to be related to gradle/os/java combo. Fixing the issue should be pretty straightforward anyway. Replacing lines 337-8 with these should be enough, since `"osmdroid.basePath"` (at least for me) seems to be initialized.

```
File osmdroidBasePath = getOsmdroidBasePath(ctx);
setOsmdroidBasePath(new File(prefs.getString("osmdroid.basePath", osmdroidBasePath != null ? osmdroidBasePath.getAbsolutePath() : null)));
File osmdroidTileCache = getOsmdroidTileCache(ctx);
setOsmdroidTileCache(new File(prefs.getString("osmdroid.cachePath", osmdroidTileCache != null ? osmdroidTileCache.getAbsolutePath() : null)));
```
I'm not able to try unfortunately, sorry

**Comment by monsieurtanuki** [comment]
@coletz I'm not convinced. I can admit that `getOsmdroidBasePath(ctx)` returns `null` and that it's meaningful to test it like you do.
But what about line 316, the init part, shouldn't it also crash for the same reasons?
* what happens if you clear the preferences and restart from scratch?
* do you sometimes use `DefaultConfigurationProvider.setOsmdroidBasePath`?

```java
if (!prefs.contains("osmdroid.basePath")) {
    //this is the first time startup. run the discovery bit
    File discoveredBasePath = getOsmdroidBasePath(ctx);
    File discoveredCachePath = getOsmdroidTileCache(ctx);
    if (!discoveredBasePath.exists() || !StorageUtils.isWritable(discoveredBasePath)) {
        //this should always be writable...
        discoveredBasePath = new File(ctx.getFilesDir(), "osmdroid");
        discoveredCachePath = new File(discoveredBasePath, "tiles");
        discoveredCachePath.mkdirs();
    }
    // ...
```

**Comment by iSergioMejia** [comment]
Hello! I don't know if this will work for all of you but I got the same error, and in the end was because I didn't call the `setContentView(...)` function in the `OnCreate` of my activity. Apparently there's a connection between these two things. I hope it works for any of you.

**Comment by wuan** [comment]
Same here. `StorageUtils.getBestWritableStorage(context)` returns `null` for `context == null` in `getOsmdroidBasePath(Context context)`.

For me it works to inject the current context into the call with a minimal config provider inheriting from `DefaultConfigurationProvider`:

```
class MapConfigurationProvider(private val context: Context) : DefaultConfigurationProvider() {
    override fun getOsmdroidBasePath(): File {
        return super.getOsmdroidBasePath(context)
    }
}
```

This is enabled by calling
```
Configuration.setConfigurationProvider(MapConfigurationProvider(this.applicationContext))
```
before initializing Osmdroid.

**Comment by longGr** [comment]
Had this issue on version 6.1.8. A quick fix for me was to use osm version  6.1.4:

    implementation 'org.osmdroid:osmdroid-android:6.1.4'

**Comment by PatrickKuijpers** [comment]
> Had this issue on version 6.1.8. A quick fix for me was to use osm version 6.1.4:
> 
> ```
> implementation 'org.osmdroid:osmdroid-android:6.1.4'
> ```

The issue appeared in version 6.1.7.
I've downgraded to 6.1.6 instead, which contains quite some bugfixes.

Let's hope there'll be a fix soon.
Or at least update the "Hello osmdroid world" [docs](https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library#manifest) so new users won't encounter these annoying issues right off the bat!
Either add some quickfix code with clear comments, or at least add a clear note in the description referring to this issue.

**Comment by NathanFallet** [comment]
Issue is still occurring now

**Comment by spyhunter99** [comment]
hmm since i can't reproduce this, can someone try the following?

at the end of the method
```
 public File getOsmdroidBasePath(Context context) {
```

put this at the end
```
if (osmdroidBasePath==null)
            osmdroidBasePath =  context.getFilesDir();
        return osmdroidBasePath;
```

instead of just `return osmdroidBasePath;`

this 'might' fix this issue for this specific edge case
