### ISSUE TITLE
Don't require ACCESS_NETWORK_STATE permission.

### ISSUE THREAD

**Issue by schildbach** [osmdroid/osmdroid#165]
After quickly migrating my app from GMv1 to osmdroid, I discovered osmdroid requires a new permission. I think this should be optional. The old API didn't require this so osmdroid should not, too.

```
E/MapTileDownloader(27496): java.lang.SecurityException: ConnectivityService: Neither user 10110 nor current process has android.permission.ACCESS_NETWORK_STATE.
E/MapTileDownloader(27496): 	at android.os.Parcel.readException(Parcel.java:1546) ~[na:0.0]
E/MapTileDownloader(27496): 	at android.os.Parcel.readException(Parcel.java:1499) ~[na:0.0]
E/MapTileDownloader(27496): 	at android.net.IConnectivityManager$Stub$Proxy.getActiveNetworkInfo(IConnectivityManager.java:945) ~[na:0.0]
E/MapTileDownloader(27496): 	at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:598) ~[na:0.0]
E/MapTileDownloader(27496): 	at org.osmdroid.tileprovider.modules.NetworkAvailabliltyCheck.getNetworkAvailable(NetworkAvailabliltyCheck.java:27) ~[na:0.0]
E/MapTileDownloader(27496): 	at org.osmdroid.tileprovider.modules.MapTileDownloader$TileLoader.loadTile(MapTileDownloader.java:166) ~[na:0.0]
E/MapTileDownloader(27496): 	at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:293) ~[na:0.0]
E/MapTileDownloader(27496): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) ~[na:0.0]
E/MapTileDownloader(27496): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) ~[na:0.0]
E/MapTileDownloader(27496): 	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
```

**Comment by spyhunter99** [comment]
Sorry, I don't think this will be fixed. OSMdroid has a few additional checks for network connectivity before attempting map tile downloads. This behavior can be overridden if you provide your own implementation of INetworkAvailablityCheck.

**Comment by neilboyd** [comment]
@spyhunter99 I think that's a bit harsh ;)  This could be fixed with a check for the permission.  I suppose it should assume network **is** available when no permission.

And this issue should apply equally to ACCESS_WIFI_STATE.
