### ISSUE TITLE
Osmdroid cache location becomes not readable on upgrade to Android 11

### ISSUE THREAD

**Issue by jpmeijers** [osmdroid/osmdroid#1678]
## Issue Type

[ ] Question
[x] Bug
[x] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

In the documentation at https://osmdroid.github.io/osmdroid/Important-notes-on-using-osmdroid-in-your-app.html I read the following about the cache location:

> Handling Cache Storage
> 
> osmdroid does not work without somewhere to cache the tiles. The first time starting an application using osmdroid will scan for all available, writable mount points on the device. It auto selects the largest mount point. This, of course can be changed via the IConfigurationProvider. If that mount point suddenly becomes read only or disappears, osmdroid will not handle this scenario. Instead, users will get the familiar gray grid with no map tiles being displayed (uh oh). To overcome this, applications using osmdroid should probably check on startup to see what the selected cache location is via ConfigurationProvider.getOsmdroidTileCache() source then by checking StorageUtils.isWritable. If it is writable, no further action is required. Otherwise, you should probably prompt the user or autoselect the next best location.

A user of my app has recently upgraded from Android 10 to Android 11. After the upgrade my app does not load the map tiles, and the following is shown in logcat:

```
01-10 19:37:11.902 14023 14056 E SQLiteLog: (14) os_unix.c:38589: (13) open(/storage/emulated/0/osmdroid/tiles/cache.db) - 
01-10 19:37:11.908 14023 14056 E SQLiteDatabase: Failed to open database '/storage/emulated/0/osmdroid/tiles/cache.db'.
01-10 19:37:11.908 14023 14056 E SQLiteDatabase: android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/storage/emulated/0/osmdroid/tiles/cache.db': File /storage/emulated/0/osmdroid/tiles/cache.db is not readable
01-10 19:37:11.908 14023 14056 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:252)
...
01-10 19:37:11.909 14023 14056 E OsmDroid: Unable to start the sqlite tile writer. Check external storage availability.
01-10 19:37:11.909 14023 14056 E OsmDroid: android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/storage/emulated/0/osmdroid/tiles/cache.db': File /storage/emulated/0/osmdroid/tiles/cache.db is not readable
01-10 19:37:11.909 14023 14056 E OsmDroid: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:252)
...
```

A simple cache clear and files clear and even a reinstall of the same version of the app does not work.

The only thing that solved the issue was to downgrade the version to an older version that did have Android 11 support.

After this the logcat output looks like this:

```
01-10 21:52:10.646  9528  9528 I StorageUtils: /data/user/0/org.ttnmapper.phonesurveyor/files is writable
01-10 21:52:10.649  9528  9528 I StorageUtils: /storage/emulated/0/Android/data/<REDACTED>/files is writable
01-10 21:52:10.649  9528  9528 I StorageUtils: /data/user/0/<REDACTED>/files is writable
01-10 21:52:10.649  9528  9528 I StorageUtils: /storage/emulated/0/Android/data/<REDACTED>/files is writable

01-10 21:52:10.659  9528  9528 I OsmDroid: Tile cache increased from 0 to 9

01-10 21:52:10.668  9528  9528 I OsmDroid: Using tile source: Mapnik
01-10 21:52:10.668  9528  9528 I OsmDroid: Tile cache increased from 0 to 9
```

What I believe happens here is the following:
* Android 10, app is installed
* At first run osmdroid scans for writable locations, finds `/storage/emulated/0/` to be writable and chooses it for the cache location
* Cache location is remembered by storing it in SharedPreferences (or I hope so)
* Android updates to 11
* App starts up and gets the cache location from SharedPreferences
* Cache location is not accessible anymore under Android 11, we get the error, and tiles do not load
*  A downgrade of the app forces a shared preferences clear, which a cache clear, file clear and reinstall did not
* Downgraded version of the app on Android 11 finds a new readable and writable location for the cache

Unfortunately I have to speculate as I do not have a way to downgrade and upgrade the Android version on a device or emulator.

### Workaround

I hope I can work around this by detecting when the SDK version changes and then clearing the SharedPreferences with code similar to this. That is assuming that osmdroid stores the cache location in SharedPreferences.

```
        // Handle android version upgrades
        val currentApiVersion = Build.VERSION.SDK_INT
        val previousApiVersion = prefs.getInt("apiVersion", 0)

        if(currentApiVersion != previousApiVersion) {
            try {
                val editor = prefs.edit();

                // Before API 30 we need to handle osmdroid's wrong storage location
                if(previousApiVersion < 30) {
                    editor.clear()
                }

                editor.putInt("apiVersion", currentApiVersion)
                editor.apply()
            } catch(e: Exception) {
                Log.e(TAG, "Can't migrate preferences")
                e.printStackTrace()
            }
        }
```

A more elegant solution from osmdroid's side would be great. Is there perhaps something opposite of `ConfigurationProvider.getOsmdroidTileCache()` that will clear and auto select the next best location? 

### If it's a bug, version(s) of android this affects:

Upgrade from Android 10 to Android 11, aka SDK 29 to SDK 30, aka Android Q to Android R

### Version of osmdroid the issue relates to:

6.1.9-SNAPSHOT

**Comment by spyhunter99** [comment]
it's definitely stored to a shared preference. You can either set your own configuration provider and override the default handling of the tile cache and/or explicitly clear the setting. You could always ask the user where to store the cache too.

**Comment by taiffu** [comment]
This case seems to be now coming issue when devices are upgraded to Android 11.

**Comment by taiffu** [comment]
Question if you this kind of code when initialize OSMDroid it this works also with Android 11 or can there still coming some problems?   

 org.osmdroid.config.IConfigurationProvider osmConf = Configuration.getInstance();
   File basePath = new File( getFilesDir().getAbsolutePath(), "osmdroid" );
   Log.e("MAP", basePath.toString());
   if (!basePath.exists()) {
    basePath.mkdirs();
   }
   osmConf.setOsmdroidBasePath( basePath );
   File tileCache = new File( getFilesDir().getAbsolutePath(), "tile" );
   if (!tileCache.exists()) {
    tileCache.mkdirs();
   }
   Log.e("MAP", tileCache.toString());
   osmConf.setOsmdroidTileCache( tileCache );

**Comment by monsieurtanuki** [comment]
@taiffu I think you're right, I would suggest something like that:
```java
private void suggestedFix(final ContextWrapper contextWrapper) {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.R) {
        return;
    }
    final File root = contextWrapper.getFilesDir();
    final File osmdroidBasePath = new File(root, "osmdroid");
    osmdroidBasePath.mkdirs();
    Configuration.getInstance().setOsmdroidBasePath(osmdroidBasePath);
}
```

To be called very early.
Tell me if it works.

As already evoked, the problem is that you don't keep your tile data history when you upgrade a smartphone to 30.
But the app does not crash ;)

**Comment by taiffu** [comment]
So  far looking good in my own tests. Waiting more information from others.

**Comment by taiffu** [comment]
Yes I can verify this works for us. Thank you :)

**Comment by monsieurtanuki** [comment]
Thank you @taiffu for your tests!

What would be the next step, then?

I guess the default dir (`DefaultConfigurationProvider.getOsmdroidBasePath(Context)`) should be a subfolder of the app dir (`contextWrapper.getFilesDir()`).
Should it be initialized this way
1. only for `Build.VERSION.SDK_INT >= Build.VERSION_CODES.R`
2. or for all versions anyway?

I cannot see the added value to do this only for `R+`.

Anyway the trouble with either solution is that the existing installed apps will still use the old root folder (as stored in the preferences), and new installed apps will use the new root folder.
That means that sometimes there may be (rare) behavior discrepancies between a database stored in one place or the other, as side effects.

@spyhunter99 @pasniak @MKergall @cbalster @InI4 What are your views on the subject?

**Comment by mikebravoyes** [comment]
@monsieurtanuki 
On my "Google Pixel 3" with Android 11 ("R"), I have recently changed my `AndroidManifest.xml` to `targetSdkVersion 30`. The permission `MANAGE_EXTERNAL_STORAGE` has been rejected by Google for the Play Store :-(
So I have to cope with the "Scoped Storage" model. So far, so good.

Now my question: There is a directory `/storage/emulated/0/osmdroid/tiles` containing two files `cache.db` and `cache.db-journal`. However, these files are several weeks old, obviously not in use any more. Even if I rename the directory to e.g. `osmdroid.old`, the map works perfectly anyway. With a file manager, I have been looking for another location of `osmdroid`, `tiles` or `cache.db`, without success. So where the hell is the tile cache?

**Comment by monsieurtanuki** [comment]
@mikebravoyes I don't know where the tile cache is but if you're looking for your car keys they're in the kitchen close to the kettle :)

From what I read [in the code](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/config/DefaultConfigurationProvider.java#L321) the tile cache location is "optimized" at the very first init time - the best file location is computed according to different criteria like read/write access or available space. When there's no available "external" file location with read/write access, it defaults to the app dir + `"/osmdroid/"`.
Then this path is stored in preferences. And the next time you ask for the tile folder, you'll get the result from the preferences, it won't be computed again.

It looks like what you're looking for is the app dir, therefore not accessible from outside the app. The path is stored in the preferences under the `"osmdroid.basePath"` label anyway.

**Comment by LostRat** [comment]
With Scoped Storage your app must access everything from within your own
private storage. I just spent a week plus trying to figure out a substitute
to accessing files directly from the shared Download folder.

I must first copy downloaded files to private storage. For my app:

*/data/*user/0/com.pdxzone.pdxwalk/app_Tracks/OthersTracks

General SD Card access limitations are the same as for shared Download
folder.

My downloads of MBTiles files go here:

[internal]
/storage/emulated/0/Android/data//com.pdxzone.pdxwalk/files/Download

[SD Card] /storage/0403-0201/Android/data/com.pdxzone.pdxwalk/files/Download

I use no cache, only my own MBTiles files. OSMDroid cache path must include
app id, similar to above.

All of it gets erased if user uninstalls app.

**Comment by jpmeijers** [comment]
I just received a bug report from a Pixel 6 users that the maps aren't showing. The logcat output indicates that the storage location is not found. This is on Android 12.

Manufacturer: Google
Board: oriole
Display: SD1A.210817.036
MODEL: Pixel 6
BRAND: google
HOST: abfarm-release-rbe-64-00002
BASE_OS: 
PREVIEW_SDK_INT: 0
SECURITY_PATCH: 2021-11-05
RELEASE_OR_CODENAME: 12
CODENAME: REL
INCREMENTAL: 7805805
RELEASE: 12
SDK_INT: 31

```
12-07 16:09:03.455 10199 10260 E OsmDroid: Error loading tile
12-07 16:09:03.455 10199 10260 E OsmDroid: java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.Cursor android.database.sqlite.SQLiteDatabase.query(java.lang.String, java.lang.String[], java.lang.String, java.lang.String[], java.lang.String, java.lang.String, java.lang.String)' on a null object reference
12-07 16:09:03.455 10199 10260 E OsmDroid: 	at org.osmdroid.tileprovider.modules.SqlTileWriter.getTileCursor(SqlTileWriter.java:590)
12-07 16:09:03.455 10199 10260 E OsmDroid: 	at org.osmdroid.tileprovider.modules.SqlTileWriter.loadTile(SqlTileWriter.java:612)
12-07 16:09:03.455 10199 10260 E OsmDroid: 	at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:163)
12-07 16:09:03.455 10199 10260 E OsmDroid: 	at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.loadTileIfReachable(MapTileModuleProviderBase.java:214)
12-07 16:09:03.455 10199 10260 E OsmDroid: 	at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:185)
12-07 16:09:03.455 10199 10260 E OsmDroid: 	at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:151)
12-07 16:09:03.455 10199 10260 E OsmDroid: 	at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:133)
12-07 16:09:03.455 10199 10260 E OsmDroid: 	at org.osmdroid.tileprovider.modules.MapTileApproximater$TileLoader.loadTile(MapTileApproximater.java:114)
12-07 16:09:03.455 10199 10260 E OsmDroid: 	at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.loadTileIfReachable(MapTileModuleProviderBase.java:214)
12-07 16:09:03.455 10199 10260 E OsmDroid: 	at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:332)
12-07 16:09:03.455 10199 10260 E OsmDroid: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-07 16:09:03.455 10199 10260 E OsmDroid: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-07 16:09:03.455 10199 10260 E OsmDroid: 	at java.lang.Thread.run(Thread.java:920)
12-07 16:09:03.457 10199 10199 D org.ttnmapper.phonesurveyor.ui.MapFragment: onDestroyView
12-07 16:09:03.459 10199 10254 E SQLiteLog: (14) cannot open file at line 39583 of [bcd014c473]
12-07 16:09:03.460 10199 10254 E SQLiteLog: (14) os_unix.c:39583: (2) open(/storage/6261-6530/Android/data/org.ttnmapper.phonesurveyor/files/osmdroid/tiles/cache.db) - 
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: Failed to open database '/storage/6261-6530/Android/data/org.ttnmapper.phonesurveyor/files/osmdroid/tiles/cache.db'.
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/storage/6261-6530/Android/data/org.ttnmapper.phonesurveyor/files/osmdroid/tiles/cache.db': Directory /storage/6261-6530/Android/data/org.ttnmapper.phonesurveyor/files/osmdroid/tiles doesn't exist
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:254)
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205)
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:919)
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:899)
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:790)
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:807)
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:799)
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	at org.osmdroid.tileprovider.modules.SqlTileWriter.getDb(SqlTileWriter.java:740)
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	at org.osmdroid.tileprovider.modules.SqlTileWriter.getTileCursor(SqlTileWriter.java:589)
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	at org.osmdroid.tileprovider.modules.SqlTileWriter.loadTile(SqlTileWriter.java:612)
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:163)
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.loadTileIfReachable(MapTileModuleProviderBase.java:214)
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:185)
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:151)
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:133)
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	at org.osmdroid.tileprovider.modules.MapTileApproximater$TileLoader.loadTile(MapTileApproximater.java:114)
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.loadTileIfReachable(MapTileModuleProviderBase.java:214)
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:332)
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	at java.lang.Thread.run(Thread.java:920)
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:224)
12-07 16:09:03.461 10199 10254 E SQLiteDatabase: 	... 23 more
12-07 16:09:03.461 10199 10254 E OsmDroid: Unable to start the sqlite tile writer. Check external storage availability.
12-07 16:09:03.461 10199 10254 E OsmDroid: android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/storage/6261-6530/Android/data/org.ttnmapper.phonesurveyor/files/osmdroid/tiles/cache.db': Directory /storage/6261-6530/Android/data/org.ttnmapper.phonesurveyor/files/osmdroid/tiles doesn't exist
12-07 16:09:03.461 10199 10254 E OsmDroid: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:254)
12-07 16:09:03.461 10199 10254 E OsmDroid: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205)
12-07 16:09:03.461 10199 10254 E OsmDroid: 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
12-07 16:09:03.461 10199 10254 E OsmDroid: 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
12-07 16:09:03.461 10199 10254 E OsmDroid: 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
12-07 16:09:03.461 10199 10254 E OsmDroid: 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:919)
12-07 16:09:03.461 10199 10254 E OsmDroid: 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:899)
12-07 16:09:03.461 10199 10254 E OsmDroid: 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:790)
12-07 16:09:03.461 10199 10254 E OsmDroid: 	at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:807)
12-07 16:09:03.461 10199 10254 E OsmDroid: 	at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:799)
12-07 16:09:03.461 10199 10254 E OsmDroid: 	at org.osmdroid.tileprovider.modules.SqlTileWriter.getDb(SqlTileWriter.java:740)
12-07 16:09:03.461 10199 10254 E OsmDroid: 	at org.osmdroid.tileprovider.modules.SqlTileWriter.getTileCursor(SqlTileWriter.java:589)
12-07 16:09:03.461 10199 10254 E OsmDroid: 	at org.osmdroid.tileprovider.modules.SqlTileWriter.loadTile(SqlTileWriter.java:612)
12-07 16:09:03.461 10199 10254 E OsmDroid: 	at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:163)
12-07 16:09:03.461 10199 10254 E OsmDroid: 	at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.loadTileIfReachable(MapTileModuleProviderBase.java:214)
12-07 16:09:03.461 10199 10254 E OsmDroid: 	at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:185)
12-07 16:09:03.461 10199 10254 E OsmDroid: 	at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:151)
12-07 16:09:03.461 10199 10254 E OsmDroid: 	at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:133)
12-07 16:09:03.461 10199 10254 E OsmDroid: 	at org.osmdroid.tileprovider.modules.MapTileApproximater$TileLoader.loadTile(MapTileApproximater.java:114)
12-07 16:09:03.461 10199 10254 E OsmDroid: 	at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.loadTileIfReachable(MapTileModuleProviderBase.java:214)
12-07 16:09:03.461 10199 10254 E OsmDroid: 	at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:332)
12-07 16:09:03.461 10199 10254 E OsmDroid: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-07 16:09:03.461 10199 10254 E OsmDroid: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-07 16:09:03.461 10199 10254 E OsmDroid: 	at java.lang.Thread.run(Thread.java:920)
12-07 16:09:03.461 10199 10254 E OsmDroid: Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
12-07 16:09:03.461 10199 10254 E OsmDroid: 	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
12-07 16:09:03.461 10199 10254 E OsmDroid: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:224)
12-07 16:09:03.461 10199 10254 E OsmDroid: 	... 23 more
```

This error occurs even when using this code:
```
        if(currentApiVersion != previousApiVersion) {
            // API 29 had a transitional storage system. Clear prefs so that we are sure to use the new system.
            if(currentApiVersion == 29 && previousApiVersion < 29) {
                Log.e(TAG, "Android SDK version changed to 29. Clearing all preferences.")
                editor.clear()
            }

            // Before API 30 we need to handle osmdroid's wrong storage location
            if(currentApiVersion == 30 && previousApiVersion < 30) {
                Log.e(TAG, "Android SDK version changed to 30. Clearing all preferences.")
                editor.clear()
            }
        }
```

I'm still debugging this, but it looks like SDK 31 requires one to clear preferences too.

**Comment by LostRat** [comment]
This reference is already in your private storage.

"Failed to open database
'/storage/6261-6530/Android/data/org.ttnmapper.phonesurveyor/files/osmdroid/tiles/"


To compile under API 31 (in my app, which needs beta testers) I had to
drop WRITE_EXTERNAL_STORAGE and replace it with READ_EXTERNAL_STORAGE.
Android may be enforcing something storage related, possibly look to
the manifest. I have not yet tested on an API 31 device or virtual.
Write permission is automatic in your app's space.

I exclusively use my own MBTiles files. Offline hiking. I previously
accessed them directly from the shared public download folder.

now in []Android/data/com.pdxzone.pdxwalk/files/Download/xxx.mbtiles
(works on internal and on external card)

**Comment by mikebravoyes** [comment]
My smartphone “Google Pixel 3” was delivered with **Android 11 (API 30)**. 

Originally, my app [Sensor Recording](http://www.braun-home.net/michael/android/sensorrecording/index.htm) was compiled with the following settings in `build.gradle`:
```
compileSdkVersion 30
defaultConfig {
    targetSdkVersion 30
    …
}
dependencies {
    implementation group: 'org.osmdroid', name: 'osmdroid-android', version: '6.1.11'
    …
}
```

Some weeks ago, my phone was updated automatically to **Android 12 (API 31)**. Everything continued to work without any problems.

When I changed the `build.gradle` to  
```
compileSdkVersion 31
defaultConfig {
    targetSdkVersion 31
    …
}
```
I got the following error message from the compiler:

_Manifest merger failed : android:exported needs to be explicitly specified for <activity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details._

So I amended the `AndroidManifest.xml` with
```
<activity
   …
   android:exported="true">
```

And everything was fine again. No need to do anything with the osmdroid cache.
I also tested on a tablet "Samsung Galaxy Tab A LTE 10.5" with **Android 10 (API 29)** without any problems.
