### ISSUE TITLE
SQLite Error

### ISSUE THREAD

**Issue by TFreudi1** [osmdroid/osmdroid#1696]
I use osmdroid 6.1.10 and have sometimes an SQLiterror on different mobiles/emulators/androidversions and Osmdroid did'nt show any maptile in this case.
The error:
2021-02-26 18:15:02.309 16246-19369/com.pg.androidmaps.jona_demo W/OsmDroid: Error getting db stream: /10/550/334
    java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /storage/emulated/0/Android/data/com.pg.androidmaps.jona_demo/files/jona.mbtiles
        at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:58)
        at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1905)
        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1781)
        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1949)
        at org.osmdroid.tileprovider.modules.MBTilesFileArchive.getInputStream(MBTilesFileArchive.java:68)
        at org.osmdroid.tileprovider.modules.MapTileFileArchiveProvider.getInputStream(MapTileFileArchiveProvider.java:197)
        at org.osmdroid.tileprovider.modules.MapTileFileArchiveProvider.access$100(MapTileFileArchiveProvider.java:29)
        at org.osmdroid.tileprovider.modules.MapTileFileArchiveProvider$TileLoader.loadTile(MapTileFileArchiveProvider.java:231)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.loadTileIfReachable(MapTileModuleProviderBase.java:214)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:332)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

This i shown in logcat for every tile. I do a mapView.OnResume/OnPause in the lifecycle of the activity.

Any hints on that ?

**Comment by TFreudi1** [comment]
Ok, I know now when that happens. I have menu point "exit" that calls finish(). In that case, when you open the App/Map again the SQLiteError pops up, and no map are shown.

**Comment by TFreudi1** [comment]
Ok, I solve it by myself. As you may saw I use MBTILES Maps, and I did'nt release/misused the underlying Archive Members.
