### ISSUE TITLE
OOMError in GarbageCollector.gc()

### ISSUE THREAD

**Issue by InI4** [osmdroid/osmdroid#1720]
## Issue Type

[ ] Question
[x] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

No steps, found below stack trace in Crashlytics of my app:

> Fatal Exception: java.lang.OutOfMemoryError: Could not allocate JNI Env: Failed anonymous mmap(0x0, 8192, 0x3, 0x22, -1, 0): Out of memory. See process maps in the log.
>        at java.lang.Thread.nativeCreate(Thread.java)
>        at java.lang.Thread.start(Thread.java:887)
>        at org.osmdroid.util.GarbageCollector.gc(GarbageCollector.java:39)
>        at org.osmdroid.tileprovider.MapTilePreCache.fill(MapTilePreCache.java:62)
>        at org.osmdroid.tileprovider.MapTileCache.maintenance(MapTileCache.java:337)
>        at org.osmdroid.views.overlay.TilesOverlay.protectDisplayedTilesForCache(TilesOverlay.java:178)
>        at org.osmdroid.views.overlay.DefaultOverlayManager.onDrawHelper(DefaultOverlayManager.java:158)
>        at org.osmdroid.views.overlay.DefaultOverlayManager.onDraw(DefaultOverlayManager.java:139)
>        at org.osmdroid.views.MapView.dispatchDraw(MapView.java:1241)
>        at android.view.View.updateDisplayListIfDirty(View.java:21380)
> 

Remarks:

- User affected from "no map any more", i.e. like #1512,  #1678 or #1571
- User affected from a not understood and rarely producible issue, that my app suddenly consumes 20 times as much bandwidth.  I do not want to play the blame game, but could this happen to be osmdroid running without external cache?

## Environment

As seen in Crashlytics:

Brand:OnePlus
Model:GM1903
Orientation: Portrait
RAM free: 3.33 GB
Disk free: 206.33 GB
Operating System

Orientation: Portrait
Rooted:No

### If it's a bug, version(s) of android this affects:

As seen in Crashlytics:
Version:11

### Version of osmdroid the issue relates to:

From the built affected:
6.1.10

**Comment by monsieurtanuki** [comment]
@InI4 Might be a problem with [`MapTileProviderBasic`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBasic.java#L112-L116):
```java
// protected-cache-tile computers
getTileCache().getProtectedTileComputers().add(new MapTileAreaZoomComputer(-1));
getTileCache().getProtectedTileComputers().add(new MapTileAreaBorderComputer(1));
getTileCache().setAutoEnsureCapacity(false);
getTileCache().setStressedMemory(false);
```

The more you ask, the more you pre-download, the more memory you use.
Please try without the `MapTileAreaZoomComputer(-1)` and `MapTileAreaBorderComputer(1)` lines.

**Comment by InI4** [comment]
Thx, will check. Sorry to have little time to help you lately!
