### ISSUE TITLE
Map crashes after device rotation (portrait/landscape)

### ISSUE THREAD

**Issue by mikebravoyes** [osmdroid/osmdroid#1721]
## Issue Type

[x] Question
[x] Bug

## Description and/or steps/code to reproduce the problem

@monsieurtanuki 

I have written an app with a map component based on osmdroid (version 6.1.10) and have discovered a bug, which drives me crazy:

**As long as the map centre is fix**, I can rotate the device and thus can flip between portrait and landscape mode as often as I want. **Everything works fine**, see screenshots below.

![Screenshot_20210607-100510](https://user-images.githubusercontent.com/6436590/120992004-7656ad80-c782-11eb-938e-8109dbbc8220.png)

![Screenshot_20210607-100525](https://user-images.githubusercontent.com/6436590/120992148-9d14e400-c782-11eb-96ca-152c218902bc.png)

But there is also an operation mode, where the **map centre follows the current position automatically**. That means: every second, when I get a new GPS position, the map centre is adjusted accordingly.

`mapController.setCenter(geoPosition);`
or (more smoothly)
`mapController.animateTo(geoPosition);`

Now, when I flip the device orientation between portrait and landscape, **the app crashes immediately**. I tried to find the exact line of code, where that happens. The last actions I can see in the log files is the execution of the methods `onPause`, `onStop`, `onDestroy`, `onCreate`, `onStart`, `onResume` and finally `onFirstLayout`.

The last line of `onFirstLayout` is executed correctly, and within the next second, the app crashes at an unknown position in the software. The next `onLocationChanged` is not executed any more. Therefore, I suspect the crash must happen somewhere in the osmdroid library during the rotation of the map.

I tried to figure out what happens since several days now, without success. The debug features of Android studio didn’t help a lot. **Any ideas, how I can track down and fix this bug?** Or is there a proposal for a workaround?

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.10

**Comment by mikebravoyes** [comment]
@monsieurtanuki 

By the way, the effect occurs even without updates of the GPS position. If you scroll the map manually - very quickly, so that it continues to move for 1 or 2 seconds, and then rotate the device, the app crashes as well.

**Comment by mikebravoyes** [comment]
@monsieurtanuki @spyhunter99 

I was able to generate a stack trace for the crash:

```
2021-06-08 16:11:04.540 13099-13099/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.braun_home.sensorrecording.pro, PID: 13099
    java.lang.NullPointerException: Attempt to invoke virtual method 'org.osmdroid.views.MapViewRepository org.osmdroid.views.MapView.getRepository()' on a null object reference
        at org.osmdroid.views.overlay.infowindow.InfoWindow.<init>(InfoWindow.java:53)
        at org.osmdroid.views.overlay.infowindow.BasicInfoWindow.<init>(BasicInfoWindow.java:54)
        at org.osmdroid.views.overlay.infowindow.MarkerInfoWindow.<init>(MarkerInfoWindow.java:42)
        at org.osmdroid.views.MapViewRepository.getDefaultMarkerInfoWindow(MapViewRepository.java:54)
        at org.osmdroid.views.overlay.Marker.<init>(Marker.java:116)
        at org.osmdroid.views.overlay.Marker.<init>(Marker.java:93)
        at net.braun_home.sensorrecording.Act06_Chart.showSymbol(Act06_Chart.java:2706)
        at net.braun_home.sensorrecording.Act06_Chart.showCrossHair(Act06_Chart.java:1896)
        at net.braun_home.sensorrecording.Act06_Chart.showAddressText(Act06_Chart.java:1868)
        at net.braun_home.sensorrecording.Act06_Chart.access$3900(Act06_Chart.java:124)
        at net.braun_home.sensorrecording.Act06_Chart$12.onScroll(Act06_Chart.java:2091)
        at org.osmdroid.events.DelayedMapListener$CallbackTask.run(DelayedMapListener.java:88)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
As you can see, it’s a **NullPointerException** in the middle of the osmdroid library, caused by this simple statement at _Act06_Chart.showSymbol(Act06_Chart.java:2706)_:

`Marker marker = new Marker(mapView);`

This statement is called in turn by this method at _Act06_Chart$12.onScroll(Act06_Chart.java:2091)_:

```
/** Fire if there is no zoom/scroll for more than 200 millisecs */
final int DEFAULT_INACTIVITY_DELAY_IN_MILLISECS = 200;
mapView.setMapListener(new DelayedMapListener(new MapListener()
{
    @Override
    public boolean onScroll(ScrollEvent arg0)
    {
        // update map
        showAddressText();

        // do something more...
        // ...

        return false;
    }  // onScroll

    @Override
    public boolean onZoom(ZoomEvent event)
    {
        // do nothing

        return false;
    }  // onZoom
}, DEFAULT_INACTIVITY_DELAY_IN_MILLISECS));
```

That means, 200 ms after the map is scrolled out, the map update is invoked. The statement `new Marker(mapView)` is called from other code pieces several dozen times per second, which is normally no problem – except after a device rotation (portrait/landscape) while the map is scrolling. After a device rotation (onDestroy, onCreate, …), the map is initialized again:

`mapView = findViewById(R.id.mapview);`

So, after the rotation, we have a fresh mapView – including all overlays. Why does this crash happen at _org.osmdroid.views.overlay.infowindow.InfoWindow.<init>(InfoWindow.java:53)_?

**Comment by mikebravoyes** [comment]
@monsieurtanuki @spyhunter99 

I couldn't figure out, why the _NullPointerException_ occurs in _InfoWindow.java:53_
`mMapView.getRepository().add(this);
`

But I can handle that with `try/catch`:

```
Marker marker = null;
try
{
    marker = new Marker(mapView);    // sometimes crash after device rotation
} catch (Exception e)
{
    e.printStackTrace();
}
```
Of course, then I have no marker for this time, but in the next run (with the next GPS position 1 second later), this will be fixed.

Might be interesting to investigate the crash in more detail, but I don't have the deeper insight in the osmdroid library.

**Comment by spyhunter99** [comment]
i think infowindow has context to it, a reference to the mapview. that's probably related. Sometimes you have class member variables of Marker or anything else that needs context, it can cause issues, or static references to marker or infowindow based items

**Comment by spyhunter99** [comment]
i think infowindow has context to it, a reference to the mapview. that's probably related. Sometimes you have class member variables of Marker or anything else that needs context, it can cause issues, or static references to marker or infowindow based items
