### ISSUE TITLE
osmdroid with over 4GB offline map zip question/concern

### ISSUE THREAD

**Issue by ariscruz** [osmdroid/osmdroid#1728]
## Issue Type

[ #] Question

## Description and/or steps/code to reproduce the problem

What is the maximum zip archive size osmdroid supports? Currently I have an offline map that is over 4 GB (4.23 GB to be exact) in size stored in external microsdcard, read by my app. The behavior is different between 2 Android OS version that I'm testing in

1. On Galaxy S10+ running Android 11, everything works fine. Same app, same microsdcard and the offline map with the tiles are loaded properly;
2. However, on Galaxy Tab A7 2016 running Android 5.1.1, I'm encountering the ff exceptions

> E/OsmDroid: Error opening archive file /storage/extSdCard/osmdroid/Mapnik.zip
    java.util.zip.ZipException: Central Directory Entry signature not found; was 51C6B4CB
        at java.util.zip.ZipFile.throwZipException(ZipFile.java:451)
        at java.util.zip.ZipEntry.<init>(ZipEntry.java:389)
        at java.util.zip.ZipFile.readCentralDir(ZipFile.java:438)
        at java.util.zip.ZipFile.<init>(ZipFile.java:163)
        at java.util.zip.ZipFile.<init>(ZipFile.java:119)
        at org.osmdroid.tileprovider.modules.ZipFileArchive.init(ZipFileArchive.java:43)
        at org.osmdroid.tileprovider.modules.ArchiveFileFactory.getArchiveFile(ArchiveFileFactory.java:65)
        at org.osmdroid.tileprovider.modules.MapTileFileArchiveProvider.findArchiveFiles(MapTileFileArchiveProvider.java:182)
        at org.osmdroid.tileprovider.modules.MapTileFileArchiveProvider.<init>(MapTileFileArchiveProvider.java:80)
        at org.osmdroid.tileprovider.modules.MapTileFileArchiveProvider.<init>(MapTileFileArchiveProvider.java:58)
        at org.osmdroid.tileprovider.modules.MapTileFileArchiveProvider.<init>(MapTileFileArchiveProvider.java:92)
        at org.osmdroid.tileprovider.MapTileProviderBasic.<init>(MapTileProviderBasic.java:100)
        at org.osmdroid.tileprovider.MapTileProviderBasic.<init>(MapTileProviderBasic.java:70)
        at org.osmdroid.tileprovider.MapTileProviderBasic.<init>(MapTileProviderBasic.java:63)
        at org.osmdroid.views.MapView.<init>(MapView.java:220)
        at org.osmdroid.views.MapView.<init>(MapView.java:193)
        at org.osmdroid.views.MapView.<init>(MapView.java:255)
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at android.view.LayoutInflater.createView(LayoutInflater.java:614)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
        at 

Note that my app already has the necessary WRITE_EXTERNAL_STORAGE and READ_EXTERNAL_STORAGE permissions. 
Initially, I thought the zip file is corrupted but realized this wasn't the case because it was loading fine on Galaxy S10+, even when clearing the cache files. 
Any ideas? Is this Android 5.1.1 limitation/restriction or on osmdroid itself? Thanks for your help, it will be very much appreciated.

## Environment
Android 11, Android 5.1.1

### Version of osmdroid the issue relates to:

6.1.0

**Comment by spyhunter99** [comment]
Iirc max zip is 65k entries on most versions of Android. Maybe newer
versions have a high limit

**Comment by ariscruz** [comment]
Thanks. If that's the case, would it be possible to split the offline map data into multiple, smaller zip files packaged inside in 1 big zip file? Does osmdroid perhaps support it?

**Comment by spyhunter99** [comment]
you can split the zip and just have multiple zip files in the same directory. One zip with multiple zip inside it is not supported. Recommendation is to use sqlite, it's way faster
