### ISSUE TITLE
File access and Android 11+

### ISSUE THREAD

**Issue by MKergall** [osmdroid/osmdroid#1743]
From Android 11, Google introduced [drastical constraints on file access](https://developer.android.com/about/versions/11/privacy/storage). 
In short, an app cannot access any file, except files located in its "private" directory, directory which is not accessible to other apps, including File Explorers. 
And you cannot publish an app on Google Play anymore, if the app is not targeting Android 11. 

This raises various issues for apps using osmdroid features. 

1) Good news: If you let osmdroid define its default cache directory, it will target the app "private" directory => usual file read/write is allowed, online tile sources will work fine. 

2) Bad news: 
[Offline tiles](https://github.com/osmdroid/osmdroid/wiki/Offline-Map-Tiles): outside the app (using File Explorer), you cannot drop files in this cache directory. 
[MapsForge maps](https://github.com/osmdroid/osmdroid/wiki/Mapsforge): outside the app (using File Explorer), you cannot put MapsForge files in a directory than could be read by the app. 
[Geopackage maps](https://github.com/osmdroid/osmdroid/wiki/Geopackage-Support): same issue. 

Workaround: you could request [MANAGE_EXTERNAL_STORAGE ](https://developer.android.com/training/data-storage/manage-all-files) permission. But again, when publishing your app on Google Play, you can anticipate that it will never be approved (trust me, I tried...). 

The "good" direction defined by Google for file access is based on [SAF framework](https://developer.android.com/training/data-storage/shared/documents-files): forget java.io.File class... 

I think this subject needs investigations and suggestions for solutions. 

## Issue Type
[X] Bug / Improvement

### If it's a bug, version(s) of android this affects:
Android 11+ (API Level 30 and above)

### Version of osmdroid the issue relates to:
At least up to 6.1.11

**Comment by spyhunter99** [comment]
for starters, we can make a new config manager class (or adjust the existing one) that handles api 30+ and only looks in app private storage, bypassing the storage utils class. This should resolve a lot of issues people are having with the current setup.

**Comment by MKergall** [comment]
For starters, I think the system already in place (osmdroid locating its cache directory in the app private storage) is the good solution. 

The issue is much more for advanced users, wanting to manage the all kinds of offline content supported by osmdroid (huge work behind that!): 
- Be able to build a MOBAC or MBTiles file on a PC and use it. 
- Be able to download a MapsForge file on Internet and use it. To customize its rendertheme.xml file, and use it. 
Using the private app storage is not possible, as it is accessible to nothing else than the app.

**Comment by monsieurtanuki** [comment]
> The issue is much more for advanced users, wanting to manage the all kinds of offline content supported by osmdroid

Unless you copy the file in the app private storage. Is it possible under the new rules to have to end-user select a file wherever and read it? (in order to copy it)
That means that at some time you'll have 2 copies of the same file.

**Comment by MKergall** [comment]
My understanding of the new rules: 
- using usual "java.io.File" methods (as done in most osmdroid code), the app cannot read outside its private storage
- the end user cannot read/write (using a File Explorer, or any other app) in the app private storage

**Comment by monsieurtanuki** [comment]
I guess we must slalom around each details: there's no way the new rules would prevent an end-user to select a picture in the Gallery and save it in the app private storage.
If we replace "a picture" with "a map file", we should be OK, shouldn't we?

**Comment by MKergall** [comment]
Unfortunately, there is not way for a user to select a picture in the Gallery and save it in the app private storage... 
Yes, we have a real problem.

**Comment by monsieurtanuki** [comment]
Really? How do you add your profile pic to an app like whatsapp?
I'll try that in an app of mine.

**Comment by MKergall** [comment]
Whatsapp is certainly using the [SAF framework](https://developer.android.com/training/data-storage/shared/documents-files), which exists since Android 4.4. 
And this is likely the move we have to handle for osmdroid features based on "public" files.

**Comment by monsieurtanuki** [comment]
> Because the user is involved in selecting the files or directories that your app can access, this mechanism doesn't require any system permissions

That's what I had in mind: the end-user selecting the file. That looks OK for the read part, doesn't it?

**Comment by MKergall** [comment]
Yes, as long as you replace **everything** based on java.io.File by something based on InputStream. 
Not impossible (I did it for the KML save/load features in OSMNavigator). 
But at osmdroid scale, not a 1h work. 
And I anticipate some issues on missing APIs: Managing of ZIP files for instance. Or MapsForge external lib.

**Comment by monsieurtanuki** [comment]
I meant to say that it was possible, not quickly done.
And I don't share your worries regarding missing APIs, as my assumption is that we just have to call the file picker and copy the map file. Then, once the map file is in the app private storage, it's business as usual and there's nothing to change.

I understood that if you invoke the file picker, as the end-user is involved, you're in a grace period long enough to copy the file. But you cannot reuse the file path later for instance.

Disclaimer: I have only an old Lollipop smartphone, and I only care about "standard" files like pictures and MP3. But my tests with API30 on emulators are OK (so far).

**Comment by MKergall** [comment]
That's a way. Drawbacks: 
- offline map files are big
- how the user will be able to manage this private app storage (list files, delete files)? Reimplement a "file explorer" ?...
- this approach will need explanations to the user. 
 
A point: osmdroid method to choose its cache directory do not warranty the same place at each launch. The offline files may be copied to a directory which will not be used later. 

I was more in favor of a real move to SAF. 
Then, let the user select his "working directory", via ACTION_OPEN_DOCUMENT_TREE. 

Note that the app can reuse later a file which has been authorized once. With additional complications after a reboot. 
See https://developer.android.com/training/data-storage/shared/documents-files#persist-permissions

**Comment by MKergall** [comment]
Mapsforge team already worked on supporting SAF: https://github.com/mapsforge/mapsforge/pull/1186

**Comment by monsieurtanuki** [comment]
@MKergall Fair enough. Actually I don't use offline maps; I was just reacting to your rather alarming OP.
In my apps I just need to copy, in the app private storage, files (music and pics) that the end-user explicitly selected.
And I wanted to share "my" solution. Which is probably not appropriate for larger files, files likely to be refreshed, or a large number of files.

> A point: osmdroid method to choose its cache directory do not warranty the same place at each launch. The offline files may be copied to a directory which will not be used later.

I'm not sure it's correct: maybe the very first time, but then the path is stored in the preferences and is reused the next time. To be checked.

**Comment by MKergall** [comment]
> I'm not sure it's correct: maybe the very first time, but then the path is stored in the preferences and is reused the next time. To be checked.

I just checked: no storage of the path in preferences.

**Comment by monsieurtanuki** [comment]
@MKergall Maybe we're talking about different things, but this is what I see in https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/config/DefaultConfigurationProvider.java#L328:
```java
if (!prefs.contains("osmdroid.basePath")) {
     //this is the first time startup. run the discovery bit
     File discoveredBasePath = getOsmdroidBasePath(ctx);
// ...
 } else {
     //normal startup, load user preferences and populate the config object
     setOsmdroidBasePath(new File(prefs.getString("osmdroid.basePath", getOsmdroidBasePath(ctx).getAbsolutePath())));
```

**Comment by MKergall** [comment]
Oh, OK, thanks. I never noticed the introduction of this Configuration.getInstance().load method, so I wasn't calling it.

**Comment by eclectice** [comment]
I am trying to solve this issue on my own with a third-party [SimpleStorage](https://github.com/anggrayudi/SimpleStorage)

**Comment by eclectice** [comment]
I discover [this article](https://commonsware.com/blog/2020/02/15/scoped-storage-stories-undocumented-documents.html) by @commonsware on undocumented Documents support in MediaStore and test the following codes in Android 11 device:


```java

Stream<String> baseTree = Arrays.asList(Constants.APP_NAME, "maps").stream();
String basePathTree = baseTree.collect(Collectors.joining(File.separator));
LOG.log(Level.INFO, "OSM GPKG basePathTree: " + basePathTree);

Stream<String> docTree = Arrays.asList(PublicDirectory.DOCUMENTS.getFolderName(), basePathTree).stream();
String docPathTree = docTree.collect(Collectors.joining(File.separator));
LOG.log(Level.INFO, "OSM GPKG docPathTree: " + docPathTree);

//setupSimpleStorage(savedInstanceState);
//Assume the default Android public Documents folder at "/storage/emulated/0/Documents"
//set OSMDroid default folder at "/storage/emulated/0/Documents/APP/maps"
Stream<String> mapTree = Arrays.asList(SimpleStorage.getExternalStoragePath(), docPathTree).stream();
String mapPathTree = mapTree.collect(Collectors.joining(File.separator));
LOG.log(Level.INFO, "OSM GPKG mapPathTree: " + mapPathTree);

LOG.log(Level.INFO, "OSM GPKG mapPathTree DocumentFileCompat.doesExist(mapPathTree): " + DocumentFileCompat.doesExist(MainApp.context(), mapPathTree));

if (Build.VERSION.SDK_INT >=29 )
{
	String filename = "test.txt";
	ContentValues contentValues = new ContentValues();
	contentValues.put(MediaStore.Files.FileColumns.DISPLAY_NAME, filename);
	contentValues.put(MediaStore.Files.FileColumns.MIME_TYPE, MimeType.TEXT);
	contentValues.put(MediaStore.Files.FileColumns.DATE_ADDED, System.currentTimeMillis()/1000);
	contentValues.put(MediaStore.Files.FileColumns.DATE_MODIFIED, System.currentTimeMillis()/1000);
	contentValues.put(MediaStore.Files.FileColumns.RELATIVE_PATH, docPathTree); // "Documents/APP/maps"
	contentValues.put(MediaStore.Files.FileColumns.IS_PENDING, true);

	Uri uri = getContext().getContentResolver().insert(MediaStore.Files.getContentUri("external"), contentValues);
	if (uri != null) {
		LOG.log(Level.INFO, "OSM GPKG MediaStore uri: " + uri);
		try {
			OutputStream out = getContext().getContentResolver().openOutputStream(uri);
			out.write("Hello\n".getBytes(StandardCharsets.UTF_8));
			out.close();
			LOG.log(Level.INFO, "OSM GPKG MediaStore written into: " + uri);
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}

		//let's verify the file exists and get its properties!
		//do note that it is not a raw file!
		DocumentFile testFile = DocumentFileCompat.fromUri(MainApp.context(), uri);
		if (testFile != null) {
			LOG.log(Level.INFO, "OSM GPKG testFile.getUri(): " + testFile.getUri());
			LOG.log(Level.INFO, "OSM GPKG testFile.exists(): " + testFile.exists());
			LOG.log(Level.INFO, "OSM GPKG testFile.isDirectory(): " + testFile.isDirectory());
			LOG.log(Level.INFO, "OSM GPKG testFile.isFile(): " + testFile.isFile());
			LOG.log(Level.INFO, "OSM GPKG testFile.getParentFile(): " + testFile.getParentFile());
			LOG.log(Level.INFO, "OSM GPKG testFile.canRead(): " + testFile.canRead());
			LOG.log(Level.INFO, "OSM GPKG testFile.canWrite(): " + testFile.canWrite());
		}
	}
	contentValues.clear();
	contentValues.put(MediaStore.Files.FileColumns.IS_PENDING, 0);
	getContext().getContentResolver().update(uri, contentValues, null, null);

	if (uri != null) {
		//let's open this file as raw file instead by using the actual raw file path
		Stream<String> fileTree = Arrays.asList(mapPathTree, filename).stream();
		String filePathTree = fileTree.collect(Collectors.joining(File.separator));
		LOG.log(Level.INFO, "OSM GPKG filePathTree: " + filePathTree);

		LOG.log(Level.INFO, "OSM GPKG filePathTree DocumentFileCompat.doesExist(fileTree): " + DocumentFileCompat.doesExist(MainApp.context(), filePathTree));

		DocumentFile rawFile = DocumentFileCompat.fromFullPath(MainApp.context(), filePathTree);
		if (rawFile != null) {
			LOG.log(Level.INFO, "OSM GPKG rawFile.getUri(): " + rawFile.getUri());
			LOG.log(Level.INFO, "OSM GPKG rawFile.exists(): " + rawFile.exists());
			LOG.log(Level.INFO, "OSM GPKG rawFile.isDirectory(): " + rawFile.isDirectory());
			LOG.log(Level.INFO, "OSM GPKG rawFile.isFile(): " + rawFile.isFile());
			LOG.log(Level.INFO, "OSM GPKG rawFile.getParentFile(): " + rawFile.getParentFile());
			LOG.log(Level.INFO, "OSM GPKG rawFile.canRead(): " + rawFile.canRead());
			LOG.log(Level.INFO, "OSM GPKG rawFile.canWrite(): " + rawFile.canWrite());
		}

		try {
			byte[] bytes = new byte[(int) rawFile.length()];
			InputStream in = getContext().getContentResolver().openInputStream(uri);
			in.read(bytes, 0, (int) rawFile.length());
			in.close();
			LOG.log(Level.INFO, "OSM GPKG MediaStore read from rawFile: " + DocumentFileUtils.getAbsolutePath(rawFile, MainApp.context()));
			LOG.log(Level.INFO, "OSM GPKG MediaStore content in rawFile: " + new String(bytes));
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}
```

The codes successfully create the _test.txt_ file and read its content under the shared public Documents folder with the following logs:

```
2021-09-23 11:39:53.079 2727-2727/? I/OsmMapFragment: OSM GPKG basePathTree: APP/maps
2021-09-23 11:39:53.080 2727-2727/? I/OsmMapFragment: OSM GPKG docPathTree: Documents/APP/maps
2021-09-23 11:39:53.081 2727-2727/? I/OsmMapFragment: OSM GPKG mapPathTree: /storage/emulated/0/Documents/APP/maps
2021-09-23 11:39:53.083 2727-2727/? I/OsmMapFragment: OSM GPKG mapPathTree DocumentFileCompat.doesExist(mapPathTree): true
2021-09-23 11:39:53.096 2727-2727/? I/OsmMapFragment: OSM GPKG MediaStore uri: content://media/external/file/868
2021-09-23 11:39:53.103 2727-2727/? I/OsmMapFragment: OSM GPKG MediaStore written into: content://media/external/file/868
2021-09-23 11:39:53.103 2727-2727/? I/OsmMapFragment: OSM GPKG testFile.getUri(): content://media/external/file/868
2021-09-23 11:39:53.110 2727-2727/? I/OsmMapFragment: OSM GPKG testFile.exists(): true
2021-09-23 11:39:53.116 2727-2727/? I/OsmMapFragment: OSM GPKG testFile.isDirectory(): false
2021-09-23 11:39:53.123 2727-2727/? I/OsmMapFragment: OSM GPKG testFile.isFile(): true
2021-09-23 11:39:53.123 2727-2727/? I/OsmMapFragment: OSM GPKG testFile.getParentFile(): null
2021-09-23 11:39:53.123 2727-2727/? I/OsmMapFragment: OSM GPKG testFile.canRead(): false
2021-09-23 11:39:53.124 2727-2727/? I/OsmMapFragment: OSM GPKG testFile.canWrite(): false
2021-09-23 11:39:53.149 2727-2727/? I/OsmMapFragment: OSM GPKG filePathTree: /storage/emulated/0/Documents/APP/maps/test.txt
2021-09-23 11:39:53.151 2727-2727/? I/OsmMapFragment: OSM GPKG filePathTree DocumentFileCompat.doesExist(fileTree): true
2021-09-23 11:39:53.152 2727-2727/? I/OsmMapFragment: OSM GPKG rawFile.getUri(): file:///storage/emulated/0/Documents/APP/maps/test.txt
2021-09-23 11:39:53.152 2727-2727/? I/OsmMapFragment: OSM GPKG rawFile.exists(): true
2021-09-23 11:39:53.152 2727-2727/? I/OsmMapFragment: OSM GPKG rawFile.isDirectory(): false
2021-09-23 11:39:53.152 2727-2727/? I/OsmMapFragment: OSM GPKG rawFile.isFile(): true
2021-09-23 11:39:53.152 2727-2727/? I/OsmMapFragment: OSM GPKG rawFile.getParentFile(): null
2021-09-23 11:39:53.153 2727-2727/? I/OsmMapFragment: OSM GPKG rawFile.canRead(): true
2021-09-23 11:39:53.154 2727-2727/? I/OsmMapFragment: OSM GPKG rawFile.canWrite(): true
2021-09-23 11:39:53.161 2727-2727/? I/OsmMapFragment: OSM GPKG MediaStore read from rawFile: /storage/emulated/0/Documents/APP/maps/test.txt
2021-09-23 11:39:53.161 2727-2727/? I/OsmMapFragment: OSM GPKG MediaStore content in rawFile: Hello
```

**Comment by eclectice** [comment]
When OSMDroid doesn't have proper storage permission to read/write _cache.db_ within the scoped storage:

```
2021-09-25 12:09:15.052 17694-17694/? I/OsmDroid: Using tile source: Mapnik
2021-09-25 12:09:15.053 17694-17694/? I/OsmDroid: Tile cache increased from 0 to 9
2021-09-25 12:09:15.129 17694-17694/? I/OsmDroid: Tile cache increased from 0 to 9
2021-09-25 12:09:15.129 17694-17694/? I/OsmDroid: Geopackage support is BETA. Please report any issues
2021-09-25 12:09:15.130 17694-17694/? I/OsmDroid: Geopackage support is BETA. Please report any issues
2021-09-25 12:09:15.276 17694-17694/? E/SQLiteDatabase: Error inserting 
    android.database.sqlite.SQLiteException: near "null": syntax error (code 1 SQLITE_ERROR[1]): , while compiling: INSERT INTO "geopackage"(null) VALUES (NULL)
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1463)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:901)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:33)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:2217)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:2088)
        at mil.nga.geopackage.db.GeoPackageDatabase.insert(GeoPackageDatabase.java:127)
        at mil.nga.geopackage.db.metadata.GeoPackageMetadataDataSource.create(GeoPackageMetadataDataSource.java:51)
        at mil.nga.geopackage.factory.GeoPackageManagerImpl.importGeoPackage(GeoPackageManagerImpl.java:1319)
        at mil.nga.geopackage.factory.GeoPackageManagerImpl.importGeoPackage(GeoPackageManagerImpl.java:658)
        at mil.nga.geopackage.factory.GeoPackageManagerImpl.importGeoPackage(GeoPackageManagerImpl.java:572)
        at org.osmdroid.gpkg.tiles.raster.GeoPackageMapTileModuleProvider.<init>(GeoPackageMapTileModuleProvider.java:64)
        at org.osmdroid.gpkg.tiles.raster.GeoPackageProvider.<init>(GeoPackageProvider.java:66)
        at org.osmdroid.gpkg.tiles.raster.GeoPackageProvider.<init>(GeoPackageProvider.java:42)
```

**Comment by eclectice** [comment]
The [`GeoPackageManager` implementation](https://github.com/ngageoint/geopackage-android/blob/547a11cf9041766a781330f99e3f30d7c9d6f900/geopackage-sdk/src/main/java/mil/nga/geopackage/GeoPackageManagerImpl.java) in GeoPackage Android library already has support for `DocumentFile`:

```java
public boolean importGeoPackage(DocumentFile file);
```

**Comment by eclectice** [comment]
I'm not familiar with the git system (I'm only familiar with SVN), so I just made a patch for the **osmdroid-geopackage** update to version 6.0.2, which adds support for the `DocumentFile` objects.
[geopackage-update-to-6.0.2.zip](https://github.com/osmdroid/osmdroid/files/7271310/geopackage-update-to-6.0.2.zip)

**Comment by mguignes** [comment]
Hello,
Has this problem been resolved ?
Has it been integrated into the master branch ?
Has it been released in a new version ?

Because today, it's getting critical for any apps to upload to Google Play

Thanks !

**Comment by drogatkin** [comment]
@MKergall  , have you solved the issue? I work on a completely different project, but have a similar issue and it got even worse with Android 13. I think all android developers should unite and send a petition to Google to reconsider current approach. It didn't make Android safer, but killed many good apps. So far, Android clearly loses to iOS specifically for bad designed API.

**Comment by MKergall** [comment]
I solved it on important sections of my own app (OsmNavigator). 
I'm not using GeoPackage, so I didn't look at @eclectice feedback about that. 
I lost capability to handle MapQuest maps => this will certainy require an upgrade to latest MapQuest lib, and some rework on its osmdroid integration.
