### ISSUE TITLE
Limit of MapView.getOverlayManager().add() before ArrayIndexOutOfBoundsException occurs?

### ISSUE THREAD

**Issue by eclectice** [osmdroid/osmdroid#1766]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[X] Question
[X] Bug
[ ] Improvement
[ ] Build system related
[X] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

Is there a limit to the number of overlays that may be added using [MapView.getOverlayManager().add()](https://github.com/osmdroid/osmdroid/blob/dbb20901cac30b28a6a9349da097c22d9a962311/osmdroid-android/src/main/java/org/osmdroid/views/overlay/DefaultOverlayManager.java) before an `ArrayIndexOutOfBoundsException` occurs? This is because I encountered the following `ArrayIndexOutOfBoundsException` while adding overlays when reaching 1900 overlays:

```
2022-01-17 17:17:07.798 31396-31762/? W/System.err: java.lang.ArrayIndexOutOfBoundsException: src.length=1899 srcPos=0 dst.length=1900 dstPos=0 length=1900
2022-01-17 17:17:07.827 31396-31762/? W/System.err:     at java.lang.System.arraycopy(Native Method)
2022-01-17 17:17:07.827 31396-31762/? W/System.err:     at java.util.concurrent.CopyOnWriteArrayList.add(CopyOnWriteArrayList.java:280)
2022-01-17 17:17:07.827 31396-31762/? W/System.err:     at org.osmdroid.views.overlay.DefaultOverlayManager.add(DefaultOverlayManager.java:56)
2022-01-17 17:17:07.827 31396-31762/? W/System.err:     at org.osmdroid.views.overlay.DefaultOverlayManager.add(DefaultOverlayManager.java:28)
2022-01-17 17:17:07.827 31396-31762/? W/System.err:     at java.util.AbstractList.add(AbstractList.java:108)
...
```

Is it decided by the Android system, or is it hardcoded in the OSMDroid SDK, since I couldn't locate it?

### If it's a bug, version(s) of android this affects:

I'm not sure, however, I'm now testing on an Android 7.0 device (Samsung Galaxy Note 5 - SMN9208).

### Version of osmdroid the issue relates to:

6.1.11

**Comment by monsieurtanuki** [comment]
@eclectice There's no obvious limit in osmdroid.

I suggest that you run some tests adding and adding again `Overlay`s, and seeing if you can go beyond 1900 (which does not look that high).

Be careful that we're not 100% safe regarding concurrency in `DefaultOverlayManager`: yes we do use a concurrency-safe list (`private final CopyOnWriteArrayList<Overlay> mOverlayList`), but there's nothing that would prevent parallel Threads to add and remove an item at the same time. As the `add` or `set` use an index as parameter, the index could be correct at the time you want to add the item, but wrong if you remove an item in the meanwhile.

If you're able to reproduce that issue quite often, I suggest that you override `DefaultOverlayManager` and add logs every time you add/remove an item.
