### ISSUE TITLE
W/SQLiteLog: (28) failed to open "/tiles/cache.db" with flag (131138) and mode_t (0) due to error (2)

### ISSUE THREAD

**Issue by johan974** [osmdroid/osmdroid#1770]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[ X] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
When running on Android 11, I get this error: 

D/OsmDroid: Unable to store cached tile from rendertheme-v4 /16/33840/21594, database not available.
W/SQLiteLog: (28) failed to open "/tiles/cache.db" with flag (131138) and mode_t (0) due to error (2)

Before upgrading from osmdroid 6.1.6 I got this error: 

W/SQLiteLog: (28) failed to open "... osmdroid.../tiles/cache.db" with flag (131138) and mode_t (0) due to error (2)

So, I thought upgrading would be wise. 

I put the mapsforge file at /Android/data/my.base.package/files/mycountry.map

The issue looks like https://github.com/osmdroid/osmdroid/issues/1678. Is there a workaround? I am a bit afraid that these number of logs may swamp my system. 

## Environment
Android 11

compileSdkVersion 31
defaultConfig {
    targetSdkVersion 31
    …
}

implementation 'com.github.MKergall:osmbonuspack:6.8.0'
implementation 'org.osmdroid:osmdroid-android:6.1.11'
implementation 'org.osmdroid:osmdroid-mapsforge:6.1.11'
implementation 'org.mapsforge:mapsforge-map-android:0.11.0'
implementation 'org.mapsforge:mapsforge-map:0.11.0'

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.11

#### Stacktrace that may help

D/OsmDroid: Unable to store cached tile from rendertheme-v4 /16/33843/21593, database not available.
W/SQLiteLog: (28) failed to open "/tiles/cache.db" with flag (131138) and mode_t (0) due to error (2)
W/SQLiteLog: (28) failed to open "/tiles/cache.db" with flag (131072) and mode_t (0) due to error (2)
E/SQLiteLog: (14) cannot open file at line 39603 of [d2e6722037]
E/SQLiteLog: (14) os_unix.c:39603: (2) open(/tiles/cache.db) - 
E/SQLiteLog: (1) Process tmans.waypoints : Pid (32220) Uid (10251) Euid (10251) Gid (10251) Egid (10251)
E/SQLiteLog: (1) osStat failed "/tiles/cache.db" due to error (2)
E/SQLiteLog: (1) osStat failed "/tiles" due to error (2)
E/SQLiteDatabase: Failed to open database '/tiles/cache.db'.
    android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/tiles/cache.db': Directory /tiles doesn't exist
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:365)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:226)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:737)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:284)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:251)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:1392)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:1337)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1007)
        at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1024)
        at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1016)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.getDb(SqlTileWriter.java:745)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.saveFile(SqlTileWriter.java:129)
        at org.osmdroid.mapsforge.MapsForgeTileModuleProvider$TileLoader.loadTile(MapsForgeTileModuleProvider.java:118)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.loadTileIfReachable(MapTileModuleProviderBase.java:213)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:331)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 1550 SQLITE_CANTOPEN_ENOENT[1550]): Could not open database
        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:337)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:226) 
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:737) 
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:284) 
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:251) 
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:1392) 
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:1337) 
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1007) 
        at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1024) 
        at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1016) 
        at org.osmdroid.tileprovider.modules.SqlTileWriter.getDb(SqlTileWriter.java:745) 
        at org.osmdroid.tileprovider.modules.SqlTileWriter.saveFile(SqlTileWriter.java:129) 
        at org.osmdroid.mapsforge.MapsForgeTileModuleProvider$TileLoader.loadTile(MapsForgeTileModuleProvider.java:118) 
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.loadTileIfReachable(MapTileModuleProviderBase.java:213) 
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:331) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
E/OsmDroid: Unable to start the sqlite tile writer. Check external storage availability.
    android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/tiles/cache.db': Directory /tiles doesn't exist
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:365)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:226)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:737)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:284)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:251)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:1392)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:1337)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1007)
        at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1024)
        at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1016)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.getDb(SqlTileWriter.java:745)
        at org.osmdroid.tileprovider.modules.SqlTileWriter.saveFile(SqlTileWriter.java:129)
        at org.osmdroid.mapsforge.MapsForgeTileModuleProvider$TileLoader.loadTile(MapsForgeTileModuleProvider.java:118)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.loadTileIfReachable(MapTileModuleProviderBase.java:213)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:331)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 1550 SQLITE_CANTOPEN_ENOENT[1550]): Could not open database
        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:337)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:226) 
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:737) 
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:284) 
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:251) 
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:1392) 
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:1337) 
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1007) 
        at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1024) 
        at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1016) 
        at org.osmdroid.tileprovider.modules.SqlTileWriter.getDb(SqlTileWriter.java:745) 
        at org.osmdroid.tileprovider.modules.SqlTileWriter.saveFile(SqlTileWriter.java:129) 
        at org.osmdroid.mapsforge.MapsForgeTileModuleProvider$TileLoader.loadTile(MapsForgeTileModuleProvider.java:118) 
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.loadTileIfReachable(MapTileModuleProviderBase.java:213) 
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:331) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923)

**Comment by johan974** [comment]
I really hope anyone responds, because Google Android directs developers to the new Android SDK, buildtools, etc. Running my 8 year old app with osmdroid with the newest Android gives so much logs, I am afraid it will crash after some moments.

**Comment by monsieurtanuki** [comment]
Hi @johan974!
It's strange to see `"/tiles/cache.db"`, like directly from the root directory.
I know that Android 11 changed the way to manage file access.
I'm sure that there are currently issues on osmdroid (open or closed) that will give you inspiration to solve your problem.

**Comment by johan974** [comment]
How can I solved the problem myself? Please give me some hints. 
Do I have influence e.g. on the location of the cache.db file?

**Comment by monsieurtanuki** [comment]
Hi @johan974!
You do have influence on the location of the cache.db file, with `IConfigurationProvider.setOsmdroidBasePath(File)` (e.g. with `DefaultConfigurationProvider`).
Of course this must be called very early in the app lifecycle.
Hope this helps.

**Comment by johan974** [comment]
Thank you for helping. Much appreciated. 

I use osmdroid for many years in my personal app, but didn't need deep knowledge of it. 

I see this example code, is setting the first sufficient, are is the complete code necessary? 

org.osmdroid.config.IConfigurationProvider osmConf = org.osmdroid.config.Configuration.getInstance();
File basePath = new File(getCacheDir().getAbsolutePath(), "osmdroid");
osmConf.setOsmdroidBasePath(basePath);
File tileCache = new File(osmConf.getOsmdroidBasePath().getAbsolutePath(), "tile");
osmConf.setOsmdroidTileCache(tileCache);

**Comment by monsieurtanuki** [comment]
@johan974 Yes, theoretically that would be something like that: "hey osmdroid, write there!" (assuming you have the folder privileges, but I'll let you deal with that). Do that early, before the database is created.
I don't think there are limitations on the db cache size - I mean, before your disk is running out of space.
If you need space you can remove tiles, but I don't remember it's done automatically (on what grounds?). Maybe I'm wrong.

**Comment by johan974** [comment]
Thanks for the help. 
Explaining this for non-osmdroid-nerds helps using and appreciating Osmdroid. 

org.osmdroid.config.IConfigurationProvider osmConf = org.osmdroid.config.Configuration.getInstance();
// NOT: File basePath = new File(getCacheDir().getAbsolutePath(), "osmdroid");
// NOT: osmConf.setOsmdroidBasePath(basePath);
File tileCache = new File(getCacheDir().getAbsolutePath(), "tile");
osmConf.setOsmdroidTileCache(tileCache);

**Comment by bioneo213** [comment]
@Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();
        StrictMode.setThreadPolicy(policy);
        
        Configuration.getInstance().setOsmdroidBasePath(new File(Environment.getExternalStorageDirectory(), "osmdroid"));
        Configuration.getInstance().setOsmdroidTileCache(new File(Environment.getExternalStorageDirectory(), "osmdroid/tiles"));
        Configuration.getInstance().setUserAgentValue(userAgent);
      
       //finally  Map works after applying this code
      org.osmdroid.config.IConfigurationProvider osmConf = org.osmdroid.config.Configuration.getInstance();
        File tileCache = new File(getCacheDir().getAbsolutePath(), "tile");
        osmConf.setOsmdroidTileCache(tileCache);
        
        
        //Configuration.getInstance().setMapViewHardwareAccelerated(true);
        MapsForgeTileSource.createInstance(getApplication());

Thank you!! still helpful after wondering for several hours why my map is all grid and grey.
