### ISSUE TITLE
Cant Building with Gradle

### ISSUE THREAD

**Issue by radosimarmata** [osmdroid/osmdroid#1785]
## Issue Type

[* ] Question

## Description and/or steps/code to reproduce the problem

When i clone this to my local folder, i try to ./gradlew clean install from osmandroid folder.
and the response is :
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.11'.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.lang.IllegalArgumentException: Could not determine java version from '11.0.11'.
        at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:68)
        at org.gradle.api.JavaVersion.current(JavaVersion.java:78)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:32)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:205)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

What i miss to build this app ?

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.2

**Comment by eclectice** [comment]
Refer to https://stackoverflow.com/questions/54358107/gradle-could-not-determine-java-version-from-11-0-2 for your main issue.

You can also read my article on how to create OSMDroid without using the Gradle Fury scripts.
https://github.com/osmdroid/osmdroid/issues/1756#issue-1084559601

We'll have to wait for the OSMDroid maintainer(s) to upgrade the build system, as described here: https://github.com/osmdroid/osmdroid/issues/1776

**Comment by radosimarmata** [comment]
> Refer to https://stackoverflow.com/questions/54358107/gradle-could-not-determine-java-version-from-11-0-2 for your main issue.
> 
> You can also read my post on how to create OSMDroid without using the Gradle Fury scripts. [#1756 (comment)](https://github.com/osmdroid/osmdroid/issues/1756#issue-1084559601)
> 
> We'll have to wait for the OSMDroid maintainer(s) to upgrade the build system, as described here: #1776

same, cant run the app in android studio

**Comment by spyhunter99** [comment]
use java 8
