### ISSUE TITLE
How can a GeoPoint be tested to see if it is valid for polygon/polyline points or inside the MapView boundary?

### ISSUE THREAD

**Issue by eclectice** [osmdroid/osmdroid#1846]
## Issue Type

[X ] Question

## Problem Description

What is the proper approach to determine whether a particular **GeoPoint** is inside the **MapView** boundary?

I must do this to prevent accepting a user **GeoPoint** entry when drawing a polygon or polyline that results in the following ***IllegalArgumentException***:

```log
java.lang.IllegalArgumentException: south must be in [-85.05112877980658,85.05112877980658]
```

Currently,  I use this code to verify the GeoPoint in a MapView boundary:

```java
boolean valid = false;
BoundingBox bb = mapView.getOverlayManager().getTilesOverlay().getBounds();
try {
    valid = bb.contains(p); //check point is within boundary or not
} catch (Exception e) {
    e.printStackTrace(); //silently ignore the exception to avoid crashing the app
}

if (valid) //accept the point into the point list to create the polygon/polyline...
```

Does the boundary returned by `mapView.getOverlayManager().getTilesOverlay().getBounds()` correspond to the **MapView** boundary? Because it initializes the following [line](https://github.com/osmdroid/osmdroid/blob/dbb20901cac30b28a6a9349da097c22d9a962311/osmdroid-android/src/main/java/org/osmdroid/views/overlay/Overlay.java#L57) in the **Overlay** constructor, that is why I chose it:

```java
protected BoundingBox mBounds = new BoundingBox(tileSystem.getMaxLatitude(), tileSystem.getMaxLongitude(), tileSystem.getMinLatitude(), tileSystem.getMinLongitude());
``` 

The problem is that although the check indicates that the **GeoPoint** is valid, but when I use the point to make a polygon or polyline from a collection of GeoPoints, I still get an ***IllegalArgumentException*** like above.

Note that I disable the ***Confguration.getInstance()*** options to repeat **MapView** horizontally and vertically.

## Environment

Irrelevant

### Version of osmdroid the issue relates to:

Maybe 6.1.13 and below since @spyhunter99 is working on a [version](https://github.com/osmdroid/osmdroid/issues/1751) that silently ignores the ***IllegalArgumentException*** from the **BoundingBox**.

**Comment by eclectice** [comment]
I discovered that the ***IllegalArgumentException*** is not caused by the ***BoundingBox.contains()*** method.

This implies that every point outside of the MapView boundary is correctly skipped, but when it comes to construct a polygon or polyline using the point list afterwards, it raises the aforementioned exception.

The second method in the ***PolyOverlayWithIW,setPoints()*** method is when the exception occurs:

```java
public void setPoints(final List<GeoPoint> points) {
    mOutline.setPoints(points);
    setDefaultInfoWindowLocation(); //the cause of IllegalArgumentException!
}
```

Here is the logcat showing the ***IllegalArgumentException***:

```java
    java.lang.IllegalArgumentException: north must be in [-85.05112877980658,85.05112877980658]
        at org.osmdroid.util.BoundingBox.set(BoundingBox.java:74)
        at org.osmdroid.views.overlay.LinearRing.computeProjected(LinearRing.java:611)
        at org.osmdroid.views.overlay.LinearRing.getBoundingBox(LinearRing.java:644)
        at org.osmdroid.views.overlay.LinearRing.getCenter(LinearRing.java:544)
        at org.osmdroid.views.overlay.PolyOverlayWithIW.setDefaultInfoWindowLocation(PolyOverlayWithIW.java:221)
        at org.osmdroid.views.overlay.PolyOverlayWithIW.setPoints(PolyOverlayWithIW.java:380)
```

I try to modify the check and add a test for polygon/polyline formation as follows:

```java
boolean valid = false;
if (polylinePoints.get(getPolyLineIdCount()) == null) {
	polylinePoints.put(getPolyLineIdCount(), new ArrayList<>());
}
try {
	BoundingBox bb = mapView.getOverlayManager().getTilesOverlay().getBounds();
	valid = bb.contains(p); //check point is within boundary or not
	if (valid) {
		valid = false;
		//copy the point list to test for valid boundary
		List<GeoPoint> testPoints = new ArrayList<>();
		testPoints.addAll(polylinePoints.get(getPolyLineIdCount()));
		testPoints.add(p);

		//TEST point list
		if (testPoints.size() > 0)
		{
			Polyline test = new Polyline();
			test.setPoints(testPoints);
			valid = true;
		}
	}
} catch (Exception e) {
	Tools.showMessageBar(getActivity(), MessageType.ERROR, "Out of boundary!");
	e.printStackTrace(); //send an error message to logcat
}
if (valid) {
    //since it is now valid add the point to the TARGET point list
	polylinePoints.get(getPolyLineIdCount()).add(p);

	if (polylinePoints.get(getPolyLineIdCount()).size() > 0) {
		List<GeoPoint> pointList = polylinePoints.get(getPolyLineIdCount());
		
		final ExtendedPolyline polyline = new ExtendedPolyline(mapView, getPolyLineIdCount());
		polyline.setTitle("POLYLINE" + getPolyLineIdCount());
		polyline.setInfoWindow(null);
		polyline.setGeodesic(true);
		polyline.setPoints((List<GeoPoint>) pointList);
		
		mapView.getOverlays().add(polyline);		
		
	}
}
```

The odd thing, though, is that using the TARGET point list to generate the polygon or polyline results in a ***IllegalArgumentException***, whereas using the TEST point list does not.

The ExtendedPolyline/ExtendedPolygon class, which extends from Polygon/Polyline, is not uncommon, as can be seen in the following code:

```java
import org.osmdroid.util.GeoPoint;
import org.osmdroid.views.MapView;
import org.osmdroid.views.Projection;
import org.osmdroid.views.overlay.Polyline;

import java.util.logging.Logger;

public class ExtendedPolyline extends Polyline {


    final int id;

    private float mDensity = 1.0f;

    public ExtendedPolyline(MapView mapView, int id) {
        super(mapView);
        this.id = id;
        mDensity = mapView.getContext().getResources().getDisplayMetrics().density;
    }

    public interface OnLongPressListener {
        boolean onLongPress(MotionEvent e, MapView mapView, int id);
    }

    ExtendedPolyline.OnLongPressListener listener;

    public void setOnLongPressListener(ExtendedPolyline.OnLongPressListener listener) {
        this.listener = listener;
    }

    @Override
    public boolean onLongPress(MotionEvent e, MapView mapView) {

        final Projection pj = mapView.getProjection();
        GeoPoint eventPos = (GeoPoint) pj.fromPixels((int) e.getX(), (int) e.getY());
        double tolerance = getPaint().getStrokeWidth() * mDensity;
        final GeoPoint closest = getCloseTo(eventPos, tolerance, mapView);
        if (closest != null) {
            if (listener == null) {
                return onClickDefault(this, mapView, closest);
            } else {
                return listener.onLongPress(e, mapView, this.id);
            }
        } else
            return false;
    }

    @Override
    public void onDetach(MapView mapView) {
        super.onDetach(mapView);
        this.listener = null;
    }
}
```

So I have no idea why ExtendedPolyline/ExtendedPolygon causes a ***IllegalArgumentException***.

**Comment by eclectice** [comment]
The logcat clearly reveals that the boundary test was successful...

```log
2022-09-25 11:17:49.005 6132-6132/? E/BOUNDARY TEST: bb.contains(-82.41881117124848,-60.22058823529413,0.0) = true
2022-09-25 11:17:49.006 6132-6132/? E/BOUNDARY TEST: test.setPoints([-69.01493473316864,-98.6029411764706,0.0, -25.57625612980405,-133.01470588235293,0.0, 57.237099089869666,-123.08823529411765,0.0, 64.59727622545965,-50.29411764705881,0.0, 72.29535732628099,93.30882352941177,0.0, 48.92249926375824,163.45588235294122,0.0, -62.22940502115344,179.33823529411762,0.0, -72.8892391418859,107.86764705882354,0.0, -82.41881117124848,-60.22058823529413,0.0]) - true
2022-09-25 11:17:49.006 6132-6132/? E/BOUNDARY TEST: valid? true
```

The following ***IllegalArgumentException*** was thrown in the log for the target test point list that was copied from the test point list above:

> [-69.01493473316864,-98.6029411764706,0.0, -25.57625612980405,-133.01470588235293,0.0, 57.237099089869666,-123.08823529411765,0.0, 64.59727622545965,-50.29411764705881,0.0, 72.29535732628099,93.30882352941177,0.0, 48.92249926375824,163.45588235294122,0.0, -62.22940502115344,179.33823529411762,0.0, -72.8892391418859,107.86764705882354,0.0, -82.41881117124848,-60.22058823529413,0.0]


```log
java.lang.IllegalArgumentException: south must be in [-85.05112877980658,85.05112877980658]
```

**Comment by eclectice** [comment]
I now use the version **org.osmdroid:osmdroid-geopackage:6.1.14** that is now accessible on MavenCentral.

![image](https://user-images.githubusercontent.com/1452656/192923262-20bdd36a-c95a-4d48-8f52-ab85647a696e.png)

https://mvnrepository.com/artifact/org.osmdroid/osmdroid-geopackage

It now supports the new ***Configuration.getInstance().setEnforceTileSystemBounds()*** option, which is set to false by default.

It fixes the strange ***IllegalArgumentException*** situation while drawing the final polygon/polyline with the validated target point list.
