### ISSUE TITLE
UnsupportedOperationException when I resume an activity

### ISSUE THREAD

**Issue by AxelFernandez** [osmdroid/osmdroid#1860]
Hi, I'm having a problem trying to go back to the previous activity with a map.

## Issue Type

[x] Question
[x] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

I have two activities with two different Map instances and when I finish with the second one (The one above) this exception occurs and I can't find any answer in any blog that has happened to someone before.

Maybe it's because it can't finish removing all the overlayers before the activity ends, but I don't know what could be causing this error, can you give me more information about this exception?

This is the STP:
1- Have an Activity with a map
2- Start another Activity with another map instance 
3- Add some Overlays
4- Finish the current Activity
5- Show the first map of the step 1
6- Crash

If you need I can leave you a video of how the exception is reproduced

```
FATAL EXCEPTION: main
    Process: com.radiotaxi.taxi.driver, PID: 10531
    java.lang.UnsupportedOperationException
        at java.util.AbstractList.remove(AbstractList.java:161)
        at java.util.AbstractList$Itr.remove(AbstractList.java:374)
        at java.util.AbstractList.removeRange(AbstractList.java:571)
        at java.util.AbstractList.clear(AbstractList.java:234)
        at org.osmdroid.views.overlay.ItemizedIconOverlay.onDetach(ItemizedIconOverlay.java:50)
        at org.osmdroid.views.overlay.DefaultOverlayManager.onDetach(DefaultOverlayManager.java:195)
        at org.osmdroid.views.MapView.onDetach(MapView.java:1068)
        at org.osmdroid.views.MapView.onDetachedFromWindow(MapView.java:1273)
        at android.view.View.dispatchDetachedFromWindow(View.java:21362)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4649)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4641)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4641)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4641)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4641)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4641)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4641)
        at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:4880)
        at android.view.ViewRootImpl.doDie(ViewRootImpl.java:8410)
        at android.view.ViewRootImpl.die(ViewRootImpl.java:8387)
        at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:542)
        at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:480)
        at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:126)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5382)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7948)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
```

### Version of osmdroid the issue relates to:

6.1.2

**Comment by AxelFernandez** [comment]
Yes, the solution was to pass a `mutableList` instead of a `List` in the `ItemizedIconOverlay`. 
Also another solution was to clean all the overlays in the onDestroy like this

```
    override fun onDestroy() {
        super.onDestroy()
        osmMap?.overlays?.clear()
    }
```

Thanks a lot!
