### ISSUE TITLE
Exception: Impossible mOptimIntersection count (3)

### ISSUE THREAD

**Issue by chrisAffinity** [osmdroid/osmdroid#1886]
## Issue Type
[x] Bug (or my fault?)

## Description and/or steps/code to reproduce the problem
I am trying to lay a grid over an OSMDroid mapView (like a quad paper). I am doing that with equidistant polylines that get drawn vertically and horizontally in a certain area. This area extends beyond the view to anticipate scrolls and rotations.  There are maybe 200 lines for each orientation.  

My code for horiontal lines for example is:

    // Horizontal lines of grid
    var lat = grid.southwest.latitude
    for (counter in 0 ..200) {
        val latPolyline = Polyline(mapView)

        latPolyline.getOutlinePaint().setARGB(255, 128, 128, 128)
        latPolyline.outlinePaint.strokeWidth = 1f

        latPolyline.addPoint(GeoPoint(lat, grid.southwest.longitude))
        latPolyline.addPoint(GeoPoint(lat, grid.northeast.longitude))

        mapView.overlays.add(latPolyline)
        latPolylineList.add(latPolyline)

        lat += grid.dy // increment latitude by dy (approx. 20 meters)
    }

As soon as i scroll the map with my finger, i get many of such exceptions:

E/OsmDroid: error dispatchDraw, probably in edit mode
    java.lang.RuntimeException: Impossible mOptimIntersection count (3)
        at org.osmdroid.util.SegmentClipper.clip(SegmentClipper.java:173)
        at org.osmdroid.util.SegmentClipper.add(SegmentClipper.java:71)
        at org.osmdroid.views.overlay.LinearRing.clipAndStore(LinearRing.java:389)
        at org.osmdroid.views.overlay.LinearRing.buildLinePortion(LinearRing.java:279)
        at org.osmdroid.views.overlay.PolyOverlayWithIW.drawWithLines(PolyOverlayWithIW.java:326)
        at org.osmdroid.views.overlay.PolyOverlayWithIW.draw(PolyOverlayWithIW.java:242)
        at org.osmdroid.views.overlay.Overlay.draw(Overlay.java:144)
        at org.osmdroid.views.overlay.DefaultOverlayManager.onDrawHelper(DefaultOverlayManager.java:179)
        at org.osmdroid.views.overlay.DefaultOverlayManager.onDraw(DefaultOverlayManager.java:139)
        at org.osmdroid.views.MapView.dispatchDraw(MapView.java:1253)
        at android.view.View.updateDisplayListIfDirty(View.java:23242)
        at android.view.View.draw(View.java:24125)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
        at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
        at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
        at android.view.View.updateDisplayListIfDirty(View.java:23242)
        at android.view.View.draw(View.java:24125)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
        at android.view.View.updateDisplayListIfDirty(View.java:23242)
        at android.view.View.draw(View.java:24125)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
        at android.view.View.updateDisplayListIfDirty(View.java:23242)
        at android.view.View.draw(View.java:24125)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
        at android.view.View.updateDisplayListIfDirty(View.java:23242)
        at android.view.View.draw(View.java:24125)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
        at android.view.View.updateDisplayListIfDirty(View.java:23242)
        at android.view.View.draw(View.java:24125)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
        at android.view.View.updateDisplayListIfDirty(View.java:23242)
        at android.view.View.draw(View.java:24125)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
        at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:1531)
        at android.view.View.draw(View.java:24398)
        at com.android.internal.policy.DecorView.draw(DecorView.java:1504)
        at android.view.View.updateDisplayListIfDirty(View.java:23256)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:753)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:759)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:857)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:5501)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5194)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4356)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2991)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10665)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
        at android.view.Choreographer.doCallbacks(Choreographer.java:923)
        at android.view.Choreographer.doFrame(Choreographer.java:852)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
E/OsmDroid:     at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8741)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

BTW: I do not know, if it is because of that exception, but sometimes after scrolling the map, all vertical or all horizontal lines are missing. 

## Environment
Android Studio in newest version with kotlin

### If it's a bug, version(s) of android this affects:
All

### Version of osmdroid the issue relates to:
implementation 'org.osmdroid:osmdroid-android:6.1.13'
implementation 'org.osmdroid:osmdroid-mapsforge:6.1.11'

**Comment by monsieurtanuki** [comment]
Hi @chrisAffinity!
I believe it's a side effect, because your precision is too high (20 meters).

When we display polygons, we (need to) optimize them.
We display accurately whatever is displayed, and we "optimize" the rest by simplifying it as much as possible. Instead of useless details, we "display" something like a rectangle for the hidden part, so that the scrolling is smooth.

When we optimize, we have to compute how the polygon segments intersect, and for that we compute each vertex.
I guess that your precision is so high that we meet side-effects with projections (like math methods) and double precision. As a consequence, we find incoherences in the vertex list and that's where it crashes.

What if you try with bigger segments, like 100m or 1K: do you still experience the same bug?

**Comment by chrisAffinity** [comment]
Hi @monsieurtanuki!

Thanks for your answer. But I don't think it's because of the precision.

As you asked, I tested with bigger distances between lines (even 1000 meters). I still get the exception - but not so often. It seems to think, that such a polyline intersects the view area at 3 sides at the same time - as far as i can see from the method, where the exception is thrown. 

Btw, those polylines are pretty long, about 5000 meters. I did that so that i don't have to remove and set all those polylines frequently, when the position of the map is changed.

I also tested LatLonGridlineOverlay. No such problems - even with gridlines distances smaller than 20 meters. Right now I am trying to reconstruct my own subclass of Overlay and solve it via draw method like LatLonGridlineOverlay, but with my own grid.

**Comment by chrisAffinity** [comment]
I have succeded in writing my own overlay for my grid now, and i am happy with that. This solution seems to be very stable.

**Comment by monsieurtanuki** [comment]
@chrisAffinity Congratulations!
It looks like polylines were not adapted to your specific need. Looking back at your code, your polylines have just one segment/2 points, right? That would explain the possible side effects.
A polyline/polygon is adapted to geo area. Finding an alternate solution with `LatLonGridlineOverlay` looks like a good solution.
Feel free to reopen the issue if relevant.
