### ISSUE TITLE
Map View is not displaying the offline map

### ISSUE THREAD

**Issue by vidhyablrgithub** [osmdroid/osmdroid#1959]
I am using osmdroid library to view offline map
I followed this page,

https://medium.com/@asynctaskcoffee/android-openstreetmap-offline-map-setup-8c71eee40088

except MOBAC.

I used map file generated from http://download.mapsforge.org/maps/v5/africa/

Upon running the applciation, map is not seen even though map load listener is successful.
Here is the log message.

12-10 18:34:06.977 17057 18336 W OsmDroid: android.database.sqlite.SQLiteException: no such table: tiles (code 1 SQLITE_ERROR): , while compiling: SELECT tile FROM tiles WHERE key = 0 and provider = ?
12-10 18:34:06.977 17057 18336 W OsmDroid: 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
12-10 18:34:06.977 17057 18336 W OsmDroid: 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:903)
12-10 18:34:06.977 17057 18336 W OsmDroid: 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:514)
12-10 18:34:06.977 17057 18336 W OsmDroid: 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
12-10 18:34:06.977 17057 18336 W OsmDroid: 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
12-10 18:34:06.977 17057 18336 W OsmDroid: 	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
12-10 18:34:06.977 17057 18336 W OsmDroid: 	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
12-10 18:34:06.977 17057 18336 W OsmDroid: 	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1457)
12-10 18:34:06.977 17057 18336 W OsmDroid: 	at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1295)
12-10 18:34:06.977 17057 18336 W OsmDroid: 	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1166)
12-10 18:34:06.977 17057 18336 W OsmDroid: 	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1334)
12-10 18:34:06.977 17057 18336 W OsmDroid: 	at org.osmdroid.tileprovider.modules.DatabaseFileArchive.getImage(DatabaseFileArchive.java:91)
12-10 18:34:06.977 17057 18336 W OsmDroid: 	at org.osmdroid.tileprovider.modules.DatabaseFileArchive.getInputStream(DatabaseFileArchive.java:116)
12-10 18:34:06.977 17057 18336 W OsmDroid: 	at org.osmdroid.tileprovider.modules.MapTileFileArchiveProvider.getInputStream(MapTileFileArchiveProvider.java:195)
12-10 18:34:06.977 17057 18336 W OsmDroid: 	at org.osmdroid.tileprovider.modules.MapTileFileArchiveProvider.access$100(MapTileFileArchiveProvider.java:29)
12-10 18:34:06.977 17057 18336 W OsmDroid: 	at org.osmdroid.tileprovider.modules.MapTileFileArchiveProvider$TileLoader.loadTile(MapTileFileArchiveProvider.java:229)
12-10 18:34:06.977 17057 18336 W OsmDroid: 	at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:183)
12-10 18:34:06.977 17057 18336 W OsmDroid: 	at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:149)
12-10 18:34:06.977 17057 18336 W OsmDroid: 	at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:131)
12-10 18:34:06.977 17057 18336 W OsmDroid: 	at org.osmdroid.tileprovider.modules.MapTileApproximater$TileLoader.loadTile(MapTileApproximater.java:112)
12-10 18:34:06.977 17057 18336 W OsmDroid: 	at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:312)
12-10 18:34:06.977 17057 18336 W OsmDroid: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-10 18:34:06.977 17057 18336 W OsmDroid: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-10 18:34:06.977 17057 18336 W OsmDroid: 	at java.lang.Thread.run(Thread.java:764)
12-10 18:34:07.243 12502 12502 D BoundBrokerSvc: onUnbind: Intent { act=com.google.firebase.dynamiclinks.service.START pkg=com.google.android.gms }

Please help if the source map file is giving any problem over here. I am kind of stuck here.

**Comment by spyhunter99** [comment]
you're using the wrong tile provider. for .map files from mapsforge, you need the mapsforge setup. They are not interchangable.

**Comment by vidhyablrgithub** [comment]
Thank you for your quick response. This sample app used MOBAC generated sqlite files an a provider. With MOBAC, I am unable to download a map file. So thought of using mapsforge files. Can you please tell me, to use the same MOBAC sample code, what other tile provider be used so that i can reuse the same code as it is?

**Comment by emandtf** [comment]
> Thank you for your quick response.
So please close this ticket if it's solved.......

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/wiki/Offline-Map-Tiles#mobile-atlas-creator-mobac

you might want to open the zip file. if the content looks like this

.
./foo
./foo/0/0/0.png

then your map file source set via osmdroid must be called "foo"
