### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'boolean org.osmdroid.views.overlay.OverlayManager.add(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by kv-shreyas** [osmdroid/osmdroid#1975]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Bug

### If it's a bug, version(s) of android this affects:

java.lang.NullPointerException: Attempt to invoke interface method 'boolean org.osmdroid.views.overlay.OverlayManager.add(java.lang.Object)' on a null object reference
	at org.osmdroid.views.overlay.FolderOverlay.add(FolderOverlay.java:68)
	at com.xyz.common.onMap.onMapManager.itemOverLays.WaypointOverlay.lambda$new$7(WaypointOverlay.java:252)
	at xyz.onMap.onMapManager.itemOverLays.WaypointOverlay.$r8$lambda$zvcCj-gnTL4EdWLDr-8GZi_MkTY(Unknown Source:0)
	at com.accord.xyz.common.onMap.onMapManager.itemOverLays.WaypointOverlay$$ExternalSyntheticLambda7.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1131)

Attempt to add a null overlay to the collection. This is probably a bug and should be reported!
                                                                                                    java.lang.Exception
                                                                                                    	at org.osmdroid.views.overlay.DefaultOverlayManager.add(DefaultOverlayManager.java:53)
                                                                                                    	at org.osmdroid.views.overlay.DefaultOverlayManager.add(DefaultOverlayManager.java:28)
                                                                                                    	at java.util.AbstractList.add(AbstractList.java:108)
                                                                                                    	at org.osmdroid.views.overlay.FolderOverlay.add(FolderOverlay.java:68)
                                                                                                    	at com.xyz.common.onMap.onMapManager.itemOverLays.WaypointOverlay.lambda$new$7(WaypointOverlay.java:253)
                                                                                                    	at com.xyz.common.onMap.onMapManager.itemOverLays.WaypointOverlay.$r8$lambda$zvcCj-gnTL4EdWLDr-8GZi_MkTY(Unknown Source:0)
                                                                                                    	at com.xyz.common.onMap.onMapManager.itemOverLays.WaypointOverlay$$ExternalSyntheticLambda7.run(Unknown Source:8)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:883)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loop(Looper.java:214)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7356)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1131)
ver: 6.1.14

**Comment by spyhunter99** [comment]
any other specifics here? could be a programming error or perhaps a strange lifecycle issue (rotating the device, turning off the screen, switching apps, etc)

**Comment by kv-shreyas** [comment]
No. This doesn't happen frequently. But this exception occurs whenever I
try to recreate my Activity. I don't know why. This happens Inspite of my
mapview object being initialized.

Regards
Shreyas kv
