### ISSUE TITLE
Map View throwing Error as Too many receivers, total of 1000, registered

### ISSUE THREAD

**Issue by SayokMajumder** [osmdroid/osmdroid#1997]
## Description :

```
**Fatal Exception: java.lang.IllegalStateException
Too many receivers, total of 1000, registered for pid: 24045, callerPackage: com.kpn.android**

Fatal Exception: java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid: 24045, callerPackage: com.kpn.android
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2397)
       at android.os.Parcel.createException(Parcel.java:2373)
       at android.os.Parcel.readException(Parcel.java:2356)
       at android.os.Parcel.readException(Parcel.java:2298)
       at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5577)
       at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1658)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1612)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1600)
       at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:678)
       at org.osmdroid.tileprovider.util.SimpleRegisterReceiver.registerReceiver(SimpleRegisterReceiver.java:21)
       at org.osmdroid.tileprovider.modules.MapTileFileStorageProviderBase.<init>(MapTileFileStorageProviderBase.java:26)
       at org.osmdroid.tileprovider.modules.MapTileFileArchiveProvider.<init>(MapTileFileArchiveProvider.java:71)
       at org.osmdroid.tileprovider.modules.MapTileFileArchiveProvider.<init>(MapTileFileArchiveProvider.java:59)
       at org.osmdroid.tileprovider.modules.MapTileFileArchiveProvider.<init>(MapTileFileArchiveProvider.java:92)
       at org.osmdroid.tileprovider.MapTileProviderBasic.createArchiveProvider(MapTileProviderBasic.java:139)
       at org.osmdroid.tileprovider.MapTileProviderBasic.<init>(MapTileProviderBasic.java:101)
       at org.osmdroid.tileprovider.MapTileProviderBasic.<init>(MapTileProviderBasic.java:69)
       at org.osmdroid.tileprovider.MapTileProviderBasic.<init>(MapTileProviderBasic.java:62)
       at org.osmdroid.views.MapView.<init>(MapView.java:235)
       at org.osmdroid.views.MapView.<init>(MapView.java:205)
       at org.osmdroid.views.MapView.<init>(MapView.java:275)
       at com.kpn.android.ui.address.maplocation.components.MapViewKt.OSMMapWidget(MapView.kt:319)
       at com.kpn.android.ui.address.maplocation.components.MapViewKt$MapView$$inlined$ConstraintLayout$2.invoke(ConstraintLayout.kt:1539)
       at androidx.constraintlayout.compose.ConstraintLayoutKt$ConstraintLayout$2.invoke(ConstraintLayout.kt:89)
       at com.kpn.android.ui.address.maplocation.components.MapViewKt$MapView$$inlined$ConstraintLayout$2.invoke(ConstraintLayout.kt:89)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
       at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.java:192)
       at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2556)
       at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2827)
       at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3314)
       at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3265)
       at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:940)
       at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1155)
       at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:127)
       at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:583)
       at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:551)
       at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
       at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.java:109)
       at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.java:41)
       at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1135)
       at android.view.Choreographer.doCallbacks(Choreographer.java:959)
       at android.view.Choreographer.doFrame(Choreographer.java:880)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1122)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:254)
       at android.app.ActivityThread.main(ActivityThread.java:8219)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
```

### If it's a bug, version(s) of android this affects:

10 to 13

### Version of osmdroid the issue relates to:

6.1.18

**Comment by panax11** [comment]
In my case, there were no issues when I modified the MapView to prevent recomposition.

**Comment by woheller69** [comment]
I have the same issue. What do you mean with "prevent recomposition"?
