### ISSUE TITLE
Problem between OSMDroid 5.2 and OSMBonusPack 5.7

### ISSUE THREAD

**Issue by 2ndGAB** [osmdroid/osmdroid#314]
Hello,
I switched to OSMDroid 5.2 but because I use RadiusMarkerClusterer which seems not ported to OSMDroid, I need to keep OSMBonusPack 5.7.

And because I use RadiusMarkerClusterer, I need to use org.osmdroid.bonuspack.overlays.Marker.

But I encounter the following error at runtime.

    05-26 18:09:09.817 29963-29963/com.... E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com...., PID: 29963
                                                                     java.lang.NoClassDefFoundError: Failed resolution of: Lorg/osmdroid/DefaultResourceProxyImpl;
                                                                         at org.osmdroid.bonuspack.overlays.Marker.<init>(Marker.java:67)
                                                                         at com.....Fragment_mainmap.sitesLoadingFinish(Fragment_mainmap.java:832)
                                                                         at com.....LoadSitesListTask.onPostExecute(LoadSitesListTask.java:169)
                                                                         at com.....LoadSitesListTask.onPostExecute(LoadSitesListTask.java:53)
                                                                         at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                         at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                         at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                      Caused by: java.lang.ClassNotFoundException: Didn't find class "org.osmdroid.DefaultResourceProxyImpl" on path: DexPathList[[dex file "/data/data/com..../files/instant-run/dex/slice-zbar_9bbd8b20f3a1abaf4bdb4beb208e3e69afb68a94-classes.dex", dex file "/data/data/com../files/instant-run/dex/slice-support-annotations-23.4.0_746204fb0858029f7726656d045c4a3d9189aca1-classes.dex", dex file "/data/data/com..../files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com..../files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com..../files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com..../files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com..../files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com..../files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com..../files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com..../files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com..../files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com../files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com../files/instant-run/dex/slice-org.osmdroid-osmdroid-android-5.2_09ea5b027f83141466cf257f1955678de3b4d4da-classes.dex", dex file "/data/data/com..../files/instant-run/dex/slice-internal_impl-23.2.1_f803f969282bea30de3ac4613361c05e2484451f-classes.dex", dex file "/data/data/com..../files/instant-run/dex/slice-intermediates-exploded-aar-osmbonuspack_v5.7_241dacfaa95c48c38c49b1a9682e7cd3b1b691c0-classes.dex", dex file "/data/data/com...../files/instant-run/dex/slice-gson-2.4_50715300289712eac07014fe1f7bece3d5a0105a-classes.dex", dex file "/data/data/com..../files/instant-run/dex/slice-commons-net-3.4_e1087f25e139a25d0bcd958bed91bb130c2de097-classes.dex", dex file "/data/data/com../files/instant-run/dex/slice-commons-io-2.4_f171108052ca57eebda73d3420202beb4cc9cde8-classes.dex", dex file "/data/data/com../files/instant-run/dex/slice-com.google.android.gms-play-services-measurement-8.4.0_02b7794fe13c71dfabaa96cb32829ee13ca1a17c-classes.dex", dex file "/data/data/com../files/instant-run/dex/slice-com.google.android.gms-play-services-maps-8.4.0_592c3fdd77c1726684cb5af09793335683941bf2-classes.dex", dex file "/data/data/com../files/instant-run/dex/slice-com.google.android.gms-play-services-location-8.4.0_e3a0646a80188c1feee97dd22c18986b64d53e43-classes.dex", dex file "/data/data/com../files/instant-run/dex/slice-com.google.android.gms-play-services-gcm-8.4.0_073d4dbe4b5b1efdd8524b8eaae23b360c7021f4-classes.dex", dex file "/data/data/com../files/instant-run/dex/slice-com.google.android.gms-play-services-basement-8.4.0_bc747819bf48a6f9deeb6e3f82

Caused by Marker.java:

    public Marker(MapView mapView) {
        this(mapView, new DefaultResourceProxyImpl(mapView.getContext()));
    }

Do you know why ``ResourceProxy`` is not found??

**Comment by spyhunter99** [comment]
I think you need osmbonuspack 5.8

**Comment by 2ndGAB** [comment]
ah sorry I didn't pay attention to this update. thanks
