### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Lorg/osmdroid/bonuspack/R$layout; -- FolderOverlay -- >buildOverlay - 

### ISSUE THREAD

**Issue by juamor86** [osmdroid/osmdroid#375]
I use osmbonuspack v5.5 , osmdroid-v5.01 and slf4j-android-1.5.8.jar , gson22.4 and commons-lang3-3.3.2
I am working in Eclipse

this code Java :

@Override
protected void onCreate(Bundle savedInstanceState) {
super.onCreate(savedInstanceState);
setContentView(R.layout.activity_main);

    myOpenMapView = (MapView)findViewById(R.id.openmapview);
    myOpenMapView.setTileSource(TileSourceFactory.MAPNIK);
    myOpenMapView.setBuiltInZoomControls(true); //quita los botones de zoom de la pantalla
    myOpenMapView.setMultiTouchControls(true);
    myOpenMapView.setEnabled(true);
    myOpenMapView.setClickable(true);

    String url = "http://mapsengine.google.com/map/kml?forcekml=1&mid=z6IJfj90QEd4.kUUY9FoHFRdE";
    mKmlDocument = new KmlDocument();

    mapControl = (MapController) myOpenMapView.getController();
    mapControl.setZoom(50);
    GeoPoint myLocation = new GeoPoint(40.46560773896929, -3.6887799453731081);
    mapControl.setCenter(myLocation);
    putKMLAsync(url);

}

private class putKML extends AsyncTask<String, Void, Boolean> {
    @Override
    protected Boolean doInBackground(String... url) {
        boolean sucess = false;
        sucess = mKmlDocument.parseKMLUrl(url[0]);
        return sucess;
    }

    @Override
    protected void onPostExecute(Boolean ok) {
        updateKML();
    }
}

private void updateKML(){
    if (mKmlOverlay != null){
        mKmlOverlay.closeAllInfoWindows();
        myOpenMapView.getOverlays().remove(mKmlOverlay);
    }
    mKmlOverlay = (FolderOverlay) mKmlDocument.mKmlRoot.buildOverlay(myOpenMapView, null, null, mKmlDocument);
    myOpenMapView.getOverlays().add(mKmlOverlay);
    myOpenMapView.invalidate();
}

private void putKMLAsync(String url) {
    new putKML().execute(url);
}
Trace Error :

08-18 12:32:34.832: E/AndroidRuntime(2510): FATAL EXCEPTION: main
Process: com.example.demo.osmdroid, PID: 2510
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/osmdroid/bonuspack/R$layout;
at org.osmdroid.bonuspack.overlays.Marker.(Marker.java:101)
at org.osmdroid.bonuspack.overlays.Marker.(Marker.java:67)
at org.osmdroid.bonuspack.kml.KmlPoint.buildOverlay(KmlPoint.java:86)
at org.osmdroid.bonuspack.kml.KmlPlacemark.buildOverlay(KmlPlacemark.java:124)
at org.osmdroid.bonuspack.kml.KmlFolder.buildOverlay(KmlFolder.java:160)
at org.osmdroid.bonuspack.kml.KmlFolder.buildOverlay(KmlFolder.java:160)
at com.example.demo.osmdroid.MainActivity.updateKML(MainActivity.java:107)
at com.example.demo.osmdroid.MainActivity.access$3(MainActivity.java:102)
at com.example.demo.osmdroid.MainActivity$putKML.onPostExecute(MainActivity.java:98)
at com.example.demo.osmdroid.MainActivity$putKML.onPostExecute(MainActivity.java:1)
at android.os.AsyncTask.finish(AsyncTask.java:651)
at android.os.AsyncTask.-wrap1(AsyncTask.java)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-18 12:32:34.832: E/AndroidRuntime(2510): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.osmdroid.bonuspack.R$layout" on path: DexPathList[[zip file "/data/app/com.example.demo.osmdroid-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.demo.osmdroid-2/lib/arm, /vendor/lib, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
... 19 more
Suppressed: java.lang.ClassNotFoundException: org.osmdroid.bonuspack.R$layout
at java.lang.Class.classForName(Native Method)
at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
... 20 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by spyhunter99** [comment]
Sounds like you have a mismatched version of osmdroid vs bonus pack

**Comment by juamor86** [comment]
which should I use?

**Comment by juamor86** [comment]
use osmdroid 5.2 and osmbonus 5.8.1 ?

**Comment by spyhunter99** [comment]
better answered by @MKergall

**Comment by k3b** [comment]
Todo Update: https://github.com/osmdroid/osmdroid/wiki/Upgrade-Guide#partial-merger-of-osm-bonus-pack to show which versions belong together.

I assume that osmbonuspack v5.5 requires osmdroid-v5.2 or newer

**Comment by spyhunter99** [comment]
not an osmdroid issue, closing for now

**Comment by ymchao** [comment]
Hello, can you tell me how to solve it?

**Comment by k3b** [comment]
> how to solve it?

use versions of osmbonuspack with a matching osmdroid version.

> I assume that osmbonuspack v5.5 requires osmdroid-v5.2 or newer

If that does not help: this issue belongs to https://github.com/MKergall/osmbonuspack/issues
