### ISSUE TITLE
 Error downloading MapTile

### ISSUE THREAD

**Issue by fanwlok** [osmdroid/osmdroid#438]
This sometimes happens
#  Error loading tile
                                                                     java.lang.IllegalArgumentException: Problem decoding into existing bitmap
                                                                         at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:619)
                                                                         at org.osmdroid.tileprovider.tilesource.BitmapTileSourceBase.getDrawable(BitmapTileSourceBase.java:150)
                                                                         at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:214)
                                                                         at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:296)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                         at java.lang.Thread.run(Thread.java:841)
# E/OsmDroid: Error downloading MapTile: /5/1/18
                                                                      java.lang.IllegalArgumentException: Problem decoding into existing bitmap
                                                                          at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:619)
                                                                          at org.osmdroid.tileprovider.tilesource.BitmapTileSourceBase.getDrawable(BitmapTileSourceBase.java:150)
                                                                          at org.osmdroid.tileprovider.modules.MapTileDownloader$TileLoader.loadTile(MapTileDownloader.java:233)
                                                                          at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:296)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                          at java.lang.Thread.run(Thread.java:841)

**Comment by spyhunter99** [comment]
Guess you missed the contributing guide. What version of osmdroid, what API level is the device that has the problem, what map source is the issue occurring with? any other relevant facts to help troubleshoot?

most likely cause: a problem with the network connection or the remote map server had an issue
