### ISSUE TITLE
MapView throws NPE when used in edit mode

### ISSUE THREAD

**Issue by Toomy** [osmdroid/osmdroid#439]
Hi,
I'd like to report, that the current version of the MapView ( org.osmdroid:osmdroid-android:5.4.1:release@aar ) throws an NPE in the UI Editor ( both Android Studio and IDEA ). This is easy to reproduce since the  [How-to-use-the-osmdroid-library](https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library)  HOWTO published by this project does not work either.

The error is reproducable as soon as the MapView is present in the layout.xml like this
<<org.osmdroid.views.MapView
    android:id="@+id/mapview"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tilesource="Mapnik" />

The reason is that the mScroller variable is set to null when in `isInEditMode()` in the constructor, but the code that runs in this mode dereferences the mScroller.

Regards Markus

Please note this Stack trace:
`java.lang.NullPointerException
	at org.osmdroid.views.MapView.computeScroll(MapView.java:960)
	at android.view.View.draw(View.java:15961)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3609)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
	at android.view.View.draw(View.java:16088)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3609)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
	at android.view.View.draw(View.java:16088)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3609)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
	at android.view.View.draw(View.java:16181)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:455)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:428)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:350)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:510)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:498)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:863)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:498)
	at com.android.tools.idea.rendering.RenderTask.access$600(RenderTask.java:72)
	at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:610)
	at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:607)
	at com.android.tools.idea.rendering.RenderService.runRenderAction(RenderService.java:359)
	at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:607)
	at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:629)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.doRender(AndroidLayoutPreviewToolWindowManager.java:652)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.access$1700(AndroidLayoutPreviewToolWindowManager.java:80)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7$1.run(AndroidLayoutPreviewToolWindowManager.java:594)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7.run(AndroidLayoutPreviewToolWindowManager.java:589)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:260)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:274)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:229)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:222)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.util.Alarm$Request.run(Alarm.java:389)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor.runFirstTaskThenPollAndRunRest(BoundedTaskExecutor.java:178)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$000(BoundedTaskExecutor.java:40)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:197)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by spyhunter99** [comment]
strange, i know there was an issue regarding this recently and it was fixed ( can't find the ticket). Try with 5.5

**Comment by Toomy** [comment]
Hi
I have tried 5.5 right know. It produces the exact same NPE and is not workind.

I checked some more versions:
The last working version for me is 5.0.1. 
Version 5.1 throws an exception, but this is about the storage manager, so this is something else.
Version 5.4 has the same NPE as well
Version 5.4.1 has the same NPE as well

**Comment by spyhunter99** [comment]
OK so it's an IDE specific issue and not a functional issue. What IDE and version?

**Comment by spyhunter99** [comment]
try changing the render api level to 23 or lower
howto: http://stackoverflow.com/questions/34499839/android-studio-does-not-show-layout-preview

**Comment by Toomy** [comment]
Hi
No, you missunderstood my version statement. I have tested different versions of the OSM-DROID library to find out when the bug has been introduced. The NPE has nothing to do with the IDE version, since it is caused by dereferencing an null variable inside MapView.

I have not tested with different API levels, but I can not imagine that this is the reason.

**Comment by spyhunter99** [comment]
"isInEditMode" is only used in the IDE, like android studio, in the layout preview generator (as far as i know). All our on-device-tests pass and no one else is complaining about NPE when using the library either in the emulator or on hardware.

**Comment by Toomy** [comment]
Hi, That is exactly the point. The MapView is not working in the IDE Gui Designer. The MapView is working perfectly in the app. The thing is, since the MapView is not working in the IDE, we can't can use the UI designer when ever this control is in the layout definition.

**Comment by spyhunter99** [comment]
Right. What version of the "IDE Gui Designer" are you referring to? Is this
android studio or something else? What operating system? Try changing the
render API to lower than 23. That might fix it.

**Comment by spyhunter99** [comment]
#378 found the related issue

**Comment by Toomy** [comment]
Hi
Unfortunately the linked issue is something else, not related to this problem.
Also I have tried your suggestion to check with different API levels and to Idea 2016.2.2 on both win and linux.
Its exactly the same NPE thrown everywhere. And it is obvious why if you have a look to the stack trace I have provided in my first post.

The error is in the constructor of the MapView class where the mScroller is explicitly set to null if 'isInEditMode()' returns true. There are two possibilities to fix this: Either providing a null object or check for null at every place where mScroller is dereferenced.

Regards Markus

**Comment by spyhunter99** [comment]
Right, it when it was set to a non null object, other exceptions were
through due to context being null. Feel free to open a PR

**Comment by spyhunter99** [comment]
I was able to fix it. changes are minimal. waiting for ci to build it

**Comment by spyhunter99** [comment]
It passed travis. Do you want to test this branch before I merge it? bug/#439

**Comment by Toomy** [comment]
Hi
unfortunately I'm not so familiar with this toolchain - so I was not able to build the osmdroid libs successfully, but I did a small code review of the current MapView class. I saw your changes you did ant this make sence and seem correct. 

But I stubled over something else that, in my eyes makes no sense. Check this out MapView.java lines 157 - 166:

if(isInEditMode()){
	mTileRequestCompleteHandler=null;
	mController=null;
	mZoomController=null;
	mScroller=null;
	mGestureDetector=null;
	return;
}
this.mController = new MapController(this);
this.mScroller = new Scroller(context);

This makes no sense. I general I have the impression that this control suffers a bit from the two possible usage modes ( In the app / In the Editor ). The handling of this difference is scattered over the whole code of the control and makes it difficult to read and maintain. I think this is the reason why it struggeled already many times in the Editor mode. I think it is best to not set members to `null` in the 'Editor' case, but brovide a proper implementation of this mode and initialize the control accordingly.

Please do not take this as a critism, I like this project very much - This has just attracted my eyes when I had a look into the code.

I hope it works now, because I like the Editor mode ;)

**Comment by spyhunter99** [comment]
The editor is pretty useless for osmdroid. It just shows a blank screen.

I can set values to non null that also require context, since android context isn't available in edit mode. It does make it harder to read.

What tool chain are you using?

**Comment by spyhunter99** [comment]
merged
