### ISSUE TITLE
Crash with the sample app, osmpath sample

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#443]
ran across this gem. api21 x86 emulator with the osmpath overlay while zooming past 16

@MKergall any ideas on this?

10-16 09:58:12.498 22451-22451/org.osmdroid I/OsmDroid: rescale tile cache from 14 to 15
10-16 09:58:12.533 22451-22451/org.osmdroid I/OsmDroid: Finished rescale in 35ms
10-16 09:58:13.582 22451-22451/org.osmdroid I/OsmDroid: rescale tile cache from 15 to 16
10-16 09:58:13.609 22451-22451/org.osmdroid I/OsmDroid: Finished rescale in 27ms
10-16 09:58:13.642 22451-22459/org.osmdroid W/art: Suspending all threads took: 6.902ms
10-16 09:58:13.647 22451-22464/org.osmdroid I/art: Background sticky concurrent mark sweep GC freed 1711(76KB) AllocSpace objects, 16(327KB) LOS objects, 0% free, 17MB/17MB, paused 15.403ms total 46.274ms
10-16 09:58:14.207 22451-22657/org.osmdroid D/OsmDroid: tile inserted Mapnik/16/19298/24624
10-16 09:58:14.222 22451-22658/org.osmdroid D/OsmDroid: tile inserted Mapnik/16/19298/24627
10-16 09:58:14.252 1491-1514/system_process I/UsageStatsService: User[0] Flushing usage stats to disk
10-16 09:58:14.499 22451-22657/org.osmdroid D/OsmDroid: tile inserted Mapnik/16/19299/24625
10-16 09:58:14.509 22451-22658/org.osmdroid D/OsmDroid: tile inserted Mapnik/16/19299/24624
10-16 09:58:14.608 22451-22658/org.osmdroid D/OsmDroid: tile inserted Mapnik/16/19298/24626
10-16 09:58:14.611 22451-22657/org.osmdroid D/OsmDroid: tile inserted Mapnik/16/19298/24625
10-16 09:58:14.698 22451-22451/org.osmdroid A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc4228008 in tid 22451 (org.osmdroid)
10-16 09:58:14.801 22409-22409/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-16 09:58:14.801 22409-22409/? I/DEBUG: Build fingerprint: 'generic_x86/sdk_google_phone_x86/generic_x86:5.0.2/LSY66K/3287218:eng/test-keys'
10-16 09:58:14.802 22409-22409/? I/DEBUG: Revision: '0'
10-16 09:58:14.802 22409-22409/? I/DEBUG: ABI: 'x86'
10-16 09:58:14.802 22409-22409/? I/DEBUG: pid: 22451, tid: 22451, name: org.osmdroid  >>> org.osmdroid <<<
10-16 09:58:14.802 22409-22409/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc4228008
10-16 09:58:14.804 22409-22409/? I/DEBUG:     eax c4228008  ebx b77a0800  ecx ffffffe1  edx ffffffe1
10-16 09:58:14.804 22409-22409/? I/DEBUG:     esi 00000002  edi 00000001
10-16 09:58:14.804 22409-22409/? I/DEBUG:     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000007  xss 0000007b
10-16 09:58:14.804 22409-22409/? I/DEBUG:     eip b774b0b1  ebp b77acda0  esp bf8f6610  flags 00210202
10-16 09:58:14.804 22409-22409/? I/DEBUG: backtrace:
10-16 09:58:14.804 22409-22409/? I/DEBUG:     #00 pc 000840b1  /system/lib/libc.so (je_arena_tcache_fill_small+417)
10-16 09:58:14.804 22409-22409/? I/DEBUG:     #01 pc 000a560e  /system/lib/libc.so (je_tcache_alloc_small_hard+62)
10-16 09:58:14.804 22409-22409/? I/DEBUG:     #02 pc 00099332  /system/lib/libc.so (je_malloc+226)
10-16 09:58:14.804 22409-22409/? I/DEBUG:     #03 pc 000127ce  /system/lib/libc.so (malloc+30)
10-16 09:58:14.804 22409-22409/? I/DEBUG:     #04 pc 00000d5b  /system/lib/libstdc++.so (operator new(unsigned int)+27)
10-16 09:58:14.804 22409-22409/? I/DEBUG:     #05 pc 00032c2e  /system/lib/libhwui.so (android::uirenderer::DisplayListRenderer::drawBitmap(SkBitmap const*, float, float, float, float, float, float, float, float, SkPaint const*)+238)
10-16 09:58:14.804 22409-22409/? I/DEBUG:     #06 pc 000b9fcd  /system/lib/libandroid_runtime.so
10-16 09:58:14.804 22409-22409/? I/DEBUG:     #07 pc 00db4918  /data/dalvik-cache/x86/system@framework@boot.oat
10-16 09:58:14.824 22409-22409/? W/libbacktrace: virtual bool UnwindPtrace::Unwind(size_t, ucontext_t*): unw_init_remote failed -3
10-16 09:58:14.824 22409-22409/? I/DEBUG: ptrace detach from 22480 failed: No such process
10-16 09:58:14.843 22409-22409/? I/DEBUG: Tombstone written to: /data/tombstones/tombstone_09
                                          
                                          
                                          [ 10-16 09:58:14.843 22409:22409 E/         ]
                                          debuggerd committing suicide to free the zombie!
10-16 09:58:14.845 1491-1516/system_process I/BootReceiver: Copying /data/tombstones/tombstone_09 to DropBox (SYSTEM_TOMBSTONE)
                                                            
                                                            [ 10-16 09:58:14.847 22687:22687 I/         ]
                                                            debuggerd: Sep 20 2016 20:25:43
10-16 09:58:14.849 1491-2306/system_process E/SharedPreferencesImpl: Couldn't create directory for SharedPreferences file shared_prefs/log_files.xml
10-16 09:58:14.852 1149-1149/? I/Zygote: Process 22451 exited due to signal (11)
10-16 09:58:14.863 1491-1576/system_process W/InputDispatcher: channel '1bc027a org.osmdroid/org.osmdroid.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
10-16 09:58:14.863 1491-1576/system_process E/InputDispatcher: channel '1bc027a org.osmdroid/org.osmdroid.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
10-16 09:58:14.864 1491-1576/system_process W/InputDispatcher: channel 'cbacdef Panel:org.osmdroid/org.osmdroid.ExtraSamplesActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
10-16 09:58:14.864 1491-1576/system_process E/InputDispatcher: channel 'cbacdef Panel:org.osmdroid/org.osmdroid.ExtraSamplesActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
10-16 09:58:14.864 1491-1702/system_process I/WindowState: WIN DEATH: Window{cbacdef u0 Panel:org.osmdroid/org.osmdroid.ExtraSamplesActivity}
10-16 09:58:14.865 1491-1954/system_process W/libprocessgroup: failed to open /acct/uid_10067/pid_22451/cgroup.procs: No such file or directory
10-16 09:58:14.865 1491-1954/system_process I/ActivityManager: Process org.osmdroid (pid 22451) has died
10-16 09:58:14.865 1491-1954/system_process W/ActivityManager: Force removing ActivityRecord{1b2ff3a3 u0 org.osmdroid/.ExtraSamplesActivity t336}: app died, no saved state
10-16 09:58:14.864 1491-1576/system_process W/InputDispatcher: channel '2e4426ff org.osmdroid/org.osmdroid.ExtraSamplesActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
10-16 09:58:14.865 1491-1576/system_process E/InputDispatcher: channel '2e4426ff org.osmdroid/org.osmdroid.ExtraSamplesActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
10-16 09:58:14.865 1491-1702/system_process W/InputDispatcher: Attempted to unregister already unregistered input channel 'cbacdef Panel:org.osmdroid/org.osmdroid.ExtraSamplesActivity (server)'
10-16 09:58:14.867 1491-1953/system_process I/WindowState: WIN DEATH: Window{2e4426ff u0 org.osmdroid/org.osmdroid.ExtraSamplesActivity}
10-16 09:58:14.867 1491-1953/system_process W/InputDispatcher: Attempted to unregister already unregistered input channel '2e4426ff org.osmdroid/org.osmdroid.ExtraSamplesActivity (server)'
10-16 09:58:14.867 1491-1953/system_process W/WindowManager: Force-removing child win Window{cbacdef u0 Panel:org.osmdroid/org.osmdroid.ExtraSamplesActivity EXITING} from container Window{2e4426ff u0 org.osmdroid/org.osmdroid.ExtraSamplesActivity}
10-16 09:58:14.869 1491-2051/system_process I/WindowState: WIN DEATH: Window{1bc027a u0 org.osmdroid/org.osmdroid.MainActivity}
10-16 09:58:14.869 1491-2051/system_process W/InputDispatcher: Attempted to unregister already unregistered input channel '1bc027a org.osmdroid/org.osmdroid.MainActivity (server)'
10-16 09:58:14.894 22688-22688/? E/libprocessgroup: failed to make and chown /acct/uid_10067: Read-only file system
10-16 09:58:14.894 22688-22688/? W/Zygote: createProcessGroup failed, kernel missing CONFIG_CGROUP_CPUACCT?
10-16 09:58:14.895 22688-22688/? I/art: Not late-enabling -Xcheck:jni (already on)
10-16 09:58:14.897 1491-1954/system_process I/ActivityManager: Start proc org.osmdroid for activity org.osmdroid/.MainActivity: pid=22688 uid=10067 gids={50067, 9997, 3003, 1028, 1015} abi=x86
10-16 09:58:14.918 22688-22688/? W/ResourcesManager: Asset path '/system/framework/com.google.android.maps.jar' does not exist or contains no resources.
10-16 09:58:14.933 22688-22695/? E/art: Failed sending reply to debugger: Broken pipe
10-16 09:58:14.933 22688-22695/? I/art: Debugger is no longer active
10-16 09:58:14.935 1491-1583/system_process I/OpenGLRenderer: Initialized EGL, version 1.4
10-16 09:58:14.943 22688-22688/? D/ACRA: ACRA is enabled for org.osmdroid, initializing...
10-16 09:58:14.945 22688-22688/? D/ACRA: Using default Report Fields
10-16 09:58:14.953 22688-22688/? D/ACRA: Looking for error files in /data/data/org.osmdroid/files
10-16 09:58:14.962 3235-3250/com.google.android.gms I/art: Explicit concurrent mark sweep GC freed 40832(2MB) AllocSpace objects, 8(128KB) LOS objects, 33% free, 8MB/12MB, paused 566us total 38.398ms
10-16 09:58:15.026 3160-3175/com.google.android.gms.persistent I/art: Background sticky concurrent mark sweep GC freed 4869(268KB) AllocSpace objects, 0(0B) LOS objects, 2% free, 9MB/9MB, paused 8.756ms total 21.895ms
10-16 09:58:15.040 3235-3245/com.google.android.gms W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/data/com.google.android.gms/databases/auto_complete_suggestions.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
10-16 09:58:15.040 3235-3245/com.google.android.gms E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                  java.lang.Throwable: Explicit termination method 'close' not called
                                                                      at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                                      at android.database.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:170)
                                                                      at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:190)
                                                                      at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
                                                                      at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
                                                                      at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                                                                      at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
                                                                      at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
                                                                      at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
                                                                      at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1142)
                                                                      at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1131)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at jkm.d(:com.google.android.gms:212)
                                                                      at jkm.c(:com.google.android.gms:158)
                                                                      at jkm.aN_(:com.google.android.gms:130)
                                                                      at peb.a(:com.google.android.gms:1045)
                                                                      at com.google.android.gms.googlehelp.service.ClearHelpHistoryChimeraIntentOperation.onHandleIntent(:com.google.android.gms:38)
                                                                      at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms:99)
                                                                      at bfe.run(:com.google.android.gms:5982)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:818)
10-16 09:58:15.040 3235-3245/com.google.android.gms E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                  java.lang.Throwable: Explicit termination method 'close' not called
                                                                      at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                                      at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:190)
                                                                      at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                                                                      at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
                                                                      at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
                                                                      at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
                                                                      at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1142)
                                                                      at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1131)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at jkm.d(:com.google.android.gms:212)
                                                                      at jkm.c(:com.google.android.gms:158)
                                                                      at jkm.aN_(:com.google.android.gms:130)
                                                                      at peb.a(:com.google.android.gms:1045)
                                                                      at com.google.android.gms.googlehelp.service.ClearHelpHistoryChimeraIntentOperation.onHandleIntent(:com.google.android.gms:38)
                                                                      at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms:99)
                                                                      at bfe.run(:com.google.android.gms:5982)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:818)
10-16 09:58:15.041 3235-3245/com.google.android.gms E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                  java.lang.Throwable: Explicit termination method 'close' not called
                                                                      at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                                      at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:807)
                                                                      at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
                                                                      at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
                                                                      at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1142)
                                                                      at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1131)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at jkm.d(:com.google.android.gms:212)
                                                                      at jkm.c(:com.google.android.gms:158)
                                                                      at jkm.aN_(:com.google.android.gms:130)
                                                                      at peb.a(:com.google.android.gms:1045)
                                                                      at com.google.android.gms.googlehelp.service.ClearHelpHistoryChimeraIntentOperation.onHandleIntent(:com.google.android.gms:38)
                                                                      at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms:99)
                                                                      at bfe.run(:com.google.android.gms:5982)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:818)
10-16 09:58:15.041 3235-3245/com.google.android.gms W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/data/com.google.android.gms/databases/help_responses.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
10-16 09:58:15.041 3235-3245/com.google.android.gms E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                  java.lang.Throwable: Explicit termination method 'close' not called
                                                                      at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                                      at android.database.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:170)
                                                                      at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:190)
                                                                      at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
                                                                      at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
                                                                      at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                                                                      at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
                                                                      at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
                                                                      at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
                                                                      at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1142)
                                                                      at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1131)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at jkm.d(:com.google.android.gms:212)
                                                                      at jkm.c(:com.google.android.gms:158)
                                                                      at jkm.aN_(:com.google.android.gms:130)
                                                                      at owv.a(:com.google.android.gms:11113)
                                                                      at com.google.android.gms.googlehelp.service.ClearHelpHistoryChimeraIntentOperation.onHandleIntent(:com.google.android.gms:37)
                                                                      at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms:99)
                                                                      at bfe.run(:com.google.android.gms:5982)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:818)
10-16 09:58:15.042 3235-3245/com.google.android.gms E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                  java.lang.Throwable: Explicit termination method 'close' not called
                                                                      at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                                      at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:190)
                                                                      at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                                                                      at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
                                                                      at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
                                                                      at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
                                                                      at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1142)
                                                                      at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1131)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at jkm.d(:com.google.android.gms:212)
                                                                      at jkm.c(:com.google.android.gms:158)
                                                                      at jkm.aN_(:com.google.android.gms:130)
                                                                      at owv.a(:com.google.android.gms:11113)
                                                                      at com.google.android.gms.googlehelp.service.ClearHelpHistoryChimeraIntentOperation.onHandleIntent(:com.google.android.gms:37)
                                                                      at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms:99)
                                                                      at bfe.run(:com.google.android.gms:5982)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:818)
10-16 09:58:15.042 3235-3245/com.google.android.gms E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                  java.lang.Throwable: Explicit termination method 'close' not called
                                                                      at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                                      at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:807)
                                                                      at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
                                                                      at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
                                                                      at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1142)
                                                                      at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1131)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at jkm.d(:com.google.android.gms:212)
                                                                      at jkm.c(:com.google.android.gms:158)
                                                                      at jkm.aN_(:com.google.android.gms:130)
                                                                      at owv.a(:com.google.android.gms:11113)
                                                                      at com.google.android.gms.googlehelp.service.ClearHelpHistoryChimeraIntentOperation.onHandleIntent(:com.google.android.gms:37)
                                                                      at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms:99)
                                                                      at bfe.run(:com.google.android.gms:5982)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:818)
10-16 09:58:15.042 3235-3245/com.google.android.gms W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/data/com.google.android.gms/databases/metrics.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
10-16 09:58:15.042 3235-3245/com.google.android.gms E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                  java.lang.Throwable: Explicit termination method 'close' not called
                                                                      at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                                      at android.database.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:170)
                                                                      at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:190)
                                                                      at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
                                                                      at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
                                                                      at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                                                                      at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
                                                                      at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
                                                                      at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
                                                                      at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1142)
                                                                      at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1131)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at jkm.d(:com.google.android.gms:212)
                                                                      at jkm.c(:com.google.android.gms:158)
                                                                      at jkm.aN_(:com.google.android.gms:130)
                                                                      at pat.b(:com.google.android.gms:2106)
                                                                      at com.google.android.gms.googlehelp.service.ClearHelpHistoryChimeraIntentOperation.onHandleIntent(:com.google.android.gms:36)
                                                                      at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms:99)
                                                                      at bfe.run(:com.google.android.gms:5982)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:818)
10-16 09:58:15.043 3235-3245/com.google.android.gms E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                  java.lang.Throwable: Explicit termination method 'close' not called
                                                                      at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                                      at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:190)
                                                                      at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                                                                      at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
                                                                      at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
                                                                      at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
                                                                      at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1142)
                                                                      at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1131)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at jkm.d(:com.google.android.gms:212)
                                                                      at jkm.c(:com.google.android.gms:158)
                                                                      at jkm.aN_(:com.google.android.gms:130)
                                                                      at pat.b(:com.google.android.gms:2106)
                                                                      at com.google.android.gms.googlehelp.service.ClearHelpHistoryChimeraIntentOperation.onHandleIntent(:com.google.android.gms:36)
                                                                      at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms:99)
                                                                      at bfe.run(:com.google.android.gms:5982)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:818)
10-16 09:58:15.043 3235-3245/com.google.android.gms E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                  java.lang.Throwable: Explicit termination method 'close' not called
                                                                      at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                                      at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:807)
                                                                      at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
                                                                      at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
                                                                      at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1142)
                                                                      at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1131)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:261)
                                                                      at jkm.d(:com.google.android.gms:212)
                                                                      at jkm.c(:com.google.android.gms:158)
                                                                      at jkm.aN_(:com.google.android.gms:130)
                                                                      at pat.b(:com.google.android.gms:2106)
                                                                      at com.google.android.gms.googlehelp.service.ClearHelpHistoryChimeraIntentOperation.onHandleIntent(:com.google.android.gms:36)
                                                                      at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms:99)
                                                                      at bfe.run(:com.google.android.gms:5982)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:818)
10-16 09:58:15.093 22688-22727/? D/OpenGLRenderer: Render dirty regions requested: true
                                                   
                                                   [ 10-16 09:58:15.094 22688:22688 D/         ]
                                                   HostConnection::get() New Host Connection established 0xacda4910, tid 22688
10-16 09:58:15.100 22688-22688/? D/Atlas: Validating map...
                                          
                                          [ 10-16 09:58:15.161 22688:22727 D/         ]
                                          HostConnection::get() New Host Connection established 0xaef21160, tid 22727
10-16 09:58:15.167 22688-22727/? I/OpenGLRenderer: Initialized EGL, version 1.4
10-16 09:58:15.186 22688-22727/? D/OpenGLRenderer: Enabling debug mode 0
10-16 09:58:15.363 1491-1520/system_process I/ActivityManager: Displayed org.osmdroid/.MainActivity: +491ms
10-16 09:58:18.385 1491-1667/system_process W/AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client
10-16 09:58:18.416 1491-1583/system_process D/OpenGLRenderer: endAllStagingAnimators on 0xa17e2d00 (RippleDrawable) with handle 0x9d93a380
10-16 09:58:18.419 1491-1953/system_process W/InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 22451 uid 10067

**Comment by spyhunter99** [comment]
ahh turning off hardware acceleration resolved it. maybe we should just force the mapview to be software accelerated?

**Comment by MKergall** [comment]
At least, setting the mapview to be software accelerated by default (and developers could turn HA on at their own risks).

**Comment by spyhunter99** [comment]
great idea

**Comment by spyhunter99** [comment]
merged, wiki updated
