### ISSUE TITLE
Crash onLocationChanged

### ISSUE THREAD

**Issue by parizene** [osmdroid/osmdroid#486]
HTC Desire 400 dual sim Android 4.1.1
`
Fatal Exception: java.lang.NullPointerException
       at org.osmdroid.views.overlay.mylocation.GpsMyLocationProvider.onLocationChanged(GpsMyLocationProvider.java:143)
       at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:234)
       at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:167)
       at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:183)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:155)
       at android.app.ActivityThread.main(ActivityThread.java:5520)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
       at dalvik.system.NativeStart.main(NativeStart.java)
`

**Comment by parizene** [comment]
`if (mIgnorer.shouldIgnore(location.getProvider(), System.currentTimeMillis()))`
location can be null

**Comment by spyhunter99** [comment]
great find. what kind of device did you run across this on?
