### ISSUE TITLE
Android Studio Layout preview Rendering problems

### ISSUE THREAD

**Issue by Ziotek** [osmdroid/osmdroid#508]
Hello, I don't know what to do next. In my android device, maps only display empty grid. 
In AndroidManifest I add all uses permission.
```
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```
 I'm using osmdroid-android:5.6.1.
Here is my screen of [Dependencies](http://oi65.tinypic.com/2r263k3.jpg) in Android Studio.
In preview in Android Studio 2.2.2 I have a next problems:

Rendering Problems 
The following classes could not be instantiated:
- org.osmdroid.views.MapView (Open Class, Show Exception, Clear Cache)

Exception Details 
java.lang.NullPointerException  
```
at android.os.storage.StorageManager.getVolumeList(StorageManager.java:922)  
at android.os.Environment$UserEnvironment.getExternalDirs(Environment.java:87)   
at android.os.Environment.getExternalStorageDirectory(Environment.java:404)   
at org.osmdroid.tileprovider.util.StorageUtils.getStorageList(StorageUtils.java:77)   
at org.osmdroid.tileprovider.util.StorageUtils.getStorage(StorageUtils.java:150)  
at org.osmdroid.config.DefaultConfigurationProvider.<init>(DefaultConfigurationProvider.java:60)   
at org.osmdroid.config.Configuration.getInstance(Configuration.java:23)   
at org.osmdroid.views.MapView.<init>(MapView.java:158)   
at org.osmdroid.views.MapView.<init>(MapView.java:212)   
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)   
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)   
at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)   
at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   
at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   
at android.view.LayoutInflater.inflate(LayoutInflater.java:518)   
at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
```

My xml:
```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <org.osmdroid.views.MapView
        android:id="@+id/mapview_offline"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
    </org.osmdroid.views.MapView>

</RelativeLayout>
```

And java:

```
public class OfflineMapsActivity extends Activity {

    private MapView mapView;
    private IMapController mapController;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_offline_maps);
        org.osmdroid.tileprovider.constants.OpenStreetMapTileProviderConstants.setUserAgentValue(BuildConfig.APPLICATION_ID);

        mapView = (org.osmdroid.views.MapView) findViewById(R.id.mapview_offline);
        mapView.setTileSource(TileSourceFactory.MAPNIK);
        mapView.setTileSource(new XYTileSource("Mapnik", 6, 15, 256, ".png", new String[] {}));
        mapView.setUseDataConnection(false);
        mapView.setBuiltInZoomControls(true);
        mapView.setClickable(true);
        mapView.setMultiTouchControls(true);

        mapController =  mapView.getController();
        mapController.setZoom(10);
        GeoPoint startPoint = new GeoPoint(49.23635, 19.78787);
        mapController.animateTo(startPoint);
    }
}
```
The contents of the zip look like this: tiles.zip ->Mapnik -> 6-15 -> X -> Y.png, located in sdcard/osmdroid/tiles.zip

 I hope I can get your help, thank you.

**Comment by spyhunter99** [comment]
whoa crazy find. Is the device API23 or newer? Have permissions been granted to your app?

**Comment by Ziotek** [comment]
In API23 and API24 is the same problem. U mean permissions in AndroidManifest?

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.admin.maps" >

    <uses-sdk
        android:minSdkVersion="8"
        android:targetSdkVersion="23"/>

    <supports-screens
        android:anyDensity="true"
        android:largeScreens="true"
        android:normalScreens="true" />

    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

    <uses-feature
        android:name="android.hardware.location.network"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.location.gps"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.telephony"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.wifi"
        android:required="false" />

    <uses-library
        android:name="com.google.android.maps"
        android:required="false" />
    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <service android:name="com.mapbox.mapboxsdk.telemetry.TelemetryService" />
            <intent-filter>
                <action android:name="com.example.admin.tatry.services.IOpenStreetMapTileProviderService" />
            </intent-filter>
        <activity
            android:name=".StartActivity"
            android:screenOrientation="portrait">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <activity
            android:name=".OfflineMapsActivity"
            android:label="@string/title_activity_offline_maps"
            android:theme="@style/AppTheme.NoActionBar">
        </activity>
    </application>

</manifest>
```

**Comment by spyhunter99** [comment]
No, application runtime permissions

**Comment by spyhunter99** [comment]
see MainActivity on the sample app for an example. on api23 the user must explicitly grant access

**Comment by Ziotek** [comment]
I added runtime permissions and still have the same problem.

**Comment by miguel-porto** [comment]
Note that you have to fully restart the app after the user gives the permissions, in order that the tiles appear.

**Comment by Ziotek** [comment]
It still not this.

**Comment by spyhunter99** [comment]
@Ziotek interesting. any details on what kind of device this is? emulator?

**Comment by Ziotek** [comment]
I run this app on my mobile phone with Android 6.0. In my Android Studio in preview i have [this](http://oi68.tinypic.com/2jdp640.jpg) error. Oddly enough in other Activity online Mapbox works fine.

**Comment by spyhunter99** [comment]
The preview error is not related. what brand of phone is this? I'll trap the error and get a version cut as soon as i can.

**Comment by Ziotek** [comment]
I using LG G4c. Here is location tiles.zip on my device.

![Here](https://cloud.githubusercontent.com/assets/24796002/21513857/b3e8178e-ccbd-11e6-9d69-2879c190e1b9.gif)

**Comment by spyhunter99** [comment]
according to the stack trace, `Environment.getExternalStorageDirectory()` is either returning null or is throwing an npe. Would you mine running in the following on the same app?

System.out.println(Environment.getExternalStorageDirectory());
System.out.println(Environment.getExternalStorageDirectory().getPath());

**Comment by Ziotek** [comment]
System.out.println(Environment.getExternalStorageDirectory());  --> "/storage/emulated/0"
System.out.println(Environment.getExternalStorageDirectory().getPath());  --> "/storage/emulated/0"

**Comment by spyhunter99** [comment]
v5.6.2 was cut yesterday. it may take another day or two to show up in all mirrors. Give it a shot when you have time

**Comment by Ziotek** [comment]
I pasted my tiles.zip into internal storage (internal storage -> osmdroid -> tiles.zip) without v5.6.2 and it is now working just fine.

**Comment by spyhunter99** [comment]
where were the files previously?

**Comment by Ziotek** [comment]
I wrote in first post. In external storage (sdcard -> osmdroid -> tiles.zip).

**Comment by spyhunter99** [comment]
i hate android
