### ISSUE TITLE
I get this exception on resume of my activity that implements IMyLocationProvider on version 5.6.2

### ISSUE THREAD

**Issue by AlfredAfutu** [osmdroid/osmdroid#543]
I get this in my stack trace:

java.lang.NullPointerException
                                                                                at org.osmdroid.views.overlay.mylocation.MyLocationNewOverlay.onLocationChanged(MyLocationNewOverlay.java:481)
                                                                                at org.osmdroid.views.overlay.mylocation.GpsMyLocationProvider.onLocationChanged(GpsMyLocationProvider.java:148)
                                                                                at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:279)
                                                                                at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:208)
                                                                                at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:224)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:136)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                                at dalvik.system.NativeStart.main(Native Method)

**Comment by spyhunter99** [comment]
thanks for the report. i'll look into why shortly

**Comment by spyhunter99** [comment]
i think i found the error. a temporary work around would be to remove the mylocation overlay on Pause of your application and to add a new instance of it onresume

**Comment by spyhunter99** [comment]
@AlfredAfutu do you have a static reference to the map view? also can you check the sample app on your device? it's called "open map" in the play store. there's a link in the readme

**Comment by AlfredAfutu** [comment]
@spyhunter99 so the issue has been fixed? i dont think there would be a new version release would there? For the meantime i can use the work around you suggested?

**Comment by spyhunter99** [comment]
@AlfredAfutu  fixed meaning i added a  null check to prevent crashing. 

The fix is: onResume, add a new mylocationoverlay to the map, onPause, remove it. This was done to prevent memory leaks for both location listener and for Handler instances.
