### ISSUE TITLE
I get a crash on enableMyLocation of location overlay

### ISSUE THREAD

**Issue by AlfredAfutu** [osmdroid/osmdroid#546]
My app crashes when i use a fake location app to change my position and resume my activity with the trace:

FATAL EXCEPTION: main
                                                                          java.lang.RuntimeException: You must pass an IMyLocationProvider to setMyLocationProvider()
                                                                              at org.osmdroid.views.overlay.mylocation.MyLocationNewOverlay.setMyLocationProvider(MyLocationNewOverlay.java:196)
                                                                              at org.osmdroid.views.overlay.mylocation.MyLocationNewOverlay.enableMyLocation(MyLocationNewOverlay.java:534)

**Comment by spyhunter99** [comment]
see #543 
duplicate
