### ISSUE TITLE
Bug with cached tiles when working offline due to SQLite exceptions

### ISSUE THREAD

**Issue by miguel-porto** [osmdroid/osmdroid#556]
Hi there,
I'm facing an issue which I still can't find how exactly to reproduce it, but it happened already multiple times to me and it's frustrating. It seems to happen after you download a large amount of tiles (not necessarily with the CacheManager) and then try to use the app offline. Sometimes, with no apparent reason, upon starting the app, a lot of exceptions are thrown, related to the tile database being locked, and the tiles are no longer displayed, even after fully restarting. Sometimes they are even deleted from cache (despite the fact that I `setExpirationOverrideDuration` to 1 year)! I can't give much more details right now, because I couldn't find exactly in what circumstances this happens, seems to be somewhat random. Right now the problem disappeared because I went online. Next time it happens I will post more detailed info.
However, I would appreciate if, in the meantime, you could try to reproduce this. It seems to happen only when many tiles are cached (say, 700 MB tiles) and you restart the app when offline. I don't know if this occurs with the sample app.
I think this issue should have some priority, because it really hinders using the maps offline - you cache an area and think everything is ok, but next day you go out offline, and you can't see the tiles! This ruins your day.
I'll post a more helpful report as soon as it happens again. I'm using 5.6.4.
Best,
Miguel

**Comment by spyhunter99** [comment]
the only time it will delete tiles that are not expired is if you are past the cache trim size. Might be worth checking that and comparing the free space available on that storage device

**Comment by miguel-porto** [comment]
I'm setting it to 9 GB... and I've got about 4 GB free space.
```
config.setExpirationOverrideDuration(365L * 24L * 3600L * 1000L);
config.setTileFileSystemCacheMaxBytes(1024L * 1024L * 1024L * 10L);
config.setTileFileSystemCacheTrimBytes(1024L * 1024L * 1024L * 9L);
```
But even if space was the problem, that wouldn't explain the "database locked" exceptions... still trying to get the error again to provide more detailed info...

**Comment by miguel-porto** [comment]
Note, the "database locked" exceptions happen when reading the tiles, not during download.

**Comment by spyhunter99** [comment]
android permissions perhaps?

**Comment by miguel-porto** [comment]
No, the app works flawlessly 95% of the time..! This only happens under certain circumstances, which I didn't fully understand yet. But it really seems to be related to offline use and many cached tiles. Yes, the problem _only_ occurs when using the app offline (not always, only when you have many cached tiles).

**Comment by miguel-porto** [comment]
I've got some more details on this error, I got it again. It seems to be caused by the SQLite connection not being properly shut down, which makes the DB being locked when I relaunch the App, and no tiles are displayed then. The remaining question is: is it a problem of osmdroid sometimes not shutting down the DB transactions / connection,  or is it a problem in my app? Still don't know, but here I paste the exceptions, may be they give you a hint, in case it's something in osmdroid. See the last line.

```
2-17 14:28:51.288 19318-19357/? I/SQLiteConnectionPool: The connection pool for /storage/emulated/0/osmdroid/tiles/cache.db has been closed but there are still 1 connections in use.  They will be closed as they are released back to the pool.
02-17 14:28:51.311 19318-19355/? E/OsmDroid: Error loading tile
                                             java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
                                                 at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:962)
                                                 at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:677)
                                                 at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
                                                 at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
                                                 at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:834)
                                                 at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
                                                 at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
                                                 at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
                                                 at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:209)
                                                 at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:297)
                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                 at java.lang.Thread.run(Thread.java:818)
02-17 14:28:51.311 19318-19356/? E/OsmDroid: Error loading tile
                                             java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
                                                 at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:962)
                                                 at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:677)
                                                 at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
                                                 at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
                                                 at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:834)
                                                 at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
                                                 at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
                                                 at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
                                                 at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:209)
                                                 at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:297)
                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                 at java.lang.Thread.run(Thread.java:818)
02-17 14:28:51.311 19318-19354/? E/OsmDroid: Error loading tile
                                             java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
                                                 at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:962)
                                                 at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:677)
                                                 at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
                                                 at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
                                                 at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:834)
                                                 at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
                                                 at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
                                                 at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
                                                 at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:209)
                                                 at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:297)
                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                 at java.lang.Thread.run(Thread.java:818)
02-17 14:28:51.313 19318-19364/? E/OsmDroid: Unable to store cached tile from BingMapsAerialWithLabels /8/13/169 db is null
                                             java.lang.NullPointerException: Attempt to invoke virtual method 'long android.database.sqlite.SQLiteDatabase.insert(java.lang.String, java.lang.String, android.content.ContentValues)' on a null object reference
                                                 at org.osmdroid.tileprovider.modules.SqlTileWriter.saveFile(SqlTileWriter.java:176)
                                                 at org.osmdroid.tileprovider.modules.MapTileDownloader$TileLoader.loadTile(MapTileDownloader.java:243)
                                                 at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:297)
                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                 at java.lang.Thread.run(Thread.java:818)
02-17 14:28:51.314 19318-19358/? E/OsmDroid: Error loading tile
                                             java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
                                                 at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:962)
                                                 at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:677)
                                                 at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
                                                 at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
                                                 at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:834)
                                                 at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
                                                 at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
                                                 at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
                                                 at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:209)
                                                 at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:297)
                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                 at java.lang.Thread.run(Thread.java:818)
02-17 14:28:51.314 19318-19357/? E/OsmDroid: Error loading tile
                                             java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
                                                 at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:962)
                                                 at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:599)
                                                 at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
                                                 at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
                                                 at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:834)
                                                 at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
                                                 at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
                                                 at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
                                                 at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:209)
                                                 at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:297)
                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                 at java.lang.Thread.run(Thread.java:818)
02-17 14:28:51.314 19318-19359/? E/OsmDroid: Error loading tile
                                             java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
                                                 at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:962)
                                                 at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:677)
                                                 at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
                                                 at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
                                                 at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:834)
                                                 at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
                                                 at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
                                                 at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
                                                 at org.osmdroid.tileprovider.modules.MapTileSqlCacheProvider$TileLoader.loadTile(MapTileSqlCacheProvider.java:209)
                                                 at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:297)
                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                 at java.lang.Thread.run(Thread.java:818)
02-17 14:28:51.315 19318-19363/? E/OsmDroid: Unable to store cached tile from BingMapsAerialWithLabels /8/10/163 db is null
                                             java.lang.NullPointerException: Attempt to invoke virtual method 'long android.database.sqlite.SQLiteDatabase.insert(java.lang.String, java.lang.String, android.content.ContentValues)' on a null object reference
                                                 at org.osmdroid.tileprovider.modules.SqlTileWriter.saveFile(SqlTileWriter.java:176)
                                                 at org.osmdroid.tileprovider.modules.MapTileDownloader$TileLoader.loadTile(MapTileDownloader.java:243)
                                                 at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:297)
                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                 at java.lang.Thread.run(Thread.java:818)
02-17 14:28:51.494 19318-19318/? I/OsmDroid: Using tile source: Mapnik
02-17 14:28:51.516 19318-19318/? I/OsmDroid: sdcard state: mounted
02-17 14:28:51.520 19318-19318/? I/OsmDroid: sdcard state: mounted
02-17 14:28:51.526 19318-19318/? I/OsmDroid: sdcard state: mounted
02-17 14:28:51.543 19318-19318/? I/OsmDroid: rescale tile cache from 1 to 8
02-17 14:28:51.555 19318-19318/? I/OsmDroid: Finished rescale in 12ms
02-17 14:28:51.572 19318-19318/? I/OsmDroid: Tile cache increased from 9 to 48
02-17 14:28:51.630 19318-19325/? W/SQLiteConnectionPool: A SQLiteConnection object for database '/storage/emulated/0/osmdroid/tiles/cache.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.

```

**Comment by spyhunter99** [comment]
Do you have a static reference to the MapView or any other osmdroid
classes? This could be a resource leak

**Comment by miguel-porto** [comment]
Hmm.. I don't think so (will check it out better later); however I do have the MapView dynamically created at runtime when the Activity starts... may be this could be the reason?

**Comment by spyhunter99** [comment]
That could be it,  see the sample app, most samples are programaticly created.  When doing so,  you have to stop and release the resources of the mapview

**Comment by miguel-porto** [comment]
Unfortunately it seems not to have resolved the problem: I added a call to myMapView.onDetach() before finish()ing the main activity, but the error of the database locked (when restarting the app) happened again... let me know if you have other ideas, or if I'm not doing it right.

**Comment by spyhunter99** [comment]
try taking a look at the BaseSampleFragment in the osmdroid sample app and
see the lifecycle management code there OR put the mapview in a layout file
and then most of that isn't needed

**Comment by miguel-porto** [comment]
I've just put the mapview into the layout file; let's see how it goes in the next days... thanks.

**Comment by azetor** [comment]
Transfer layout helped?

**Comment by miguel-porto** [comment]
I haven't had more problems so far since I transferred to the layout file. I'll close this for now, but let's see in the next weeks when I'll be using the app. These exceptions were more or less unpredictable.
