### ISSUE TITLE
GoogleWrapperSample. osm-android-4.2. MapFactory.getMap throws exception.

### ISSUE THREAD

**Issue by nugmanovagulnaz** [osmdroid/osmdroid#59]
osm-android-4.0 works fine. But GoogleWrapperSample throws exception with osm-android-4.2 and osm-android-third-party-4.2:
E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NoSuchMethodError: com.google.android.gms.maps.MapsInitializer.initialize
            at org.osmdroid.google.wrapper.v2.MapFactory.getMap(MapFactory.java:23)
            at com.tatinfotech.myapplication.GoogleWrapperSample.setMapView(GoogleWrapperSample.java:192)
            at com.tatinfotech.myapplication.GoogleWrapperSample.onOptionsItemSelected(GoogleWrapperSample.java:150)
            at android.app.Activity.onMenuItemSelected(Activity.java:2516)
            at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:961)
            at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:735)
            at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:149)
            at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
            at com.android.internal.view.menu.ListMenuPresenter.onItemClick(ListMenuPresenter.java:163)

**Comment by imeneLa** [comment]
i want to use the osmdroid_third party  4.3 library in order to use google fonctionnalities such as : animate camera ,animation...  i used this code :https://github.com/osmdroid/osmdroid/blob/master/GoogleWrapperSample/src/org/osmdroid/google/sample/GoogleWrapperSample.java
especially in what concerns osmap
this line doesn't work mMap = MapFactory.getMap(mapView); (the error is:The type com.google.android.maps.MapView cannot be resolved. It is indirectly referenced from required .class files) and i need it to work ,i need mMap in order to call animate camera .
Please,Can any one help me ?
