### ISSUE TITLE
Runtime Exception on enableMyLocation

### ISSUE THREAD

**Issue by AlfredAfutu** [osmdroid/osmdroid#603]
I get a runtime exception on enableMyLocation call with the stack trace
Fatal Exception: java.lang.RuntimeException: You must pass an IMyLocationProvider to setMyLocationProvider()
       at org.osmdroid.views.overlay.mylocation.MyLocationNewOverlay.setMyLocationProvider(MyLocationNewOverlay.java:197)
       at org.osmdroid.views.overlay.mylocation.MyLocationNewOverlay.enableMyLocation(MyLocationNewOverlay.java:535)
       at org.osmdroid.views.overlay.mylocation.MyLocationNewOverlay.enableMyLocation(MyLocationNewOverlay.java:564)

**Comment by spyhunter99** [comment]
This is probably an artifact from the great memory leak fix everything ticket. I'm assuming this was on your app. Anything that requires a system resource, sensor, etc is released onPause and needs to be recreated onResume.
