### ISSUE TITLE
NullPointerException MapController.setCenter()

### ISSUE THREAD

**Issue by mwuwer** [osmdroid/osmdroid#616]
Hi, I'm getting such an NPE exception reported as crash in PlayStore and do not have actually any idea in which situation it happens. On the stack trace there is also no line of code from my application. 
Any help appreciated - Thanks!

Full stack I have (version 5.6.4):
`
java.lang.NullPointerException: 
  at org.osmdroid.views.Projection.toPixels(Projection.java:121)
  at org.osmdroid.views.MapController.setCenter(MapController.java:229)
  at org.osmdroid.views.MapController$ReplayController.replayCalls(MapController.java:533)
  at org.osmdroid.views.MapController.onFirstLayout(MapController.java:97)
  at org.osmdroid.views.MapView.onLayout(MapView.java:835)
  at android.view.View.layout(View.java:16662)
  at android.view.ViewGroup.layout(ViewGroup.java:5439)
  at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1167)
  at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:852)
  at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:871)
  at android.view.View.layout(View.java:16662)
  at android.view.ViewGroup.layout(ViewGroup.java:5439)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
  at android.view.View.layout(View.java:16662)
  at android.view.ViewGroup.layout(ViewGroup.java:5439)
  at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1167)
  at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:852)
  at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:871)
  at android.view.View.layout(View.java:16662)
  at android.view.ViewGroup.layout(ViewGroup.java:5439)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
  at android.view.View.layout(View.java:16662)
  at android.view.ViewGroup.layout(ViewGroup.java:5439)
  at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
  at android.view.View.layout(View.java:16662)
  at android.view.ViewGroup.layout(ViewGroup.java:5439)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
  at android.view.View.layout(View.java:16662)
  at android.view.ViewGroup.layout(ViewGroup.java:5439)
  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
  at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
  at android.view.View.layout(View.java:16662)
  at android.view.ViewGroup.layout(ViewGroup.java:5439)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
  at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2720)
  at android.view.View.layout(View.java:16662)
  at android.view.ViewGroup.layout(ViewGroup.java:5439)
  at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2202)
  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1955)
  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1125)
  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6100)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
  at android.view.Choreographer.doCallbacks(Choreographer.java:670)
  at android.view.Choreographer.doFrame(Choreographer.java:606)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5525)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
`

**Comment by spyhunter99** [comment]
thanks for the report.

it's possible that the user quickly change activities (or otherwise cause the map to open and then close immediately).

That line of code hasn't changed in a while

````
Point out = TileSystem.LatLongToPixelXY(in.getLatitude(), in.getLongitude(),
				getZoomLevel(), reuse);
````

Back tracing this, i can add some null checks in earlier cases to trap it

**Comment by mwuwer** [comment]
Cool, thanks a lot for fixing it!

**Comment by spyhunter99** [comment]
np, merged
