### ISSUE TITLE
Network Proxy

### ISSUE THREAD

**Issue by gsantner** [osmdroid/osmdroid#625]
I'm developing an app that may need to access the web via a proxy. I found no way yet to configure an network proxy in osmdroid yet. The app should access e.g. Mapnik (<https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourceFactory.java#L94>) via a corporate proxy or proxy running on localhost (e.g. Tor)

Is there any way to accomplish this? Searches about proxy and osmdroid only revealed resource proxy but no word about network proxy /java.net.proxy

**Comment by spyhunter99** [comment]
try searching for configuring android to use a web proxy. On regular JDK, there's a number of system properties that can be set to redirect traffic to a web proxy. I have no idea if android's version of java honors it or not but it's worth looking at.

**Comment by gsantner** [comment]
Is there no httpclient, okhttpclient or like that where I could hook into?

**Comment by spyhunter99** [comment]
i think osmdroid is using the standard java HttpUrlConnection. 

https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileDownloader.java#L192

the underlying implementation will either be okhttp or apache httpclient depending on the version of the os but we don't have any hard dependencies on either

**Comment by spyhunter99** [comment]
http://docs.telerik.com/fiddler/Configure-Fiddler/Tasks/ConfigureForAndroid

that looks like a reasonable guide for setting the web proxy, should effect everything on the device no code changes needed

**Comment by gsantner** [comment]
Thanks for pointing to that line, exactly what I was looking for. (<https://stackoverflow.com/questions/1432961/how-do-i-make-httpurlconnection-use-a-proxy/1433296#1433296>)

No, it should just affect the app. I don't want to setup a device wide proxy, nor I want app users to do that

**Comment by spyhunter99** [comment]
cool find, didn't know about it. Please open a PR if you want to contribute your changes. I'd suggest possibly adding a new field to the configuration provider to get an instance of Proxy. The map tile downloader would then check for null and pass it in if needed. osmdroid developer uses can then extend the default configuration provider to provider their own mechanism for setting the proxy

**Comment by gsantner** [comment]
* <https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/config/IConfigurationProvider.java>
* <https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/config/DefaultConfigurationProvider.java>

```
+ is/setHttpProxyEnabled
+ get/setHttpProxyHost
+ get/setHttpProxyPort
```

* <https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileDownloader.java#L192>
```
+ if (config.isHttpProxyEnabled()) {
+  ... new Proxy()...
+ }
```

Are there other places or is that sufficient?

**Comment by spyhunter99** [comment]
Those are the classes.

I think there's a bunch of use cases that may be needed for authentication. i've seen all kinds of create mechanisms. I'd suggest that the config provider return an instance of Proxy

**Comment by gsantner** [comment]
What about  adding java.net.Proxy object in config provider + get/set? And making that one null as default as suggested

**Comment by spyhunter99** [comment]
bingo

**Comment by gsantner** [comment]
@spyhunter99 Howto correctly build the library? I used the commands as described in README and get:
```
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:604)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 68 more
Caused by: org.gradle.api.publish.maven.InvalidMavenPublicationException: Invalid publication 'distributions': artifact file does not exist: '/home/gregor/aaCurrent/osmdroid/osmdroid-dist/build/distributions/osmdroid-dist-5.6.5-SNAPSHOT.zip'
	at org.gradle.api.publish.maven.internal.publisher.ValidatingMavenPublisher.checkCanPublish(ValidatingMavenPublisher.java:129)
	at org.gradle.api.publish.maven.internal.publisher.ValidatingMavenPublisher.validateArtifacts(ValidatingMavenPublisher.java:99)
	at org.gradle.api.publish.maven.internal.publisher.ValidatingMavenPublisher.publish(ValidatingMavenPublisher.java:45)
	at org.gradle.api.publish.maven.tasks.PublishToMavenLocal$1.publish(PublishToMavenLocal.java:50)
	at org.gradle.api.publish.internal.PublishOperation.run(PublishOperation.java:36)
	... 77 more


BUILD FAILED
```
I tried `./gradlew clean install` and `./gradlew clean build install` and neither do work. Otherwise: My changes are ready, it's exactly what discussed above.

**Comment by spyhunter99** [comment]
built fine here, waiting on travis and i'll merge it. we're due for a release anyhow

**Comment by gsantner** [comment]
ok :D

**Comment by gsantner** [comment]
Thanks for merging! Looking forward to next release
