### ISSUE TITLE
Dependencies to deprecated object

### ISSUE THREAD

**Issue by ycuicui** [osmdroid/osmdroid#731]
## Issue Type
[x] Improvement
[x] Documentation

#### UtilConstants is refered by
- NetworkLocationIgnorer
- LocationUtils

#### latitudeE6 and longitudeE6 are still used by
- Polyline to store points as Android Point (suggest to use GeoPoint).
- Polygon for mConvertedPoints (suggest to use GeoPoint) and mOriginalPoints (suggest to use double or float)

#### zoomInFixing in MapView use by
- MapViewDoubleClickListener subclass

### Version of osmdroid the issue relates to:
5.6.5

Edits: 
reformatting this a task list

 - [x] NetworkLocationIgnorer
 - [x] LocationUtils
 - [x] latitudeE6 and longitudeE6 are still used by polyline
 - [x] latitudeE6 and longitudeE6 are still used by polgon
 - [ ] zoomInFixing in MapView use by MapViewDoubleClickListener

**Comment by spyhunter99** [comment]
good find, i think they were deprecated with api25 right? Would you mind checking to see when they are scheduled to be removed and if there is a suitable replacement?

**Comment by spyhunter99** [comment]
After changing the last set call, i'm getting unit test failures. not too sure why

````
test_toMapPixels_0_0

junit.framework.AssertionFailedError: the computed center of the map is in the pixel center of the map (Y) expected:<568.0> but was:<29.0>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:102)
at org.osmdroid.views.OpenStreetMapViewTest.checkCenter(OpenStreetMapViewTest.java:121)
at org.osmdroid.views.OpenStreetMapViewTest.checkCenter(OpenStreetMapViewTest.java:106)
at org.osmdroid.views.OpenStreetMapViewTest.test_toMapPixels_0_0(OpenStreetMapViewTest.java:58)
at java.lang.reflect.Method.invoke(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
at android.test.InstrumentationTestCase.-wrap0(InstrumentationTestCase.java)
at android.test.InstrumentationTestCase$2.run(InstrumentationTestCase.java:189)
at android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:1897)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
````
