### ISSUE TITLE
MapTileApproximater OutOfMemoryError when zooming out deep

### ISSUE THREAD

**Issue by miguel-porto** [osmdroid/osmdroid#801]
## Issue Type
[x] Bug

## Description and/or steps/code to reproduce the problem
With wi-fi turned on, pinch zoom out a large amount quickly and do not lift fingers (say, with fingers going from the screen corners to the center fast). The following exception occurs, because too many tiles are being loaded and scaled at the same time. Note that, until you lift up the fingers, the tiles will be loaded at the higher resolution (before the zoom started), and that makes hundreds of tiles being loaded and scaled and the same time at the lower zoom level, beforel you lift the fingers. And this throws this exception, causing the app to crash and vanish. I suggest that the resolution at which the tiles are being loaded should be updated during pinch zoom, to avoid loading hundreds of high res tiles simultaneously.

Anyway, congratulations for the MapTileApproximater - it *greatly* increased UX for offliners!

```
12-10 22:19:26.961 6813-6965/? I/art: Waiting for a blocking GC Alloc
12-10 22:19:26.968 6813-6968/? I/OsmDroid: Error downloading tile: /17/62449/50269
java.lang.OutOfMemoryError: Failed to allocate a 262156 byte allocation with 0 free bytes and 3GB until OOM
   at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
   at android.graphics.Bitmap.nativeCreate(Native Method)
   at android.graphics.Bitmap.createBitmap(Bitmap.java:831)
   at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
   at android.graphics.Bitmap.createBitmap(Bitmap.java:775)
   at org.osmdroid.tileprovider.modules.MapTileApproximater.getTileBitmap(MapTileApproximater.java:250)
   at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:206)
   at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:184)
   at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:148)
   at org.osmdroid.tileprovider.modules.MapTileApproximater.approximateTileFromLowerZoom(MapTileApproximater.java:130)
   at org.osmdroid.tileprovider.modules.MapTileApproximater$TileLoader.loadTile(MapTileApproximater.java:111)
   at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:317)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
   at java.lang.Thread.run(Thread.java:818)
12-10 22:19:26.968 6813-6968/? I/art: Waiting for a blocking GC Alloc
12-10 22:19:26.973 6813-6970/? I/art: Waiting for a blocking GC Alloc
12-10 22:19:26.978 6813-6823/? I/art: Waiting for a blocking GC Alloc
```

### If it's a bug, version(s) of android this affects:
API 23 at least

### Version of osmdroid the issue relates to:
6.0.0-SNAPSHOT

**Comment by spyhunter99** [comment]
thanks for the report, glad it was discovered before we cut the release

**Comment by monsieurtanuki** [comment]
Seems related to #757, and potentially to be fixed by #790.

**Comment by monsieurtanuki** [comment]
@miguel-porto Should be fixed by #800. Could you give it a try?

**Comment by miguel-porto** [comment]
Yep, it does work now without problems!
However, this change brought a slight decrease in UX: the pinch zoom is not totally smooth any more, you can notice breaks every time the tile resolution changes during pinch zoom.

**Comment by monsieurtanuki** [comment]
@miguel-porto I'm glad it helped!
About the UX issue you mentioned: do you mean that the _pinch gesture is smooth in itself_ but that you notice a break in the _display of the tile_ every time the tile resolution changes (e.g. from 5.9 - which is tile 5 multiplied by 1.9 - to 6 - which is tile 6)?
What happens if you zoom in and out and in and out on the same location: do you still experience that little break?

**Comment by miguel-porto** [comment]
Thank you!
Yes, it is exactly as you describe - the pinch zoom is smooth except for those little breaks when tiles from a higher resolution are loaded. It happens also when doing as you say, zooming in and out repeatedly in the same location. However, this does not happen on pinch zoom out - when pinch zooming out, the gesture is smooth all throughout the tile resolutions, tiles are replaced by lower resolution ones without any noticeable break.
But this is just a minor detail that is not of much importance.

**Comment by spyhunter99** [comment]
well it's merged, i'll open a new ticket to describe the new issue and we'll move on

**Comment by monsieurtanuki** [comment]
Let's focus on #812 now!
