### ISSUE TITLE
NoSuchElementException on detaching

### ISSUE THREAD

**Issue by miguel-porto** [osmdroid/osmdroid#802]
## Issue Type

[x] Bug

## Description and/or steps/code to reproduce the problem
I still couldn't identify what is causing the problem, but I suspect it might be related with MapTileApproximater deep zooms, see #801 
Anyway, what happens is that, sometimes (probably after many deep zoom outs), upon quitting the app, while detaching the MapView, I get the following exception. Seems simple to dirty fix, but the cause is further up, don't know where. I'll post here if I have more cues.

Cheers,

```
12-10 22:57:34.486 10786-10786/? I/OsmDroid: Database detached
12-10 22:57:34.503 10786-10786/? I/OsmDroid: Database detached
12-10 22:57:34.537 10786-10786/? D/AndroidRuntime: Shutting down VM
12-10 22:57:34.539 10786-10786/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: pt.flora_on.homemluzula, PID: 10786
java.util.NoSuchElementException
   at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:349)
   at java.util.LinkedHashMap$KeyIterator.next(LinkedHashMap.java:366)
   at org.osmdroid.tileprovider.LRUMapTileCache.clear(LRUMapTileCache.java:61)
   at org.osmdroid.tileprovider.MapTileCache.clear(MapTileCache.java:82)
   at org.osmdroid.tileprovider.MapTileProviderArray.detach(MapTileProviderArray.java:81)
   at org.osmdroid.tileprovider.MapTileProviderBasic.detach(MapTileProviderBasic.java:122)
   at org.osmdroid.views.overlay.TilesOverlay.onDetach(TilesOverlay.java:110)
   at org.osmdroid.views.overlay.DefaultOverlayManager.onDetach(DefaultOverlayManager.java:142)
   at org.osmdroid.views.MapView.onDetach(MapView.java:857)
   at org.osmdroid.views.MapView.onDetachedFromWindow(MapView.java:1125)
   at android.view.View.dispatchDetachedFromWindow(View.java:14561)
   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3071)
   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
   at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3068)
   at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5606)
   at android.view.ViewRootImpl.die(ViewRootImpl.java:5583)
   at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:397)
   at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:352)
   at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
   at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3867)
   at android.app.ActivityThread.-wrap5(ActivityThread.java)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:148)
   at android.app.ActivityThread.main(ActivityThread.java:5417)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

### If it's a bug, version(s) of android this affects:
API 23

### Version of osmdroid the issue relates to:

6.0.0-SNAPSHOT

**Comment by monsieurtanuki** [comment]
Looks like #776, where a "dirty" fix was applied, assuming that it was not worth investigating too much this java concurrency issue especially when quitting the app.

**Comment by miguel-porto** [comment]
Oops, sorry for duplicating an already fixed issue!
I note, however, that this exception never happened in v. 5.6.5, and I used it a lot.
Cheers.
