### ISSUE TITLE
StrictMode causes termination due to unreleased resources

### ISSUE THREAD

**Issue by grimace** [osmdroid/osmdroid#819]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[?] Question
[? ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
blows up and app restarts

code looks like this:

```
        BingMapTileSource.retrieveBingKey(activity);
        final BingMapTileSource aerialSource = new BingMapTileSource(null);
        new Thread(new Runnable() {
                @Override
                 public void run() {
                      aerialSource.initMetaData();
                 }
        }).start();
        aerialSource.setStyle(BingMapTileSource.IMAGERYSET_AERIALWITHLABELS);
        TileSourceFactory.addTileSource(aerialSource);

````

stack trace
```

12-23 05:45:59.331  4490  4535 E StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
12-23 05:45:59.331  4490  4535 E StrictMode: java.lang.Throwable: Explicit termination method 'end' not called
12-23 05:45:59.331  4490  4535 E StrictMode: 	at dalvik.system.CloseGuard.open(CloseGuard.java:180)
12-23 05:45:59.331  4490  4535 E StrictMode: 	at java.util.zip.Inflater.<init>(Inflater.java:82)
12-23 05:45:59.331  4490  4535 E StrictMode: 	at com.android.okhttp.okio.GzipSource.<init>(GzipSource.java:62)
12-23 05:45:59.331  4490  4535 E StrictMode: 	at com.android.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:645)
12-23 05:45:59.331  4490  4535 E StrictMode: 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:827)
12-23 05:45:59.331  4490  4535 E StrictMode: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443)
12-23 05:45:59.331  4490  4535 E StrictMode: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
12-23 05:45:59.331  4490  4535 E StrictMode: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:501)
12-23 05:45:59.331  4490  4535 E StrictMode: 	at org.osmdroid.tileprovider.tilesource.bing.BingMapTileSource.getMetaData(BingMapTileSource.java:232)
12-23 05:45:59.331  4490  4535 E StrictMode: 	at org.osmdroid.tileprovider.tilesource.bing.BingMapTileSource.initMetaData(BingMapTileSource.java:200)
12-23 05:45:59.331  4490  4535 E StrictMode: 	at com.company.Launcher.TVLayout$9.run(DTVLayout.java:1447)
12-23 05:45:59.331  4490  4535 E StrictMode: 	at java.lang.Thread.run(Thread.java:818)
12-23 05:45:59.331  4490  4535 W System.err: StrictMode VmPolicy violation with POLICY_DEATH; shutting down.


```
### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

5.6.5

**Comment by spyhunter99** [comment]
Thanks I think I see the issue, should be an easy fix

**Comment by spyhunter99** [comment]
I'll add that you probably have enabled strict mode compliance in your app. Which is totally fine. I honestly have never heard of it and found details here: https://developer.android.com/reference/android/os/StrictMode.ThreadPolicy.Builder.html

This commit adds that to the sample app at API11+ and only on debug builds. I found a few other related issues that should be cleaned up now. If you can, please test our this branch with your app to see if the situation is improved

**Comment by spyhunter99** [comment]
merged
