### ISSUE TITLE
close() missing in org.osmdroid.tileprovider.constants.OpenStreetMapTileProviderConstants.setUserAgentValue(OpenStreetMapTileProviderConstants.java:67)

### ISSUE THREAD

**Issue by InI4** [osmdroid/osmdroid#821]
## Issue Type

[ ] Question
[X ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
No big deal, but libraries should be clean, shouldn't they? Reading Issue #819 I enabled some StrictMode policies on my app and got (beside lots of other things) this trace:

```
 java.lang.Throwable: Explicit termination method 'close' not called
                                                                             at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                             at java.io.FileInputStream.<init>(FileInputStream.java:78)
                                                                             at java.util.Scanner.<init>(Scanner.java:158)
                                                                             at java.util.Scanner.<init>(Scanner.java:138)
                                                                             at org.osmdroid.tileprovider.util.StorageUtils.getAllStorageLocationsRevised(StorageUtils.java:507)
                                                                             at org.osmdroid.tileprovider.util.StorageUtils.getStorageList(StorageUtils.java:198)
                                                                             at org.osmdroid.tileprovider.util.StorageUtils.getStorage(StorageUtils.java:232)
                                                                             at org.osmdroid.tileprovider.constants.OpenStreetMapTileProviderConstants.<clinit>(OpenStreetMapTileProviderConstants.java:25)
                                                                             at org.osmdroid.tileprovider.constants.OpenStreetMapTileProviderConstants.setUserAgentValue(OpenStreetMapTileProviderConstants.java:67)
```

## Environment

Just an Activity with a MapView.

### If it's a bug, version(s) of android this affects:

Found in a 6.0 Emulator.

### Version of osmdroid the issue relates to:

5.6.5

**Comment by InI4** [comment]
OK, getting beyond that point, there seems to be more:
`java.lang.Throwable: Explicit termination method 'close' not called
                                                                             at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                             at java.io.FileInputStream.<init>(FileInputStream.java:78)
                                                                             at java.util.Scanner.<init>(Scanner.java:158)
                                                                             at java.util.Scanner.<init>(Scanner.java:138)
                                                                             at org.osmdroid.tileprovider.util.StorageUtils.getAllStorageLocationsRevised(StorageUtils.java:507)
                                                                             at org.osmdroid.tileprovider.util.StorageUtils.getStorageList(StorageUtils.java:198)
                                                                             at org.osmdroid.tileprovider.util.StorageUtils.getStorage(StorageUtils.java:232)
                                                                             at org.osmdroid.config.DefaultConfigurationProvider.<init>(DefaultConfigurationProvider.java:74)
                                                                             at org.osmdroid.config.Configuration.getInstance(Configuration.java:23)
                                                                             at org.osmdroid.views.MapView.<init>(MapView.java:158)
                                                                             at org.osmdroid.views.MapView.<init>(MapView.java:212)`

**Comment by spyhunter99** [comment]
see #819, i think they were fixed on that branch

**Comment by InI4** [comment]
Still have it on the (right now) Sonatype Snapshot. Note that the things I reported were missing "close" actions. #819 was about missing "end". 

Message is:
`java.lang.Throwable: Explicit termination method 'close' not called`

Positions is:
`org.osmdroid.tileprovider.util.StorageUtils.getAllStorageLocationsRevised(StorageUtils.java:507)`

(Actually same as with 5.6.5)

**Comment by spyhunter99** [comment]
I just pushed another snapshot. Give it a shot

**Comment by spyhunter99** [comment]
The end bit is not our code and most likely is called after closing the connection, which should be fixed. I just pushed another snapshot, give it a shot when you have time

**Comment by InI4** [comment]
I just pulled another snapshot and it seems to work now.

Note (and this also fits here: #824 ) I realized, that I have to go to gradle cache and manually delete the last downloaded snapshot, as gradle does not see a reason to automatically update a snapshot with all visible version numbers the same.

**Comment by spyhunter99** [comment]
if you work with snapshots a lot, you can add this to your root build.gradle file

````
allprojects  {
    // forces all changing dependencies (i.e. SNAPSHOTs) to automagicially download
    configurations.all {
        resolutionStrategy {
            cacheChangingModulesFor 0, 'seconds'
        }
    }
````
