### ISSUE TITLE
Systematic crash with .gemf files

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#850]
## Issue Type
[v] Bug

## Description and/or steps/code to reproduce the problem
* I have a .gemf file (usgssat-jpg.gemf) in my osmdroid folder: basically, USA at zoom 2 or 3.
* each time I go to the USA map at zoom 2 or 3, I have a glimpse of the tiles, then within 10ths of second a crash like that:
````
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
              java.lang.Throwable: Explicit termination method 'close' not called
                  at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                  at java.io.RandomAccessFile.<init>(RandomAccessFile.java:127)
                  at java.io.RandomAccessFile.<init>(RandomAccessFile.java:149)
                  at org.osmdroid.util.GEMFFile$GEMFInputStream.<init>(GEMFFile.java:675)
                  at org.osmdroid.util.GEMFFile.getInputStream(GEMFFile.java:617)
                  at org.osmdroid.tileprovider.modules.GEMFFileArchive.getInputStream(GEMFFileArchive.java:39)
                  at org.osmdroid.tileprovider.modules.MapTileFileArchiveProvider.getInputStream(MapTileFileArchiveProvider.java:181)
                  at org.osmdroid.tileprovider.modules.MapTileFileArchiveProvider.access$100(MapTileFileArchiveProvider.java:30)
                  at org.osmdroid.tileprovider.modules.MapTileFileArchiveProvider$TileLoader.loadTile(MapTileFileArchiveProvider.java:222)
                  at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.run(MapTileModuleProviderBase.java:317)
                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                  at java.lang.Thread.run(Thread.java:818)
````
I don't know what the `StrictMode` of the log message represents. Maybe this bug appeared first when I recently upgraded Android Studio and had to have it modify some compilation parameters.

### Version of osmdroid the issue relates to:
6.0.0

**Comment by spyhunter99** [comment]
on it
