### ISSUE TITLE
android 4.4.2_r3 missing in Android SDK Deployer

### ISSUE THREAD

**Issue by qumaciel** [osmdroid/osmdroid#94]
I was trying to import the project to a brand new computer and a figured that the Android SDK Deployer doesn't have the android 4.4.2_r3.jar. It was updated to 4.4.2_r4.

After while, I tried to update to the latest android version (5.0.1_r2), but a got errors in the test phase:

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
org.apache.maven.surefire.util.SurefireReflectionException: java.lang.reflect.InvocationTargetException; nested exception is java.lang.reflect.InvocationTargetException: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.apache.maven.surefire.util.ReflectionUtils.instantiateOneArg(ReflectionUtils.java:130)
	at org.apache.maven.surefire.booter.SurefireReflector.instantiateProvider(SurefireReflector.java:239)
	at org.apache.maven.surefire.booter.ProviderFactory.createProvider(ProviderFactory.java:122)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:81)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.UnsupportedClassVersionError: junit/framework/Test : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at org.apache.maven.surefire.util.ReflectionUtils.tryLoadClass(ReflectionUtils.java:213)
	at org.apache.maven.surefire.common.junit3.JUnit3TestChecker.<init>(JUnit3TestChecker.java:49)
	at org.apache.maven.surefire.common.junit4.JUnit4TestChecker.<init>(JUnit4TestChecker.java:44)
	at org.apache.maven.surefire.junit4.JUnit4Provider.<init>(JUnit4Provider.java:82)
	... 10 more

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.545 s
[INFO] Finished at: 2015-01-29T16:42:15-02:00
[INFO] Final Memory: 6M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project osmdroid-android: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
[ERROR] 

Any ideas how to solve it?!

**Comment by trofimchyk** [comment]
in pom.xml write **<version>4.4.2_r4</version>** instead of **<version>4.4.2_r3</version>**

**Comment by kurtzmarc** [comment]
As @trofimchyk points out, sometimes we lag behind in updating our POMs to the latest version. Simply update the POM.xml file in the root with the proper new version. Sending us a pull request also helps get this applied to the repo quicker!
