### ISSUE TITLE
Folder overlay causing NPE preventing rendering of all child overlays

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#941]
## Issue Type

[ ] Bug

## Description and/or steps/code to reproduce the problem

````
 onDraw(false)
02-18 14:36:12.283 12514-12514/org.osmdroid E/OsmDroid: error dispatchDraw, probably in edit mode
                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'void org.osmdroid.views.overlay.TilesOverlay.protectDisplayedTilesForCache(android.graphics.Canvas, org.osmdroid.views.MapView)' on a null object reference
                                                            at org.osmdroid.views.overlay.DefaultOverlayManager.onDraw(DefaultOverlayManager.java:131)
                                                            at org.osmdroid.views.overlay.FolderOverlay.draw(FolderOverlay.java:73)
                                                            at org.osmdroid.views.overlay.gridlines.LatLonGridlineOverlay2.draw(LatLonGridlineOverlay2.java:53)
                                                            at org.osmdroid.views.overlay.DefaultOverlayManager.onDraw(DefaultOverlayManager.java:147)
                                                            at org.osmdroid.views.MapView.dispatchDraw(MapView.java:1160)
````

### Version of osmdroid the issue relates to:

6.0.0

**Comment by spyhunter99** [comment]
Probably introduced by #908
