### ISSUE TITLE
SampleZoomToBounding fails randomly

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#979]
````
04-02 21:12:43.108  1644  1644 E UncaughtException: Got an uncaught exception: java.lang.IllegalArgumentException: east must be less than 180.0 value was N:30.672279962736386; E:314.56874074231985; S:2.9142932777241697; W:38.52950140593643
04-02 21:12:43.108  1644  1644 W System.err: java.lang.IllegalArgumentException: east must be less than 180.0 value was N:30.672279962736386; E:314.56874074231985; S:2.9142932777241697; W:38.52950140593643
04-02 21:12:43.108  1644  1644 W System.err:    at org.osmdroid.util.BoundingBox.set(BoundingBox.java:65)
04-02 21:12:43.108  1644  1644 W System.err:    at org.osmdroid.util.BoundingBox.<init>(BoundingBox.java:43)
04-02 21:12:43.108  1644  1644 W System.err:    at org.osmdroid.util.BoundingBox.fromGeoPoints(BoundingBox.java:296)
04-02 21:12:43.108  1644  1644 W System.err:    at org.osmdroid.views.overlay.Polygon.setDefaultInfoWindowLocation(Polygon.java:357)
04-02 21:12:43.108  1644  1644 W System.err:    at org.osmdroid.views.overlay.Polygon.setPoints(Polygon.java:171)
04-02 21:12:43.108  1644  1644 W System.err:    at org.osmdroid.samplefragments.events.SampleZoomToBounding.onClick(SampleZoomToBounding.java:81)
04-02 21:12:43.108  1644  1644 W System.err:    at android.view.View.performClick(View.java:5198)
````

**Comment by monsieurtanuki** [comment]
What triggers the exception is:
* the recent addition of `Polygon.setDefaultInfoWindowLocation` by @MKergall
* this new step's goal is to compute the center of the polygon, by using a `BoundingBox`
* a `BoundingBox` doesn't accept `IGeoPoint` beyond the world, e.g. with east beyond 180°

We could argue about `BoundingBox`: should it enforce strict "corners should be in the known world" rules? How do we deal with west/east/date line? Isn't there something to fix in `fromGeoPoints`, where longitudes are pre-truncated in order to fit into the world?

Beyond those `BoundingBox` questions, I think the best way to solve this issue would be to implement something like a `LinearRing.getCenter`: that's what we actually need in `Polygon.setDefaultInfoWindowLocation`.
I'm on it.

**Comment by monsieurtanuki** [comment]
Just committed #980 
The next step would be to edit `Polygon.setDefaultInfoWindowLocation` and replace
````java
BoundingBox bb = BoundingBox.fromGeoPoints(mOutline.getPoints());
mInfoWindowLocation = bb.getCenterWithDateLine();
````
by 
````java
mInfoWindowLocation = mOutline.getCenter();
````
Which is unfortunately beyond my git skills.

**Comment by monsieurtanuki** [comment]
@spyhunter99 Probably fixed by #993: would you double check?

**Comment by spyhunter99** [comment]
on it
