### ISSUE TITLE
java.lang.IllegalArgumentException: south more than -85.05112877980659 value was N:80.0; E:179.97999572753906; S:-89.9800033569336; ...

### ISSUE THREAD

**Issue by pasniak** [osmdroid/osmdroid#986]
## Issue Type

[x] Question

After today's pull I get exception for point coordinates which look okay:
```
Caused by: java.lang.IllegalArgumentException: south more than -85.05112877980659 value was N:80.0; E:179.97999572753906; S:-89.9800033569336; W:-177.3699951171875
at org.osmdroid.util.BoundingBox.set(BoundingBox.java:61)
at org.osmdroid.util.BoundingBox.<init>(BoundingBox.java:43)
at org.osmdroid.views.overlay.simplefastpoint.SimpleFastPointOverlay.<init>(SimpleFastPointOverlay.java:101)
```
These points do not move and osmdroid displayed those points fine for a year or so, so is it a bug, or I have to filter my points ?

### Version of osmdroid the issue relates to:

latest

**Comment by spyhunter99** [comment]
the max/min latitude that can be displayed using the web mercator project is +/-85.05112877980659. Although your location may be a valid location on earth, it really can't be displayed even reasonably accurately using the web mercator projection. Actually accuracy suffers significantly near the poles. I wouldn't rely on the pixel to lat/lon mapping

**Comment by pasniak** [comment]
ok, thanks, I added a filter for those.
