### ISSUE TITLE
Crash in demos around Bookmarks

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#998]
## Issue Type

- [x] Bug

## Description and/or steps/code to reproduce the problem

* go to demo "More Samples / Location / Heading/Compass up"
* go back
* go again to demo "More Samples / Location / Heading/Compass up"
* then it crashes with that kind of log:
````java
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
              java.lang.Throwable: Explicit termination method 'close' not called
                  at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                  at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:909)
                  at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:878)
                  at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:699)
                  at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:714)
                  at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:707)
                  at org.osmdroid.samplefragments.bookmarks.BookmarkDatastore.<init>(BookmarkDatastore.java:45)
                  at org.osmdroid.samplefragments.bookmarks.BookmarkSample.<init>(BookmarkSample.java:26)
                  at java.lang.reflect.Constructor.newInstance(Native Method)
                  at java.lang.Class.newInstance(Class.java:1656)
                  at org.osmdroid.samplefragments.SampleFactory.getSample(SampleFactory.java:304)
````

### Version of osmdroid the issue relates to:

6.0.2

**Comment by spyhunter99** [comment]
hmm that's strange since there's definitely a close call in onDestroy

**Comment by monsieurtanuki** [comment]
@spyhunter99 It's even stranger because I'm not even supposed to use bookmarks in this demo.

**Comment by spyhunter99** [comment]
with your procedure, did you ever load the bookmarks sample?

**Comment by spyhunter99** [comment]
oh i see the problem, never mind

**Comment by spyhunter99** [comment]
@monsieurtanuki want to retest?

**Comment by monsieurtanuki** [comment]
@spyhunter99 As written in my comment about your commit, it fixed the issue.
Please PR and merge.
